"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.extension_dict
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
CPP_NAMESPACE_FIELD_NUMBER: builtins.int
PTR_FIELD_NUMBER: builtins.int
IOBUF_FIELD_NUMBER: builtins.int
cpp_namespace: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FileOptions, builtins.str]
'A file option that customizes the namespace within that file.\n\nExample:\n\n```proto\nsyntax "proto3";\n\noption (redpanda.core.pbgen.cpp_namespace) = "proto::bar";\n```\n'
ptr: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, builtins.bool]
'A field option that can only be applied to message subfields and\neffects the code generation for Redpanda C++ protocol buffers.\n\nThis value set to true puts the value behind a std::unique_ptr instead\nof inline into the generated class. This is needed for recursive\nstructures that need the level of indirection.\n\nExample:\n\n```proto\nmessage Foo {\n  Bar bar = 1 [(redpanda.core.pbgen.ptr) = true];\n}\n```\n'
iobuf: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, builtins.bool]
"A field option that can only be applied to string fields and\neffects the code generation for Redpanda C++ protocol buffers.\n\nThis value set to true puts the value as an iobuf instead of a\nss::sstring. This should be used whenever it's possible a string can be\nlarger than 128KiB.\n\nExample:\n\n```proto\nmessage Foo {\n  string bar = 1 [(redpanda.core.pbgen.iobuf) = true];\n}\n```\n"