"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RPCAuthZLevel:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RPCAuthZLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RPCAuthZLevel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LEVEL_UNSPECIFIED: _RPCAuthZLevel.ValueType
    PUBLIC: _RPCAuthZLevel.ValueType
    USER: _RPCAuthZLevel.ValueType
    SUPERUSER: _RPCAuthZLevel.ValueType

class RPCAuthZLevel(_RPCAuthZLevel, metaclass=_RPCAuthZLevelEnumTypeWrapper):
    """The authentication level for this handler."""
LEVEL_UNSPECIFIED: RPCAuthZLevel.ValueType
PUBLIC: RPCAuthZLevel.ValueType
USER: RPCAuthZLevel.ValueType
SUPERUSER: RPCAuthZLevel.ValueType
Global___RPCAuthZLevel: typing_extensions.TypeAlias = RPCAuthZLevel

@typing.final
class RPCOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    AUTHZ_FIELD_NUMBER: builtins.int
    HTTP_ROUTE_FIELD_NUMBER: builtins.int
    authz: Global___RPCAuthZLevel.ValueType
    "The authentication level required to invoke the handler. Must be\n    specified.\n\n    APIs should default to SUPERUSER, if you'd like to create an admin API at\n    another level, please consult the Redpanda core team first.\n    "
    http_route: builtins.str
    'The alternative HTTP route to use for this handler. This is used to give\n    "prettier" HTTP routes to the user. This is an additional route used to\n    alias the ConnectRPC route that is automatically generated.\n    '

    def __init__(self, *, authz: Global___RPCAuthZLevel.ValueType=..., http_route: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['authz', b'authz', 'http_route', b'http_route']) -> None:
        ...
Global___RPCOptions: typing_extensions.TypeAlias = RPCOptions
RPC_FIELD_NUMBER: builtins.int
rpc: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.MethodOptions, Global___RPCOptions]
'A RPC method option for the authentication required to invoke\nthe handler. Must be specified.\n\nExample:\n\n```proto\nservice Foo {\n\n  rpc GetFoo(GetFooRequest) returns (GetFooResponse) {\n    option (redpanda.core.pbgen.rpc) = {\n      authz: USER,\n      http_route: "/v2/myapi/foo",\n  }\n\n}\n```\n'