# Auto-generated by gen-bazel-deps.py — do not edit manually.
# Re-generate with:
#   python3 nix/gen-bazel-deps.py \
#     --lockfile MODULE.bazel.lock \
#     --bcr $(nix-build --no-out-link -E 'with import <nixpkgs> {}; callPackage ./nix/bcr.nix {}') \
#     --module-bazel MODULE.bazel \
#     > nix/bazel-deps.nix
# 230 archives
[
  {
    url = "http://www.colm.net/files/ragel/ragel-6.10.tar.gz";
    sha256 = "5f156edb65d20b856d638dd9ee2dfb43285914d9aa2b6ec779dac0270cd56c3f";
    name = "ragel-6.10.tar.gz";
  }
  {
    url = "https://dl.grafana.com/grafana/release/12.3.1/grafana_12.3.1_20271043721_linux_amd64.tar.gz";
    sha256 = "75d03b5ac2dc7b009625869355225d73e5b29866efbd999479bdd24429a695db";
    name = "grafana_12.3.1_20271043721_linux_amd64.tar.gz";
  }
  {
    url = "https://dl.grafana.com/grafana/release/12.3.1/grafana_12.3.1_20271043721_linux_arm64.tar.gz";
    sha256 = "889cac6634a365dacbc712e1e49ea2233d40b9c958e61266f39949537ce63cdd";
    name = "grafana_12.3.1_20271043721_linux_arm64.tar.gz";
  }
  {
    url = "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2025-04-03T14-56-28Z";
    sha256 = "cebd628ae859b4670de9c04b0cbf5600a498166da2031ad634c987208d89ae94";
    name = "minio.RELEASE.2025-04-03T14-56-28Z";
  }
  {
    url = "https://dl.min.io/server/minio/release/linux-arm64/archive/minio.RELEASE.2025-04-03T14-56-28Z";
    sha256 = "5ecf7891298aebe495928f84e6eaf3b59cb7dddb499c7add8c5027eb0ba8f0e9";
    name = "minio.RELEASE.2025-04-03T14-56-28Z";
  }
  {
    url = "https://github.com/Cyan4973/xxHash/archive/bbb27a5efb85b92a0486cf361a8635715a53f6ba.tar.gz";
    sha256 = "716fbe4fc85ecd36488afbbc635b59b5ab6aba5ed3b69d4a32a46eae5a453d38";
    name = "bbb27a5efb85b92a0486cf361a8635715a53f6ba.tar.gz";
  }
  {
    url = "https://github.com/HdrHistogram/HdrHistogram_c/archive/refs/tags/0.11.8.tar.gz";
    sha256 = "bb95351a6a8b242dc9be1f28562761a84d4cf0a874ffc90a9b630770a6468e94";
    name = "0.11.8.tar.gz";
  }
  {
    url = "https://github.com/JetBrains/kotlin/releases/download/v1.9.23/kotlin-compiler-1.9.23.zip";
    sha256 = "93137d3aab9afa9b27cb06a824c2324195c6b6f6179d8a8653f440f5bd58be88";
    name = "kotlin-compiler-1.9.23.zip";
  }
  {
    url = "https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-aarch64.tar.gz";
    sha256 = "f2654bf780b53f170bbbec44d8ac67d401d24788e590faa53036a89476efa91e";
    name = "cmake-3.23.2-linux-aarch64.tar.gz";
  }
  {
    url = "https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz";
    sha256 = "aaced6f745b86ce853661a595bdac6c5314a60f8181b6912a0a4920acfa32708";
    name = "cmake-3.23.2-linux-x86_64.tar.gz";
  }
  {
    url = "https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-macos-universal.tar.gz";
    sha256 = "853a0f9af148c5ef47282ffffee06c4c9f257be2635936755f39ca13c3286c88";
    name = "cmake-3.23.2-macos-universal.tar.gz";
  }
  {
    url = "https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-windows-i386.zip";
    sha256 = "6a4fcd6a2315b93cb23c93507efccacc30c449c2bf98f14d6032bb226c582e07";
    name = "cmake-3.23.2-windows-i386.zip";
  }
  {
    url = "https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-windows-x86_64.zip";
    sha256 = "2329387f3166b84c25091c86389fb891193967740c9bcf01e7f6d3306f7ffda0";
    name = "cmake-3.23.2-windows-x86_64.zip";
  }
  {
    url = "https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2.tar.gz";
    sha256 = "f316b40053466f9a416adf981efda41b160ca859e97f6a484b447ea299ff26aa";
    name = "cmake-3.23.2.tar.gz";
  }
  {
    url = "https://github.com/NixOS/patchelf/releases/download/0.18.0/patchelf-0.18.0.tar.gz";
    sha256 = "64de10e4c6b8b8379db7e87f58030f336ea747c0515f381132e810dbf84a86e7";
    name = "patchelf-0.18.0.tar.gz";
  }
  {
    url = "https://github.com/abseil/abseil-cpp/releases/download/20250814.0/abseil-cpp-20250814.0.tar.gz";
    sha256 = "9b2b72d4e8367c0b843fa2bcfa2b08debbe3cee34f7aaa27de55a6cbb3e843db";
    name = "abseil-cpp-20250814.0.tar.gz";
  }
  {
    url = "https://github.com/antithesishq/antithesis-sdk-cpp/archive/refs/tags/0.4.7.tar.gz";
    sha256 = "e083cec08b4e173df23e0b07beda5509eddebc1f11d9adc71a8a39d0a229da97";
    name = "0.4.7.tar.gz";
  }
  {
    url = "https://github.com/apple/swift-argument-parser/archive/refs/tags/1.3.1.tar.gz";
    sha256 = "4d964f874b251abc280ee28f0f187de3c13a6122a9561524f66a10768ca2d837";
    name = "1.3.1.tar.gz";
  }
  {
    url = "https://github.com/axboe/liburing/archive/refs/tags/liburing-2.14.tar.gz";
    sha256 = "5f80964108981c6ad979c735f0b4877d5f49914c2a062f8e88282f26bf61de0c";
    name = "liburing-2.14.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/bazel-gazelle/releases/download/v0.45.0/bazel-gazelle-v0.45.0.tar.gz";
    sha256 = "e467b801046b6598c657309b45d2426dc03513777bd1092af2c62eebf990aca5";
    name = "bazel-gazelle-v0.45.0.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/bazel_features/releases/download/v1.15.0/bazel_features-v1.15.0.tar.gz";
    sha256 = "ba1282c1aa1d1fffdcf994ab32131d7c7551a9bc960fbf05f42d55a1b930cbfb";
    name = "bazel_features-v1.15.0.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/bazel_features/releases/download/v1.33.0/bazel_features-v1.33.0.tar.gz";
    sha256 = "c41853e3b636c533b86bf5ab4658064e6cc9db0a3bce52cbff0629e094344ca9";
    name = "bazel_features-v1.33.0.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/rules_go/releases/download/v0.59.0/rules_go-v0.59.0.zip";
    sha256 = "68af54cb97fbdee5e5e8fe8d210d15a518f9d62abfd71620c3eaff3b26a5ff86";
    name = "rules_go-v0.59.0.zip";
  }
  {
    url = "https://github.com/bazel-contrib/rules_jvm_external/releases/download/6.7/rules_jvm_external-6.7.tar.gz";
    sha256 = "a1e351607f04fed296ba33c4977d3fe2a615ed50df7896676b67aac993c53c18";
    name = "rules_jvm_external-6.7.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/supply-chain/releases/download/v0.0.5/supply-chain-v0.0.5.tar.gz";
    sha256 = "49ed11e5d6b752c55fa539cbb10b2736974f347b081d7bd500a80dacb7dbec06";
    name = "supply-chain-v0.0.5.tar.gz";
  }
  {
    url = "https://github.com/bazel-contrib/toolchains_llvm/archive/d103be73bce9a804ebc4e57637fbaf9d6f23e682.tar.gz";
    sha256 = "b97d41f29fa274c3e59f53c247e1a5afee625d99ef0f1ea1d61d268a23f35900";
    name = "d103be73bce9a804ebc4e57637fbaf9d6f23e682.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/apple_support/releases/download/1.23.1/apple_support.1.23.1.tar.gz";
    sha256 = "ee20cc5c0bab47065473c8033d462374dd38d172406ecc8de5c8f08487943f2f";
    name = "apple_support.1.23.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.1/bazel-skylib-1.8.1.tar.gz";
    sha256 = "51b5105a760b353773f904d2bbc5e664d0987fbaf22265164de65d43e910d8ac";
    name = "bazel-skylib-1.8.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/platforms/releases/download/1.0.0/platforms-1.0.0.tar.gz";
    sha256 = "3384eb1c30762704fbe38e440204e114154086c8fc8a8c2e3e28441028c019a8";
    name = "platforms-1.0.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_android/archive/refs/tags/v0.1.1.tar.gz";
    sha256 = "6461c1c5744442b394f46645957d6bd3420eb1b421908fe63caa03091b1b3655";
    name = "v0.1.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip";
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806";
    name = "v0.1.1.zip";
  }
  {
    url = "https://github.com/bazelbuild/rules_apple/releases/download/3.16.0/rules_apple.3.16.0.tar.gz";
    sha256 = "86ff9c3a2c7bc308fef339bcd5b3819aa735215033886cc281eb63f10cd17976";
    name = "rules_apple.3.16.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_cc/releases/download/0.2.17/rules_cc-0.2.17.tar.gz";
    sha256 = "283fa1cdaaf172337898749cf4b9b1ef5ea269da59540954e51fba0e7b8f277a";
    name = "rules_cc-0.2.17.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_foreign_cc/releases/download/0.12.0/rules_foreign_cc-0.12.0.tar.gz";
    sha256 = "a2e6fb56e649c1ee79703e99aa0c9d13c6cc53c8d7a0cbb8797ab2888bbc99a3";
    name = "rules_foreign_cc-0.12.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_java/releases/download/8.14.0/rules_java-8.14.0.tar.gz";
    sha256 = "bbe7d94360cc9ed4607ec5fd94995fd1ec41e84257020b6f09e64055281ecb12";
    name = "rules_java-8.14.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_kotlin/releases/download/v1.9.6/rules_kotlin-v1.9.6.tar.gz";
    sha256 = "3b772976fec7bdcda1d84b9d39b176589424c047eb2175bed09aac630e50af43";
    name = "rules_kotlin-v1.9.6.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_license/releases/download/1.0.0/rules_license-1.0.0.tar.gz";
    sha256 = "26d4021f6898e23b82ef953078389dd49ac2b5618ac564ade4ef87cced147b38";
    name = "rules_license-1.0.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/1.0.1/rules_pkg-1.0.1.tar.gz";
    sha256 = "d20c951960ed77cb7b341c2a59488534e494d5ad1d30c4818c736d57772a9fef";
    name = "rules_pkg-1.0.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_proto/releases/download/7.1.0/rules_proto-7.1.0.tar.gz";
    sha256 = "14a225870ab4e91869652cfd69ef2028277fc1dc4910d65d353b62d6e0ae21f4";
    name = "rules_proto-7.1.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.23.1.tar.gz";
    sha256 = "84aec9e21cc56fbc7f1335035a71c850d1b9b5cc6ff497306f84cced9a769841";
    name = "0.23.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_rust/releases/download/0.60.0/rules_rust-0.60.0.tar.gz";
    sha256 = "7825214ccad7c2482cb490ac91dbc1e88b30223062796ce328aca893b74ae342";
    name = "rules_rust-0.60.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_shell/releases/download/v0.3.0/rules_shell-v0.3.0.tar.gz";
    sha256 = "d8cd4a3a91fc1dc68d4c7d6b655f09def109f7186437e3f50a9b60ab436a0c53";
    name = "rules_shell-v0.3.0.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/rules_swift/releases/download/2.1.1/rules_swift.2.1.1.tar.gz";
    sha256 = "9919ed1d8dae509645bfd380537ae6501528d8de971caebed6d5185b9970dc4d";
    name = "rules_swift.2.1.1.tar.gz";
  }
  {
    url = "https://github.com/bazelbuild/stardoc/releases/download/0.7.2/stardoc-0.7.2.tar.gz";
    sha256 = "0e1ed4a98f26e718776bd64d053d02bb34d98572ccd03d6ba355112a1205706b";
    name = "stardoc-0.7.2.tar.gz";
  }
  {
    url = "https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.tar.gz";
    sha256 = "4d27e9efed0f6f152dc28db6430b9d3dfb40c0345da7342eaa5a987dde57bd95";
    name = "boost-1.84.0.tar.gz";
  }
  {
    url = "https://github.com/bufbuild/protovalidate/releases/download/v1.0.0/protovalidate-1.0.0.tar.gz";
    sha256 = "39a3f262614ffc23e89507f4dbdae535d8d73021713f580733b6a8dfdf06f734";
    name = "protovalidate-1.0.0.tar.gz";
  }
  {
    url = "https://github.com/bufbuild/rules_buf/archive/refs/tags/v0.3.0.tar.gz";
    sha256 = "89c6d6e6523802ee7f1210340a69fab4ee0b47554953a1ecbe359319fd3f93dc";
    name = "v0.3.0.tar.gz";
  }
  {
    url = "https://github.com/bytecodealliance/wasmtime/archive/9e1084ffac08b1bf9c82de40c0efc1baff14b9ad.tar.gz";
    sha256 = "a7f989b170d109696b928b4b3d1ec1d930064af7df47178e1341bd96e5c34465";
    name = "9e1084ffac08b1bf9c82de40c0efc1baff14b9ad.tar.gz";
  }
  {
    url = "https://github.com/danielaparker/jsoncons/archive/ffd2540bc9cfb54c16ef4d29d80622605d8dfbe8.tar.gz";
    sha256 = "078ba32cd1198cbeb1903fbf4881d4960b226bdf8083d9f5a927b96f0aa8d6dd";
    name = "ffd2540bc9cfb54c16ef4d29d80622605d8dfbe8.tar.gz";
  }
  {
    url = "https://github.com/doctest/doctest/archive/refs/tags/v2.4.12.tar.gz";
    sha256 = "73381c7aa4dee704bd935609668cf41880ea7f19fa0504a200e13b74999c2d70";
    name = "v2.4.12.tar.gz";
  }
  {
    url = "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz";
    sha256 = "eb33e51f49a15e023950cd7825ca74a4a2b43db8354825ac24fc1b7ee09e6fa3";
    name = "zstd-1.5.7.tar.gz";
  }
  {
    url = "https://github.com/fmeum/buildozer/releases/download/v7.1.2/buildozer-v7.1.2.tar.gz";
    sha256 = "fc77c37f08e674508a5798d84918ae52b3b9510199e0ac01112a378967da4158";
    name = "buildozer-v7.1.2.tar.gz";
  }
  {
    url = "https://github.com/fmeum/googleapis-rules-registry/releases/download/v1.0.0/googleapis-rules-registry-v1.0.0.tar.gz";
    sha256 = "af7b098716da243485a91e1e679b2c7c8ee28bb391b734ddcb1adce5a992e9be";
    name = "googleapis-rules-registry-v1.0.0.tar.gz";
  }
  {
    url = "https://github.com/fmtlib/fmt/archive/refs/tags/9.1.0.tar.gz";
    sha256 = "5dea48d1fcddc3ec571ce2058e13910a0d4a6bab4cc09a809d8b1dd1c88ae6f2";
    name = "9.1.0.tar.gz";
  }
  {
    url = "https://github.com/foonathan/lexy/archive/refs/tags/v2025.05.0.tar.gz";
    sha256 = "ae867846b890b7564d633cf28d39dfc4938fe7c54515126f720c1762de5eab30";
    name = "v2025.05.0.tar.gz";
  }
  {
    url = "https://github.com/google/boringssl/releases/download/0.20250818.0/boringssl-0.20250818.0.tar.gz";
    sha256 = "64529449ef458381346b163302523a1fb876e5b667bec4a4bd38d0d2fff8b42b";
    name = "boringssl-0.20250818.0.tar.gz";
  }
  {
    url = "https://github.com/google/crc32c/archive/refs/tags/1.1.0.tar.gz";
    sha256 = "49de137bf1c2eb6268d5122674f7dd1524b9148ba65c7b85c5ae4b9be104a25a";
    name = "1.1.0.tar.gz";
  }
  {
    url = "https://github.com/google/googletest/releases/download/v1.17.0/googletest-1.17.0.tar.gz";
    sha256 = "65fab701d9829d38cb77c14acdc431d2108bfdbf8979e40eb8ae567edf10b27c";
    name = "googletest-1.17.0.tar.gz";
  }
  {
    url = "https://github.com/google/ksp/releases/download/1.9.23-1.0.20/artifacts.zip";
    sha256 = "ee0618755913ef7fd6511288a232e8fad24838b9af6ea73972a76e81053c8c2d";
    name = "artifacts.zip";
  }
  {
    url = "https://github.com/google/libprotobuf-mutator/archive/dc4ced337a9fb4047e2dc727268fbac55ca82f73.zip";
    sha256 = "0847a2ee65552a92643131e934b50164e8b79fadc7be24b180a1c8d6dbb05952";
    name = "dc4ced337a9fb4047e2dc727268fbac55ca82f73.zip";
  }
  {
    url = "https://github.com/google/re2/releases/download/2024-07-02/re2-2024-07-02.zip";
    sha256 = "a835fe55fbdcd8e80f38584ab22d0840662c67f2feb36bd679402da9641dc71e";
    name = "re2-2024-07-02.zip";
  }
  {
    url = "https://github.com/google/snappy/archive/refs/tags/1.2.1.tar.gz";
    sha256 = "736aeb64d86566d2236ddffa2865ee5d7a82d26c9016b36218fcc27ea4f09f86";
    name = "1.2.1.tar.gz";
  }
  {
    url = "https://github.com/googleapis/googleapis/archive/f9d6fe4a6ad9ed89dfc315f284124d2104377940.zip";
    sha256 = "07283fe78fd8834604d79e5009f3c96761f94135c48088e8e17a8b6f83e94036";
    name = "f9d6fe4a6ad9ed89dfc315f284124d2104377940.zip";
  }
  {
    url = "https://github.com/krb5/krb5/archive/refs/tags/krb5-1.21.3-final.tar.gz";
    sha256 = "2157d92020d408ed63ebcd886a92d1346a1383b0f91123a0473b4f69b4a24861";
    name = "krb5-1.21.3-final.tar.gz";
  }
  {
    url = "https://github.com/lz4/lz4/releases/download/v1.9.4/lz4-1.9.4.tar.gz";
    sha256 = "0b0e3aa07c8c063ddf40b082bdf7e37a1562bda40a0ff5272957f3e987e0e54b";
    name = "lz4-1.9.4.tar.gz";
  }
  {
    url = "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz";
    sha256 = "9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23";
    name = "zlib-1.3.1.tar.gz";
  }
  {
    url = "https://github.com/martinus/unordered_dense/archive/f30ed41b58af8c79788e8581fe57a6faf856258e.tar.gz";
    sha256 = "8393d08b2a41949c70345926515036df55643e80118b608bcec6f4202d4a3026";
    name = "f30ed41b58af8c79788e8581fe57a6faf856258e.tar.gz";
  }
  {
    url = "https://github.com/nelhage/rules_boost/archive/f5b0f8c904f2487d8f5a9a956d4388724e627210.tar.gz";
    sha256 = "c10b313b1661d6d96e73a0178fe9dcb188414a5d37b82fa13e106b53a264ba92";
    name = "f5b0f8c904f2487d8f5a9a956d4388724e627210.tar.gz";
  }
  {
    url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux-aarch64.zip";
    sha256 = "5c25c6570b0155e95fce5918cb95f1ad9870df5768653afe128db822301a05a1";
    name = "ninja-linux-aarch64.zip";
  }
  {
    url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip";
    sha256 = "6f98805688d19672bd699fbbfa2c2cf0fc054ac3df1f0e6a47664d963d530255";
    name = "ninja-linux.zip";
  }
  {
    url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip";
    sha256 = "89a287444b5b3e98f88a945afa50ce937b8ffd1dcc59c555ad9b1baf855298c9";
    name = "ninja-mac.zip";
  }
  {
    url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-win.zip";
    sha256 = "f550fec705b6d6ff58f2db3c374c2277a37691678d6aba463adcbb129108467a";
    name = "ninja-win.zip";
  }
  {
    url = "https://github.com/nlohmann/json/releases/download/v3.11.3/include.zip";
    sha256 = "a22461d13119ac5c78f205d3df1db13403e58ce1bb1794edc9313677313f4a9d";
    name = "include.zip";
  }
  {
    url = "https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/1.9.6.tar.gz";
    sha256 = "f93b6dd7ce796b13d02c108bc9f79812245a82e577581c4c9aabe57075c90ea2";
    name = "1.9.6.tar.gz";
  }
  {
    url = "https://github.com/pinterest/ktlint/releases/download/1.3.0/ktlint";
    sha256 = "01b2e0ef893383a50dbeb13970fe7fa3be36ca3e83259e01649945b09d736985";
    name = "ktlint";
  }
  {
    url = "https://github.com/prometheus/prometheus/releases/download/v3.7.1/prometheus-3.7.1.linux-amd64.tar.gz";
    sha256 = "a2e8a89c09b14b2277e6151e87fc8ed18858486cbf89372656d71fcd666b51da";
    name = "prometheus-3.7.1.linux-amd64.tar.gz";
  }
  {
    url = "https://github.com/prometheus/prometheus/releases/download/v3.7.1/prometheus-3.7.1.linux-arm64.tar.gz";
    sha256 = "7ede3f3f0541b9bfd2ccca9cef57af80554f131b8e7af8900896c6e49ed2d4ef";
    name = "prometheus-3.7.1.linux-arm64.tar.gz";
  }
  {
    url = "https://github.com/protocolbuffers/protobuf/releases/download/v33.5/protobuf-33.5.bazel.tar.gz";
    sha256 = "692ea6352402599c72020d2487c8bace5c50439bac2029ed864b323e5e214e8b";
    name = "protobuf-33.5.bazel.tar.gz";
  }
  {
    url = "https://github.com/pybind/pybind11_bazel/releases/download/v2.12.0/pybind11_bazel-2.12.0.zip";
    sha256 = "a58c25c5fe063a70057fa20cb8e15f3bda19b1030305bcb533af1e45f36a4a55";
    name = "pybind11_bazel-2.12.0.zip";
  }
  {
    url = "https://github.com/redpanda-data/CRoaring/archive/c433d1c70c10fb2e40f049e019e2abbcafa6e69d.tar.gz";
    sha256 = "78487658b774f27546e79de2ddd37fca56679b23f256425d2c86aabf7d1b8066";
    name = "c433d1c70c10fb2e40f049e019e2abbcafa6e69d.tar.gz";
  }
  {
    url = "https://github.com/redpanda-data/avro/archive/46fe1e36f680d75219cba46368de38321f1810ed.tar.gz";
    sha256 = "791d9f163f458d0ba4c94251f58ef5af9157952a9569ce0968d89aeb585af34f";
    name = "46fe1e36f680d75219cba46368de38321f1810ed.tar.gz";
  }
  {
    url = "https://github.com/redpanda-data/llvm-project/releases/download/llvmorg-19.1.7/sysroot-ubuntu-22.04-aarch64-2025-02-27.tar.zst";
    sha256 = "39e3d368d57a40d36f6735dcfe3ed699c6a5962cd47c5b1f652254f077632688";
    name = "sysroot-ubuntu-22.04-aarch64-2025-02-27.tar.zst";
  }
  {
    url = "https://github.com/redpanda-data/llvm-project/releases/download/llvmorg-19.1.7/sysroot-ubuntu-22.04-x86_64-2025-02-24.tar.zst";
    sha256 = "282b7eb89ca45d2309217d5d2099cc087c1e7bd55f7891b9d2ddca648b6663b7";
    name = "sysroot-ubuntu-22.04-x86_64-2025-02-24.tar.zst";
  }
  {
    url = "https://github.com/redpanda-data/rapidjson/archive/14a5dd756e9bef26f9b53d3b4eb1b73c6a1794d5.tar.gz";
    sha256 = "d085ef6d175d9b20800958c695c7767d65f9c1985a73d172150e57e84f6cd61c";
    name = "14a5dd756e9bef26f9b53d3b4eb1b73c6a1794d5.tar.gz";
  }
  {
    url = "https://github.com/redpanda-data/seastar/archive/617d3c421a949f449942d7ce0d275af0997efb48.tar.gz";
    sha256 = "9c572c5111ef6b4f0afc6ba358696c0e2a78e118bc3c3617cf6454a9d98970de";
    name = "617d3c421a949f449942d7ce0d275af0997efb48.tar.gz";
  }
  {
    url = "https://github.com/stonier/yaml-cpp/releases/download/0.8.0/yaml-cpp-0.8.0.tar.gz";
    sha256 = "fbe74bbdcee21d656715688706da3c8becfd946d92cd44705cc6098bb23b3a16";
    name = "yaml-cpp-0.8.0.tar.gz";
  }
  {
    url = "https://github.com/tukaani-project/xz/releases/download/v5.4.5/xz-5.4.5.tar.gz";
    sha256 = "135c90b934aee8fbc0d467de87a05cb70d627da36abe518c357a873709e5b7d6";
    name = "xz-5.4.5.tar.gz";
  }
  {
    url = "https://mirror.bazel.build/download.gnome.org/binaries/win64/dependencies/gettext-runtime_0.18.1.1-2_win64.zip";
    sha256 = "1f4269c0e021076d60a54e98da6f978a3195013f6de21674ba0edbc339c5b079";
    name = "gettext-runtime_0.18.1.1-2_win64.zip";
  }
  {
    url = "https://mirror.bazel.build/download.gnome.org/binaries/win64/glib/2.26/glib-dev_2.26.1-1_win64.zip";
    sha256 = "bdf18506df304d38be98a4b3f18055b8b8cca81beabecad0eece6ce95319c369";
    name = "glib-dev_2.26.1-1_win64.zip";
  }
  {
    url = "https://mirror.bazel.build/download.gnome.org/binaries/win64/glib/2.26/glib_2.26.1-1_win64.zip";
    sha256 = "88d857087e86f16a9be651ee7021880b3f7ba050d34a1ed9f06113b8799cb973";
    name = "glib_2.26.1-1_win64.zip";
  }
  {
    url = "https://mirror.bazel.build/download.gnome.org/sources/glib/2.26/glib-2.26.1.tar.gz";
    sha256 = "bc96f63112823b7d6c9f06572d2ad626ddac7eb452c04d762592197f6e07898e";
    name = "glib-2.26.1.tar.gz";
  }
  {
    url = "https://mirror.bazel.build/ftpmirror.gnu.org/gnu/make/make-4.4.1.tar.gz";
    sha256 = "dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3";
    name = "make-4.4.1.tar.gz";
  }
  {
    url = "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.2.1/bazel-skylib-1.2.1.tar.gz";
    sha256 = "f7be3474d42aae265405a592bb7da8e171919d74c16f082a5457840f06054728";
    name = "bazel-skylib-1.2.1.tar.gz";
  }
  {
    url = "https://mirror.bazel.build/github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz";
    sha256 = "567e533adf255de73a2de35049b99923caf872a455af9ce03e01077e0d384bed";
    name = "meson-1.5.1.tar.gz";
  }
  {
    url = "https://mirror.bazel.build/github.com/ninja-build/ninja/archive/v1.12.1.tar.gz";
    sha256 = "821bdff48a3f683bc4bb3b6f0b5fe7b2d647cf65d52aeb63328c91a6c6df285a";
    name = "v1.12.1.tar.gz";
  }
  {
    url = "https://mirror.bazel.build/sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz";
    sha256 = "ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269";
    name = "bzip2-1.0.8.tar.gz";
  }
  {
    url = "https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz";
    sha256 = "6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591";
    name = "pkg-config-0.29.2.tar.gz";
  }
  {
    url = "https://static.crates.io/crates/addr2line/0.24.2/download";
    sha256 = "dfbe277e56a376000877090da837660b4427aad530e3028d44e0bffe4f89a1c1";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/allocator-api2/0.2.21/download";
    sha256 = "683d7910e743518b0e34f1186f92494becacb047c7b6bf616c96772180fef923";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/anyhow/1.0.98/download";
    sha256 = "e16d2d3311acee920a9eb8d33b8cbc1787ce4a264e85f964c2404b969bdcd487";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/arbitrary/1.4.1/download";
    sha256 = "dde20b3d026af13f561bdd0f15edf01fc734f0dafcedbaf42bba506a9517f223";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/async-trait/0.1.88/download";
    sha256 = "e539d3fca749fcee5236ab05e93a52867dd549cc157c8cb7f99595f3cedffdb5";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/bitflags/2.9.0/download";
    sha256 = "5c8214115b7bf84099f1309324e63141d4c5d7cc26862f97a0a857dbefe165bd";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/bumpalo/3.17.0/download";
    sha256 = "1628fb46dfa0b37568d12e5edd512553eccf6a22a78e8bde00bb4aed84d5bdbf";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cc/1.2.21/download";
    sha256 = "8691782945451c1c383942c4874dbe63814f61cb57ef773cda2972682b7bb3c0";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cfg-if/1.0.0/download";
    sha256 = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cobs/0.2.3/download";
    sha256 = "67ba02a97a2bd10f4b59b25c7973101c79642302776489e030cd13cdab09ed15";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-assembler-x64-meta/0.119.0/download";
    sha256 = "5b4a113455f8c0e13e3b3222a9c38d6940b958ff22573108be083495c72820e1";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-assembler-x64/0.119.0/download";
    sha256 = "263cc79b8a23c29720eb596d251698f604546b48c34d0d84f8fd2761e5bf8888";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-bforest/0.119.0/download";
    sha256 = "58f96dca41c5acf5d4312c1d04b3391e21a312f8d64ce31a2723a3bb8edd5d4d";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-bitset/0.119.0/download";
    sha256 = "7d821ed698dd83d9c012447eb63a5406c1e9c23732a2f674fb5b5015afd42202";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-codegen-meta/0.119.0/download";
    sha256 = "af2c215e0c9afa8069aafb71d22aa0e0dde1048d9a5c3c72a83cacf9b61fcf4a";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-codegen-shared/0.119.0/download";
    sha256 = "97524b2446fc26a78142132d813679dda19f620048ebc9a9fbb0ac9f2d320dcb";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-codegen/0.119.0/download";
    sha256 = "06c52fdec4322cb8d5545a648047819aaeaa04e630f88d3a609c0d3c1a00e9a0";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-control/0.119.0/download";
    sha256 = "8e32e900aee81f9e3cc493405ef667a7812cb5c79b5fc6b669e0a2795bda4b22";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-entity/0.119.0/download";
    sha256 = "d16a2e28e0fa6b9108d76879d60fe1cc95ba90e1bcf52bac96496371044484ee";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-frontend/0.119.0/download";
    sha256 = "328181a9083d99762d85954a16065d2560394a862b8dc10239f39668df528b95";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-isle/0.119.0/download";
    sha256 = "e916f36f183e377e9a3ed71769f2721df88b72648831e95bb9fa6b0cd9b1c709";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-native/0.119.0/download";
    sha256 = "fc852cf04128877047dc2027aa1b85c64f681dc3a6a37ff45dcbfa26e4d52d2f";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/cranelift-srcgen/0.119.0/download";
    sha256 = "47e1a86340a16e74b4285cc86ac69458fa1c8e7aaff313da4a89d10efd3535ee";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/crc32fast/1.4.2/download";
    sha256 = "a97769d94ddab943e4510d138150169a2758b5ef3eb191a9ee688de3e23ef7b3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/either/1.15.0/download";
    sha256 = "48c757948c5ede0e46177b7add2e67155f70e33c07fea8284df6576da70b3719";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/embedded-io/0.4.0/download";
    sha256 = "ef1a6892d9eef45c8fa6b9e0086428a2cca8491aca8f787c534a3d6d0bcb3ced";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/embedded-io/0.6.1/download";
    sha256 = "edd0f118536f44f5ccd48bcb8b111bdc3de888b58c74639dfb034a357d0f206d";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/equivalent/1.0.2/download";
    sha256 = "877a4ace8713b0bcf2a4e7eec82529c029f1d0619886d18145fea96c3ffe5c0f";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/errno/0.3.11/download";
    sha256 = "976dd42dc7e85965fe702eb8164f21f450704bdde31faefd6471dba214cb594e";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/fallible-iterator/0.3.0/download";
    sha256 = "2acce4a10f12dc2fb14a218589d4f1f62ef011b2d0cc4b3cb1bba8e94da14649";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/foldhash/0.1.5/download";
    sha256 = "d9c4f5dac5e15c24eb999c26181a6ca40b39fe946cbe4c263c7209467bc83af2";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/futures-channel/0.3.31/download";
    sha256 = "2dff15bf788c671c1934e366d07e30c1814a8ef514e1af724a602e8a2fbe1b10";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/futures-core/0.3.31/download";
    sha256 = "05f29059c0c2090612e8d742178b0580d2dc940c837851ad723096f87af6663e";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/futures-io/0.3.31/download";
    sha256 = "9e5c1b78ca4aae1ac06c48a526a655760685149f0d465d21f37abfe57ce075c6";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/futures-sink/0.3.31/download";
    sha256 = "e575fab7d1e0dcb8d0c7bcf9a63ee213816ab51902e6d244a95819acacf1d4f7";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/futures-task/0.3.31/download";
    sha256 = "f90f7dce0722e95104fcb095585910c0977252f286e354b5e3bd38902cd99988";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/futures-util/0.3.31/download";
    sha256 = "9fa08315bb612088cc391249efdc3bc77536f16c91f6cf495e6fbe85b20a4a81";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/futures/0.3.31/download";
    sha256 = "65bc07b1a8bc7c85c5f2e110c476c7389b4554ba72af57d8445ea63a576b0876";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/gimli/0.31.1/download";
    sha256 = "07e28edb80900c19c28f1072f2e8aeca7fa06b23cd4169cefe1af5aa3260783f";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/hashbrown/0.15.3/download";
    sha256 = "84b26c544d002229e640969970a2e74021aadf6e2f96372b9c58eff97de08eb3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/heck/0.5.0/download";
    sha256 = "2304e00983f87ffb38b55b444b5e3b60a884b5d30c0fca7d82fe33449bbe55ea";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/id-arena/2.2.1/download";
    sha256 = "25a2bc672d1148e28034f176e01fffebb08b35768468cc954630da77a1449005";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/indexmap/2.9.0/download";
    sha256 = "cea70ddb795996207ad57735b50c5982d8844f38ba9ee5f1aedcfb708a2aa11e";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/itertools/0.14.0/download";
    sha256 = "2b192c782037fadd9cfa75548310488aabdbf3d2da73885b31bd0abd03351285";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/itoa/1.0.15/download";
    sha256 = "4a5f13b858c8d314ee3e8f639011f7ccefe71f97f96e50151fb991f267928e2c";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/leb128fmt/0.1.0/download";
    sha256 = "09edd9e8b54e49e587e4f6295a7d29c3ea94d469cb40ab8ca70b288248a81db2";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/libc/0.2.172/download";
    sha256 = "d750af042f7ef4f724306de029d18836c26c1765a54a6a3f094cbd23a7267ffa";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/libm/0.2.15/download";
    sha256 = "f9fbbcab51052fe104eb5e5d351cf728d30a5be1fe14d9be8a3b097481fb97de";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/linux-raw-sys/0.4.15/download";
    sha256 = "d26c52dbd32dccf2d10cac7725f8eae5296885fb5703b261f7d0a0739ec807ab";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/linux-raw-sys/0.9.4/download";
    sha256 = "cd945864f07fe9f5371a27ad7b52a172b4b499999f1d97574c9fa68373937e12";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/log/0.4.27/download";
    sha256 = "13dc2df351e3202783a1fe0d44375f7295ffb4049267b0f3018346dc122a1d94";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/mach2/0.4.2/download";
    sha256 = "19b955cdeb2a02b9117f121ce63aa52d08ade45de53e48fe6a38b39c10f6f709";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/memchr/2.7.4/download";
    sha256 = "78ca9ab1a0babb1e7d5695e3530886289c18cf2f87ec19a575a0abdce112e3a3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/memfd/0.6.4/download";
    sha256 = "b2cffa4ad52c6f791f4f8b15f0c05f9824b2ced1160e88cc393d64fff9a8ac64";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/object/0.36.7/download";
    sha256 = "62948e14d923ea95ea2c7c86c71013138b66525b86bdc08d2dcc262bdb497b87";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/once_cell/1.21.3/download";
    sha256 = "42f5e15c9953c5e4ccceeb2e7382a716482c34515315f7b03532b8b4e8393d2d";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/pin-project-lite/0.2.16/download";
    sha256 = "3b3cff922bd51709b605d9ead9aa71031d81447142d828eb4a6eba76fe619f9b";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/pin-utils/0.1.0/download";
    sha256 = "8b870d8c151b6f2fb93e84a13146138f05d02ed11c7e7c54f8826aaaf7c9f184";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/postcard/1.1.1/download";
    sha256 = "170a2601f67cc9dba8edd8c4870b15f71a6a2dc196daec8c83f72b59dff628a8";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/proc-macro2/1.0.95/download";
    sha256 = "02b3e5e68a3a1a02aad3ec490a98007cbc13c37cbe84a3cd7b8e406d76e7f778";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/psm/0.1.26/download";
    sha256 = "6e944464ec8536cd1beb0bbfd96987eb5e3b72f2ecdafdc5c769a37f1fa2ae1f";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/pulley-interpreter/32.0.0/download";
    sha256 = "69c819888a64024f9c6bc7facbed99dfb4dd0124abe4335b6a54eabaa68ef506";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/quote/1.0.40/download";
    sha256 = "1885c039570dc00dcb4ff087a89e185fd56bae234ddc7f056a945bf36467248d";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/regalloc2/0.11.2/download";
    sha256 = "dc06e6b318142614e4a48bc725abbf08ff166694835c43c9dae5a9009704639a";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/rustc-hash/2.1.1/download";
    sha256 = "357703d41365b4b27c590e3ed91eabb1b663f07c4c084095e60cbed4362dff0d";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/rustix/0.38.44/download";
    sha256 = "fdb5bc1ae2baa591800df16c9ca78619bf65c0488b41b96ccec5d11220d8c154";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/rustix/1.0.7/download";
    sha256 = "c71e83d6afe7ff64890ec6b71d6a69bb8a610ab78ce364b3352876bb4c801266";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/ryu/1.0.20/download";
    sha256 = "28d3b2b1366ec20994f1fd18c3c594f05c5dd4bc44d8bb0c1c632c8d6829481f";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/semver/1.0.26/download";
    sha256 = "56e6fa9c48d24d85fb3de5ad847117517440f6beceb7798af16b4a87d616b8d0";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/serde/1.0.219/download";
    sha256 = "5f0e2c6ed6606019b4e29e69dbaba95b11854410e5347d525002456dbbb786b6";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/serde_derive/1.0.219/download";
    sha256 = "5b0276cf7f2c73365f7157c8123c21cd9a50fbbd844757af28ca1f5925fc2a00";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/serde_json/1.0.140/download";
    sha256 = "20068b6e96dc6c9bd23e01df8827e6c7e1f2fddd43c21810382803c136b99373";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/shlex/1.3.0/download";
    sha256 = "0fda2ff0d084019ba4d7c6f371c95d8fd75ce3524c3cb8fb653a3023f6323e64";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/smallvec/1.15.0/download";
    sha256 = "8917285742e9f3e1683f0a9c4e6b57960b7314d0b08d30d1ecd426713ee2eee9";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/sptr/0.3.2/download";
    sha256 = "3b9b39299b249ad65f3b7e96443bad61c02ca5cd3589f46cb6d610a0fd6c0d6a";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/stable_deref_trait/1.2.0/download";
    sha256 = "a8f112729512f8e442d81f95a8a7ddf2b7c6b8a1a6f509a95864142b30cab2d3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/syn/2.0.101/download";
    sha256 = "8ce2b7fc941b3a24138a0a7cf8e858bfc6a992e7978a068a5c760deb0ed43caf";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/target-lexicon/0.13.2/download";
    sha256 = "e502f78cdbb8ba4718f566c418c52bc729126ffd16baee5baa718cf25dd5a69a";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/termcolor/1.4.1/download";
    sha256 = "06794f8f6c5c898b3275aebefa6b8a1cb24cd2c6c79397ab15774837a0bc5755";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/thiserror-impl/2.0.12/download";
    sha256 = "7f7cf42b4507d8ea322120659672cf1b9dbb93f8f2d4ecfd6e51350ff5b17a1d";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/thiserror/2.0.12/download";
    sha256 = "567b8a2dae586314f7be2a752ec7474332959c6460e02bde30d702a66d488708";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/tracing-attributes/0.1.28/download";
    sha256 = "395ae124c09f9e6918a2310af6038fba074bcf474ac352496d5910dd59a2226d";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/tracing-core/0.1.33/download";
    sha256 = "e672c95779cf947c5311f83787af4fa8fffd12fb27e4993211a84bdfd9610f9c";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/tracing/0.1.41/download";
    sha256 = "784e0ac535deb450455cbfa28a6f0df145ea1bb7ae51b821cf5e7927fdcfbdd0";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/trait-variant/0.1.2/download";
    sha256 = "70977707304198400eb4835a78f6a9f928bf41bba420deb8fdb175cd965d77a7";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/unicode-ident/1.0.18/download";
    sha256 = "5a5f39404a5da50712a4c1eecf25e90dd62b613502b7e925fd4e4d19b5c96512";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/unicode-width/0.2.0/download";
    sha256 = "1fc81956842c57dac11422a97c3b8195a1ff727f06e85c84ed2e8aa277c9a0fd";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/unicode-xid/0.2.6/download";
    sha256 = "ebc1c04c71510c7f702b52b7c350734c9ff1295c464a03335b00bb84fc54f853";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasm-encoder/0.228.0/download";
    sha256 = "05d30290541f2d4242a162bbda76b8f2d8b1ac59eab3568ed6f2327d52c9b2c4";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasm-encoder/0.230.0/download";
    sha256 = "d4349d0943718e6e434b51b9639e876293093dca4b96384fb136ab5bd5ce6660";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmparser/0.228.0/download";
    sha256 = "4abf1132c1fdf747d56bbc1bb52152400c70f336870f968b85e89ea422198ae3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmparser/0.230.0/download";
    sha256 = "808198a69b5a0535583370a51d459baa14261dfab04800c4864ee9e1a14346ed";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmprinter/0.228.0/download";
    sha256 = "0df64bd38c14db359d02ce2024c64eb161aa2618ccee5f3bc5acbbd65c9a875c";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-asm-macros/32.0.0/download";
    sha256 = "194241137d4c1a30a3c2d713016d3de7e2c4e25c9a1a49ef23fc9b850d9e2068";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-c-api-impl/32.0.0/download";
    sha256 = "1a9c67a781fcfe4f9a8dbbfc0a562bf937e7826c6547c9f1c2cf62e5ebb08753";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-c-api-macros/32.0.0/download";
    sha256 = "d688c2f0a5fcb9236e9ef593f15170afb3edac2b5eb3af49773ba5f2e7a1a9d3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-component-macro/32.0.0/download";
    sha256 = "5758acd6dadf89f904c8de8171ae33499c7809c8f892197344df5055199aeab3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-component-util/32.0.0/download";
    sha256 = "3068c266bc21eb51e7b9a405550b193b8759b771d19aecc518ca838ea4782ef3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-cranelift/32.0.0/download";
    sha256 = "925c030360b8084e450f29d4d772e89ba0a8855dd0a47e07dd11e7f5fd900b42";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-environ/32.0.0/download";
    sha256 = "58d78b12eb1f2d2ac85eff89693963ba9c13dd9c90796d92d83ff27b23b29fbe";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-fiber/32.0.0/download";
    sha256 = "ced0efdb1553ada01704540d3cf3e525c93c8f5ca24a48d3e50ba5f2083c36ba";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-jit-icache-coherence/32.0.0/download";
    sha256 = "eb399eaabd7594f695e1159d236bf40ef55babcb3af97f97c027864ed2104db6";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-math/32.0.0/download";
    sha256 = "a527168840e87fc06422b44e7540b4e38df7c84237abdad3dc2450dcde8ab38e";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-slab/32.0.0/download";
    sha256 = "46a3a2798fb5472381cebd72c1daa1f99bbfd6fb645bf8285db8b3a48405daec";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-versioned-export-macros/32.0.0/download";
    sha256 = "b5afcdcb7f97cce62f6f512182259bfed5d2941253ad43780b3a4e1ad72e4fea";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-winch/32.0.0/download";
    sha256 = "0ac4f31e4657e385d53c71cf963868dc6efdff39fe657c873a0f5da8f465f164";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime-wit-bindgen/32.0.0/download";
    sha256 = "ada7e868e5925341cdae32729cf02a8f2523b8e998286213e6f4a5af7309cb75";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wasmtime/32.0.0/download";
    sha256 = "ab05ab5e27e0d76a9a7cd93d30baa600549945ff7dcae57559de9678e28f3b7e";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wast/230.0.0/download";
    sha256 = "b8edac03c5fa691551531533928443faf3dc61a44f814a235c7ec5d17b7b34f1";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wat/1.230.0/download";
    sha256 = "0d77d62229e38db83eac32bacb5f61ebb952366ab0dae90cf2b3c07a65eea894";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/winapi-util/0.1.9/download";
    sha256 = "cf221c93e13a30d793f7645a0e7762c55d169dbb0a49671918a2319d289b10bb";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/winch-codegen/32.0.0/download";
    sha256 = "108e1f810933ac36e7168313a0e5393c84a731f0394c3cb3e5f5667b378a03fc";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows-sys/0.59.0/download";
    sha256 = "1e38bc4d79ed67fd075bcc251a1c39b32a1776bbe92e5bef1f0bf1f8c531853b";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows-targets/0.52.6/download";
    sha256 = "9b724f72796e036ab90c1021d4780d4d3d648aca59e491e6b98e725b84e99973";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows_aarch64_gnullvm/0.52.6/download";
    sha256 = "32a4622180e7a0ec044bb555404c800bc9fd9ec262ec147edd5989ccd0c02cd3";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows_aarch64_msvc/0.52.6/download";
    sha256 = "09ec2a7bb152e2252b53fa7803150007879548bc709c039df7627cabbd05d469";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows_i686_gnu/0.52.6/download";
    sha256 = "8e9b5ad5ab802e97eb8e295ac6720e509ee4c243f69d781394014ebfe8bbfa0b";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows_i686_gnullvm/0.52.6/download";
    sha256 = "0eee52d38c090b3caa76c563b86c3a4bd71ef1a819287c19d586d7334ae8ed66";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows_i686_msvc/0.52.6/download";
    sha256 = "240948bc05c5e7c6dabba28bf89d89ffce3e303022809e73deaefe4f6ec56c66";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows_x86_64_gnu/0.52.6/download";
    sha256 = "147a5c80aabfbf0c7d901cb5895d1de30ef2907eb21fbbab29ca94c5b08b1a78";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows_x86_64_gnullvm/0.52.6/download";
    sha256 = "24d5b23dc417412679681396f2b49f3de8c1473deb516bd34410872eff51ed0d";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/windows_x86_64_msvc/0.52.6/download";
    sha256 = "589f6da84c646204747d1270a2a5661ea66ed1cced2631d546fdfb155959f9ec";
    name = "download";
  }
  {
    url = "https://static.crates.io/crates/wit-parser/0.228.0/download";
    sha256 = "399ce56e28d79fd3abfa03fdc7ceb89ffec4d4b2674fe3a92056b7d845653c38";
    name = "download";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/base64-v0.5.0.tar.gz";
    sha256 = "b21be58a90d31302ba86056db7ef77a481393b9359c505be5337d7d54e8a0559";
    name = "base64-v0.5.0.tar.gz";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/c-ares-1.34.6.tar.gz";
    sha256 = "912dd7cc3b3e8a79c52fd7fb9c0f4ecf0aaa73e45efda880266a2d6e26b84ef5";
    name = "c-ares-1.34.6.tar.gz";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/hwloc-2.11.2.tar.gz";
    sha256 = "866ac8ef07b350a6a2ba0c6826c37d78e8994dcbcd443bdd2b436350de19d540";
    name = "hwloc-2.11.2.tar.gz";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/libpciaccess-2ec2576cabefef1eaa5dd9307c97de2e887fc347.tar.gz";
    sha256 = "d0d0d53c2085d21ab37ae5989e55a3de13d4d80dc2c0a8d5c77154ea70f4783c";
    name = "libpciaccess-2ec2576cabefef1eaa5dd9307c97de2e887fc347.tar.gz";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/lksctp-tools-1.0.19.tar.gz";
    sha256 = "0c8fac0a5c66eea339dce6be857101b308ce1064c838b81125b0dde3901e8032";
    name = "lksctp-tools-1.0.19.tar.gz";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/omb/omb_minimal_3c624daad47f16ae7036b67142c384d3e59150bf.tar.gz";
    sha256 = "9d1f651d98a624dcfb09c213a8b77732bd08e037d32922b06c06e6027841e8ee";
    name = "omb_minimal_3c624daad47f16ae7036b67142c384d3e59150bf.tar.gz";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/openssl-3.1.2.tar.gz";
    sha256 = "a0ce69b8b97ea6a35b96875235aa453b966ba3cba8af2de23657d8b6767d6539";
    name = "openssl-3.1.2.tar.gz";
  }
  {
    url = "https://vectorized-public.s3.amazonaws.com/dependencies/openssl-3.5.5.tar.gz";
    sha256 = "b28c91532a8b65a1f983b4c28b7488174e4a01008e29ce8e69bd789f28bc2a89";
    name = "openssl-3.5.5.tar.gz";
  }
  {
    url = "https://vectorized-public.s3.us-west-2.amazonaws.com/dependencies/ada-3.2.4.single-header.zip";
    sha256 = "bd89fcf57c93e965e6e2488448ab9d1cf8005311808c563b288f921d987e4924";
    name = "ada-3.2.4.single-header.zip";
  }
  {
    url = "https://vectorized-public.s3.us-west-2.amazonaws.com/dependencies/libxml2-v2.15.2.tar.gz";
    sha256 = "2769234c4fe2fab9b0b043e891c2af0f1ae51c8d4b94799472981e676ed8009e";
    name = "libxml2-v2.15.2.tar.gz";
  }

  # Rust toolchain archives (not captured in lockfile extensions)
  { url = "https://static.rust-lang.org/dist/2025-04-03/cargo-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; sha256 = "c5c1590f7e9246ad9f4f97cfe26ffa92707b52a769726596a9ef81565ebd908b"; name = "cargo-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; }
  { url = "https://static.rust-lang.org/dist/2025-04-03/clippy-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; sha256 = "02aaff2c1407d2da8dba19aa4970dd873e311902b120a66cbcdbe51eb8836edf"; name = "clippy-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; }
  { url = "https://static.rust-lang.org/dist/2025-04-03/llvm-tools-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; sha256 = "282145ab7a63c98b625856f44b905b4dc726b497246b824632a5790debe95a78"; name = "llvm-tools-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; }
  { url = "https://static.rust-lang.org/dist/2025-04-03/rust-std-1.86.0-aarch64-unknown-linux-gnu.tar.xz"; sha256 = "176129577a5d560bbd94bcd2d24c0228bb495b73219df02556b4e4b4f0815bf7"; name = "rust-std-1.86.0-aarch64-unknown-linux-gnu.tar.xz"; }
  { url = "https://static.rust-lang.org/dist/2025-04-03/rust-std-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; sha256 = "67be7184ea388d8ce0feaf7fdea46f1775cfc2970930264343b3089898501d37"; name = "rust-std-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; }
  { url = "https://static.rust-lang.org/dist/2025-04-03/rustc-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; sha256 = "4438b809ce4a083af31ed17aeeedcc8fc60ccffc0625bef1926620751b6989d7"; name = "rustc-1.86.0-x86_64-unknown-linux-gnu.tar.xz"; }
  { url = "https://static.rust-lang.org/dist/2025-04-03/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz"; sha256 = "f8876b429b1ad9dfd5ece1e47947b39b20a0ecc56b1c76a614c4af5797152d86"; name = "rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz"; }
]
