load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "common",
    srcs = ["common.go"],
    importpath = "github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/debug/common",
    visibility = ["//visibility:public"],
    deps = ["@com_github_spf13_pflag//:pflag"],
)
