load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "metrics",
    srcs = ["metrics.go"],
    importpath = "github.com/redpanda-data/redpanda/tests/go/client-swarm/internal/metrics",
    visibility = ["//tests/go/client-swarm:__subpackages__"],
)
