FROM openjdk:14-jdk-buster

ENV DEBIAN_FRONTEND noninteractive \
    TZ="UTC"

RUN apt update && \
    apt install -y openssh-server && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

# Set up ssh
COPY ./ssh /root/.ssh

ARG KAFKA_MIRROR="https://s3-us-west-2.amazonaws.com/kafka-packages"

# single RUN to reduce num of layers:
#  * allow user env variables in ssh sessions
#  * add jdk bin dir to path
#  * install kafka
#  * create expected dirs
RUN echo 'PermitUserEnvironment yes' >> /etc/ssh/sshd_config && \
    bash -c "echo 'export PATH=$PATH:/usr/java/openjdk-14/bin/' > /etc/environment" && \
    mkdir /opt/kafka-dev && curl -s "$KAFKA_MIRROR/kafka_2.12-2.3.1.tgz" | tar xz --strip-components=1 -C /opt/kafka-dev && \
    mkdir /mnt/trogdor && \
    mkdir /etc/redpanda /var/lib/redpanda

# install redpanda
ADD redpanda.tar.gz /usr/local/

CMD service ssh start && tail -f /dev/null
