FROM python:2.7

ENV TZ="UTC"

# install kafkatests and ducktape
RUN pip install --no-cache-dir 'git+https://github.com/apache/kafka#egg=kafkatest&subdirectory=tests'

# install v tests
COPY . /root/tests/
RUN pip list && pip install --no-cache-dir -e /root/tests/ && \
    mv /root/tests/docker/ssh /root/.ssh

ENTRYPOINT ["ducktape"]
