load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "provider",
    srcs = ["provider.go"],
    importpath = "github.com/redpanda-data/redpanda/src/go/rpk/pkg/cloud/provider",
    visibility = ["//visibility:public"],
)
