"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.descriptor_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class FieldInfo(google.protobuf.message.Message):
    """Rich semantic information of an API field beyond basic typing."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Format:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[FieldInfo._Format.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FORMAT_UNSPECIFIED: FieldInfo._Format.ValueType
        'Default, unspecified value.'
        UUID4: FieldInfo._Format.ValueType
        'Universally Unique Identifier, version 4, value as defined by\n        https://datatracker.ietf.org/doc/html/rfc4122. The value may be\n        normalized to entirely lowercase letters. For example, the value\n        `F47AC10B-58CC-0372-8567-0E02B2C3D479` would be normalized to\n        `f47ac10b-58cc-0372-8567-0e02b2c3d479`.\n        '
        IPV4: FieldInfo._Format.ValueType
        'Internet Protocol v4 value as defined by [RFC\n        791](https://datatracker.ietf.org/doc/html/rfc791). The value may be\n        condensed, with leading zeros in each octet stripped. For example,\n        `001.022.233.040` would be condensed to `1.22.233.40`.\n        '
        IPV6: FieldInfo._Format.ValueType
        'Internet Protocol v6 value as defined by [RFC\n        2460](https://datatracker.ietf.org/doc/html/rfc2460). The value may be\n        normalized to entirely lowercase letters with zeros compressed, following\n        [RFC 5952](https://datatracker.ietf.org/doc/html/rfc5952). For example,\n        the value `2001:0DB8:0::0` would be normalized to `2001:db8::`.\n        '
        IPV4_OR_IPV6: FieldInfo._Format.ValueType
        'An IP address in either v4 or v6 format as described by the individual\n        values defined herein. See the comments on the IPV4 and IPV6 types for\n        allowed normalizations of each.\n        '

    class Format(_Format, metaclass=_FormatEnumTypeWrapper):
        """The standard format of a field value. The supported formats are all backed
        by either an RFC defined by the IETF or a Google-defined AIP.
        """
    FORMAT_UNSPECIFIED: FieldInfo.Format.ValueType
    'Default, unspecified value.'
    UUID4: FieldInfo.Format.ValueType
    'Universally Unique Identifier, version 4, value as defined by\n    https://datatracker.ietf.org/doc/html/rfc4122. The value may be\n    normalized to entirely lowercase letters. For example, the value\n    `F47AC10B-58CC-0372-8567-0E02B2C3D479` would be normalized to\n    `f47ac10b-58cc-0372-8567-0e02b2c3d479`.\n    '
    IPV4: FieldInfo.Format.ValueType
    'Internet Protocol v4 value as defined by [RFC\n    791](https://datatracker.ietf.org/doc/html/rfc791). The value may be\n    condensed, with leading zeros in each octet stripped. For example,\n    `001.022.233.040` would be condensed to `1.22.233.40`.\n    '
    IPV6: FieldInfo.Format.ValueType
    'Internet Protocol v6 value as defined by [RFC\n    2460](https://datatracker.ietf.org/doc/html/rfc2460). The value may be\n    normalized to entirely lowercase letters with zeros compressed, following\n    [RFC 5952](https://datatracker.ietf.org/doc/html/rfc5952). For example,\n    the value `2001:0DB8:0::0` would be normalized to `2001:db8::`.\n    '
    IPV4_OR_IPV6: FieldInfo.Format.ValueType
    'An IP address in either v4 or v6 format as described by the individual\n    values defined herein. See the comments on the IPV4 and IPV6 types for\n    allowed normalizations of each.\n    '
    FORMAT_FIELD_NUMBER: builtins.int
    REFERENCED_TYPES_FIELD_NUMBER: builtins.int
    format: Global___FieldInfo.Format.ValueType
    "The standard format of a field value. This does not explicitly configure\n    any API consumer, just documents the API's format for the field it is\n    applied to.\n    "

    @property
    def referenced_types(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TypeReference]:
        """The type(s) that the annotated, generic field may represent.

        Currently, this must only be used on fields of type `google.protobuf.Any`.
        Supporting other generic types may be considered in the future.
        """

    def __init__(self, *, format: Global___FieldInfo.Format.ValueType=..., referenced_types: collections.abc.Iterable[Global___TypeReference] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['format', b'format', 'referenced_types', b'referenced_types']) -> None:
        ...
Global___FieldInfo: typing_extensions.TypeAlias = FieldInfo

@typing.final
class TypeReference(google.protobuf.message.Message):
    """A reference to a message type, for use in [FieldInfo][google.api.FieldInfo]."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_NAME_FIELD_NUMBER: builtins.int
    type_name: builtins.str
    'The name of the type that the annotated, generic field may represent.\n    If the type is in the same protobuf package, the value can be the simple\n    message name e.g., `"MyMessage"`. Otherwise, the value must be the\n    fully-qualified message name e.g., `"google.library.v1.Book"`.\n\n    If the type(s) are unknown to the service (e.g. the field accepts generic\n    user input), use the wildcard `"*"` to denote this behavior.\n\n    See [AIP-202](https://google.aip.dev/202#type-references) for more details.\n    '

    def __init__(self, *, type_name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['type_name', b'type_name']) -> None:
        ...
Global___TypeReference: typing_extensions.TypeAlias = TypeReference
FIELD_INFO_FIELD_NUMBER: builtins.int
field_info: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[google.protobuf.descriptor_pb2.FieldOptions, Global___FieldInfo]
'Rich semantic descriptor of an API field beyond the basic typing.\n\nExamples:\n\n    string request_id = 1 [(google.api.field_info).format = UUID4];\n    string old_ip_address = 2 [(google.api.field_info).format = IPV4];\n    string new_ip_address = 3 [(google.api.field_info).format = IPV6];\n    string actual_ip_address = 4 [\n      (google.api.field_info).format = IPV4_OR_IPV6\n    ];\n    google.protobuf.Any generic_field = 5 [\n      (google.api.field_info).referenced_types = {type_name: "ActualType"},\n      (google.api.field_info).referenced_types = {type_name: "OtherType"},\n    ];\n    google.protobuf.Any generic_user_input = 5 [\n      (google.api.field_info).referenced_types = {type_name: "*"},\n    ];\n'