"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ControllerForcedReconfigurationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEAD_NODE_IDS_FIELD_NUMBER: builtins.int
    SURVIVING_NODE_COUNT_FIELD_NUMBER: builtins.int
    surviving_node_count: builtins.int
    'the number of surviving nodes remaining.'

    @property
    def dead_node_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """node ids of lost brokers to be forcibly removed."""

    def __init__(self, *, dead_node_ids: collections.abc.Iterable[builtins.int] | None=..., surviving_node_count: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['dead_node_ids', b'dead_node_ids', 'surviving_node_count', b'surviving_node_count']) -> None:
        ...
Global___ControllerForcedReconfigurationRequest: typing_extensions.TypeAlias = ControllerForcedReconfigurationRequest

@typing.final
class ControllerForcedReconfigurationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___ControllerForcedReconfigurationResponse: typing_extensions.TypeAlias = ControllerForcedReconfigurationResponse