"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LogLevel:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LogLevelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LogLevel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOG_LEVEL_UNSPECIFIED: _LogLevel.ValueType
    LOG_LEVEL_TRACE: _LogLevel.ValueType
    LOG_LEVEL_DEBUG: _LogLevel.ValueType
    LOG_LEVEL_INFO: _LogLevel.ValueType
    LOG_LEVEL_WARN: _LogLevel.ValueType
    LOG_LEVEL_ERROR: _LogLevel.ValueType

class LogLevel(_LogLevel, metaclass=_LogLevelEnumTypeWrapper):
    ...
LOG_LEVEL_UNSPECIFIED: LogLevel.ValueType
LOG_LEVEL_TRACE: LogLevel.ValueType
LOG_LEVEL_DEBUG: LogLevel.ValueType
LOG_LEVEL_INFO: LogLevel.ValueType
LOG_LEVEL_WARN: LogLevel.ValueType
LOG_LEVEL_ERROR: LogLevel.ValueType
Global___LogLevel: typing_extensions.TypeAlias = LogLevel

@typing.final
class StartStressFiberRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MIN_SPINS_PER_SCHEDULING_POINT_FIELD_NUMBER: builtins.int
    MAX_SPINS_PER_SCHEDULING_POINT_FIELD_NUMBER: builtins.int
    STACK_DEPTH_FIELD_NUMBER: builtins.int
    MIN_MS_PER_SCHEDULING_POINT_FIELD_NUMBER: builtins.int
    MAX_MS_PER_SCHEDULING_POINT_FIELD_NUMBER: builtins.int
    FIBER_COUNT_FIELD_NUMBER: builtins.int
    min_spins_per_scheduling_point: builtins.int
    max_spins_per_scheduling_point: builtins.int
    stack_depth: builtins.int
    min_ms_per_scheduling_point: builtins.int
    max_ms_per_scheduling_point: builtins.int
    fiber_count: builtins.int

    def __init__(self, *, min_spins_per_scheduling_point: builtins.int=..., max_spins_per_scheduling_point: builtins.int=..., stack_depth: builtins.int=..., min_ms_per_scheduling_point: builtins.int=..., max_ms_per_scheduling_point: builtins.int=..., fiber_count: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['fiber_count', b'fiber_count', 'max_ms_per_scheduling_point', b'max_ms_per_scheduling_point', 'max_spins_per_scheduling_point', b'max_spins_per_scheduling_point', 'min_ms_per_scheduling_point', b'min_ms_per_scheduling_point', 'min_spins_per_scheduling_point', b'min_spins_per_scheduling_point', 'stack_depth', b'stack_depth']) -> None:
        ...
Global___StartStressFiberRequest: typing_extensions.TypeAlias = StartStressFiberRequest

@typing.final
class StartStressFiberResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StartStressFiberResponse: typing_extensions.TypeAlias = StartStressFiberResponse

@typing.final
class StopStressFiberRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StopStressFiberRequest: typing_extensions.TypeAlias = StopStressFiberRequest

@typing.final
class StopStressFiberResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StopStressFiberResponse: typing_extensions.TypeAlias = StopStressFiberResponse

@typing.final
class ThrowStructuredExceptionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str

        def __init__(self, *, key: builtins.str=..., value: builtins.str=...) -> None:
            ...

        def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
            ...
    NODE_ID_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    reason: builtins.str

    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        ...

    def __init__(self, *, node_id: builtins.int=..., reason: builtins.str=..., metadata: collections.abc.Mapping[builtins.str, builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['metadata', b'metadata', 'node_id', b'node_id', 'reason', b'reason']) -> None:
        ...
Global___ThrowStructuredExceptionRequest: typing_extensions.TypeAlias = ThrowStructuredExceptionRequest

@typing.final
class ThrowStructuredExceptionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___ThrowStructuredExceptionResponse: typing_extensions.TypeAlias = ThrowStructuredExceptionResponse

@typing.final
class LogMessageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MESSAGE_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    message: builtins.str
    level: Global___LogLevel.ValueType

    def __init__(self, *, message: builtins.str=..., level: Global___LogLevel.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['level', b'level', 'message', b'message']) -> None:
        ...
Global___LogMessageRequest: typing_extensions.TypeAlias = LogMessageRequest

@typing.final
class LogMessageResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___LogMessageResponse: typing_extensions.TypeAlias = LogMessageResponse