---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /src/go/k8s/
    schedule:
      interval: daily
    groups:
      kubernetes:
        patterns:
          - "k8s.io/*"
        exclude-patterns:
          - "k8s.io/utils"
    labels:
      - dependencies
      - area/k8s
      - k8s/tests
