{
 "title": "Scale test control",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Shard util",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(redpanda_cpu_busy_seconds_total{}[30s])) by (instance, shard)",
     "legendFormat": "{{instance}} {{shard}}"
    }
   ]
  },
  {
   "title": "kafka produce received bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(vectorized_kafka_handler_received_bytes_total{handler=\"produce\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka produce requests completed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(vectorized_kafka_handler_requests_completed_total{handler=\"produce\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mean batch size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(sum(irate(vectorized_storage_log_written_bytes{}[$__rate_interval])) by (instance)) / (sum(irate(vectorized_storage_log_batches_written{}[$__rate_interval])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka produce requests in progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(vectorized_kafka_handler_requests_in_progress_total{handler=\"produce\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "recovery requests sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(vectorized_raft_recovery_requests{}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leader balancer transfers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(irate(vectorized_leader_balancer_leader_transfer_succeeded{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka metadata requests completed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(vectorized_kafka_handler_requests_completed_total{handler=\"metadata\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leadership changes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(irate(vectorized_raft_leadership_changes{instance=~\".*\",shard=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Reactor metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "reactor util",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(vectorized_reactor_utilization{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "io queue length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum(vectorized_io_queue_queue_length{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internal RPC metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Raft-level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true
  },
  {
   "title": "leader step downs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(irate(vectorized_raft_step_downs{instance=~\".*\",shard=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leaderless partition replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(vectorized_cluster_partition_leaderless{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "internal rpc pending requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(vectorized_internal_rpc_requests_pending{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "underreplicated partition replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum(vectorized_cluster_partition_under_replicated_replicas{instance=~\".*\",shard=~\".*\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "internal rpc latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(vectorized_internal_rpc_latency_bucket{instance=~\".*\",shard=~\".*\"}[$__rate_interval])) by (le, instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "internal rpc recv bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(vectorized_internal_rpc_received_bytes{}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}