FROM debian:bullseye AS builder

RUN apt update && apt install -y \
    git \
    python3 \
    jq \
    curl \
    wget \
    gnupg \
    software-properties-common \
    lsb-release

# Install latest versions using backports
RUN echo "deb http://archive.debian.org/debian bullseye-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update && \
    apt-get install -y -t bullseye-backports \
      cmake \
      gcc \
      g++ \
      build-essential \
      binutils-dev \
      automake \
      ninja-build \
      zlib1g-dev \
      pkg-config

ARG STAGE_0_LLVM_VERSION=20

RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && /llvm.sh ${STAGE_0_LLVM_VERSION} all

# Set working directory
WORKDIR /src

ARG LLVM_VERSION=20

# Clone LLVM project (includes Clang, clang-tidy, clangd, and BOLT)
# We use the latest version of the release branch to pick up fixes quicker rather than waiting for a full
# release to happen
RUN git clone --depth 1 --branch release/${LLVM_VERSION}.x https://github.com/llvm/llvm-project.git

# LTO builds take a bunch of RAM, limit them to a low number by default
ARG MAX_LINK_JOBS=4

COPY <<EOF /llvm.cmake
set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD Native CACHE STRING "")
set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "")
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "")
set(LLVM_INCLUDE_UTILS OFF CACHE BOOL "")
set(LLVM_INCLUDE_DOCS OFF CACHE BOOL "")
set(LLVM_INCLUDE_GO_TESTS OFF CACHE BOOL "")
set(LLVM_ENABLE_ZLIB ON CACHE BOOL "")
set(LLVM_ENABLE_LIBXML2 OFF CACHE BOOL "")
set(LLVM_ENABLE_BACKTRACES OFF CACHE BOOL "")
set(LLVM_ENABLE_PROJECTS clang bolt lld lldb clang-tools-extra CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES libcxx libcxxabi compiler-rt CACHE STRING "")
set(LLVM_USE_LINKER lld CACHE STRING "")
set(LLVM_BUILD_TOOLS ON CACHE BOOL "")
set(LLVM_BINUTILS_INCDIR ON CACHE BOOL "")
set(CLANG_INCLUDE_TESTS OFF CACHE BOOL "")
set(CLANG_PLUGIN_SUPPORT OFF CACHE BOOL "")
set(COMPILER_RT_INCLUDE_TESTS OFF CACHE BOOL "")
set(COMPILER_RT_BUILD_SANITIZERS ON CACHE BOOL "")
set(COMPILER_RT_ENABLE_IOS OFF CACHE BOOL "")
set(COMPILER_RT_ENABLE_WATCHOS OFF CACHE BOOL "")
set(COMPILER_RT_ENABLE_TVOS OFF CACHE BOOL "")
set(LIBCXX_INSTALL_EXPERIMENTAL_LIBRARY ON CACHE STRING "")
set(LIBCXX_CXX_ABI libcxxabi CACHE STRING "")
# in clang-18 this appears to be on by default, but we don't use libunwind
set(LIBCXXABI_USE_LLVM_UNWINDER OFF CACHE BOOL "")
set(LLVM_INSTALL_TOOLCHAIN_ONLY ON CACHE BOOL "")
set(LLVM_ENABLE_LTO Thin CACHE STRING "")
set(LLVM_PARALLEL_LINK_JOBS ${MAX_LINK_JOBS} CACHE STRING "")
EOF

# Create build directory
WORKDIR /src/build

RUN cmake -G Ninja \
    -C /llvm.cmake \
    -DCMAKE_INSTALL_PREFIX=/opt/install \
    -DCMAKE_C_COMPILER=/usr/bin/clang-${STAGE_0_LLVM_VERSION} \
    -DCMAKE_ASM_COMPILER=/usr/bin/clang-${STAGE_0_LLVM_VERSION} \
    -DCMAKE_CXX_COMPILER=/usr/bin/clang++-${STAGE_0_LLVM_VERSION} \
    -DCMAKE_AR=/usr/bin/llvm-ar-${STAGE_0_LLVM_VERSION} \
    -DCMAKE_LINKER=/usr/bin/llvm-ld-${STAGE_0_LLVM_VERSION} \
    -DCMAKE_NM=/usr/bin/llvm-nm-${STAGE_0_LLVM_VERSION} \
    -DCMAKE_OBJDUMP=/usr/bin/llvm-objdump-${STAGE_0_LLVM_VERSION} \
    -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-${STAGE_0_LLVM_VERSION} \
    ../llvm-project/llvm

RUN ninja -j$(nproc) && ninja install

FROM scratch

COPY --from=builder /opt/install/ .
