#!/bin/bash
#
# Setup script for macOS cross-compilation toolchain
#
# This script helps set up LLVM for cross-compiling Redpanda from macOS to Linux.
# It provides multiple options for obtaining LLVM toolchains.
#

set -euo pipefail

LLVM_VERSION="${LLVM_VERSION:-20}"

echo "==================================="
echo "macOS Toolchain Setup for Redpanda"
echo "==================================="
echo ""

# Detect architecture
ARCH=$(uname -m)
if [ "$ARCH" = "arm64" ]; then
    BREW_PREFIX="/opt/homebrew"
else
    BREW_PREFIX="/usr/local"
fi

echo "Detected architecture: $ARCH"
echo "Homebrew prefix: $BREW_PREFIX"
echo ""

# Check if Homebrew is installed
if ! command -v brew &> /dev/null; then
    echo "❌ Homebrew is not installed."
    echo ""
    echo "Install Homebrew:"
    echo '  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
    echo ""
    exit 1
fi

echo "✅ Homebrew is installed"
echo ""

# Check for LLVM
LLVM_PATH="${BREW_PREFIX}/opt/llvm@${LLVM_VERSION}"

if [ -d "$LLVM_PATH" ]; then
    echo "✅ LLVM ${LLVM_VERSION} is already installed at: $LLVM_PATH"
    echo ""

    # Verify it has the necessary tools
    if [ -f "${LLVM_PATH}/bin/clang" ] && [ -f "${LLVM_PATH}/bin/clang++" ]; then
        echo "✅ Clang found:"
        "${LLVM_PATH}/bin/clang" --version | head -n 1
        echo ""
    else
        echo "⚠️  LLVM installation appears incomplete. Reinstalling..."
        brew reinstall "llvm@${LLVM_VERSION}"
    fi
else
    echo "📦 Installing LLVM ${LLVM_VERSION} from Homebrew..."
    echo "   This may take a few minutes..."
    echo ""

    brew install "llvm@${LLVM_VERSION}"

    if [ $? -eq 0 ]; then
        echo ""
        echo "✅ LLVM ${LLVM_VERSION} installed successfully"
    else
        echo ""
        echo "❌ Failed to install LLVM ${LLVM_VERSION}"
        exit 1
    fi
fi

# Create user.bazelrc with local toolchain configuration
USER_BAZELRC="user.bazelrc"

if [ ! -f "$USER_BAZELRC" ]; then
    echo "📝 Creating $USER_BAZELRC with Homebrew LLVM configuration..."
    cat > "$USER_BAZELRC" << EOF
# Generated by setup-macos-toolchain.sh
# This file is git-ignored and contains local machine configuration

# Use Homebrew LLVM for macOS cross-compilation
build:macos-local --action_env=CC=${LLVM_PATH}/bin/clang
build:macos-local --action_env=CXX=${LLVM_PATH}/bin/clang++
build:macos-local --action_env=PATH=${LLVM_PATH}/bin:\$PATH

# Combine with cross-compilation configs
build:macos-linux-local --config=macos-local
build:macos-linux-local --config=macos-linux

build:macos-linux-arm64-local --config=macos-local
build:macos-linux-arm64-local --config=macos-linux-arm64
EOF
    echo "✅ Created $USER_BAZELRC"
else
    echo "⚠️  $USER_BAZELRC already exists. Not overwriting."
    echo "   Add the following to use Homebrew LLVM:"
    echo ""
    echo "build:macos-local --action_env=CC=${LLVM_PATH}/bin/clang"
    echo "build:macos-local --action_env=CXX=${LLVM_PATH}/bin/clang++"
fi

echo ""
echo "==================================="
echo "✅ Setup Complete!"
echo "==================================="
echo ""
echo "You can now build Redpanda for Linux from macOS:"
echo ""
echo "  # Build Linux x86_64 binary"
echo "  bazel build --config=macos-linux-local //:redpanda"
echo ""
echo "  # Build Linux ARM64 binary"
echo "  bazel build --config=macos-linux-arm64-local //:redpanda"
echo ""
echo "  # Build release binary"
echo "  bazel build --config=macos-release --config=macos-local //:redpanda"
echo ""
echo "For more information, see: docs/BUILDING_ON_MACOS.md"
echo ""
