from setuptools import find_packages, setup

setup(
    name="rptest",
    version="0",
    provides=["rptest"],
    author="Redpanda Data",
    author_email="hi@redpanda.com",
    description="redpanda internal testing",
    packages=find_packages(),
    setup_requires=["setuptools"],
    package_data={"": ["*.md"]},
    include_package_data=True,
    install_requires=[
        "ducktape@git+https://github.com/redpanda-data/ducktape.git@c642f195d06d387348034c30f917b1a15c5d43a0",
        "prometheus-client==0.9.0",
        "kafka-python==2.0.6",
        "crc32c==2.2",
        "confluent-kafka==2.6.1",
        "zstandard==0.23.0",
        "xxhash==3.5.0",
        "protobuf==5.29.0",
        "fastavro==1.11.1",
        "falcon==4.0.2",
        "psutil==5.9.0",
        "numpy==1.26.4",
        "pygal==3.0",
        "pytest==7.1.2",
        "jump-consistent-hash==3.2.0",
        "azure-storage-blob==12.14.1",
        "kafkatest@git+https://github.com/apache/kafka.git@b3939f7901470048a70ee7cbaaa587f32cfac50e#egg=kafkatest&subdirectory=tests",
        "grpcio==1.71.0",
        "grpcio-tools==1.71",
        "grpcio-status==1.71.0",
        "google-api-core==2.24.2",
        "google-auth==2.40.2",
        "googleapis-common-protos==1.70.0",
        "google.cloud.compute==1.30.0",
        "google-cloud-storage==3.1.0",
        "proto-plus==1.26.1",
        "rsa==4.9",
        "python-keycloak==3.12.0",
        "z3-solver==4.12.2",
        "hypothesis==6.82",
        "jsonschema==4.10.0",
        "redpanda-polaris-catalog-python==1.0.0.post3",  # See: .github/workflows/publish-apache-polaris-python-client.yml
        # PyIceberg: Use an official release once the next major (1.0) is out.
        #   Using a hash to unreleased version because we depend on new
        #   pluggable authentication mechanism.
        # "pyiceberg==0.9.1",
        "pyiceberg@git+https://github.com/apache/iceberg-python@76a6451cd6863fe3d0e10d33da9b78af12e50111",
        "adlfs==2024.7.0",
        "pyarrow",
        "pandas",
        "pyparsing>=3.1.0",
        "thrift==0.20.0",
        "thrift-sasl==0.4.3",
        "pyhive==0.7.0",
        "python-snappy==0.7.3",
        "lz4==4.4.3",
        "databricks-sdk==0.49.0",
        "databricks-sql-connector==4.0.2",
        "duckdb==1.3.1",
        "connect-python==0.4.2",
        "avro==1.12.0",
    ],
    scripts=[],
)
