#!/usr/bin/env bash
set -e

# Pulls down the addr2line python code for use in DT tests. This doesn't necessarily
# need to point into our fork, in the case we need upstream improvements we haven't
# downstreamed yet.

SEASTAR_REPO=redpanda-data/seastar
SEASTAR_HASH=a6ac2ff6190a4a9dce5059991355703e1073d11f

mkdir -p /opt/scripts
for filename in addr2line.py seastar-addr2line; do
  curl https://raw.githubusercontent.com/$SEASTAR_REPO/$SEASTAR_HASH/scripts/$filename -o /opt/scripts/$filename
done

chmod +x /opt/scripts/seastar-addr2line
