#!/usr/bin/env bash
set -e
set -x

pushd /tmp
git clone https://github.com/redpanda-data/client-swarm.git

pushd client-swarm
git reset --hard 7a2d3837ac926047098232b7ec87afb32a319690
cargo build --config 'term.verbose=true' --config 'net.retry=6' --release
cp target/release/client-swarm /usr/local/bin
popd

rm -rf client-swarm
popd
