#!/usr/bin/env bash
set -e
set -x

pushd /tmp
git clone https://github.com/redpanda-data/client-swarm.git

pushd client-swarm
git reset --hard 9f343b16a88a263e21a701b7e1ca5488f5507b1b
cargo build --config 'term.verbose=true' --config 'net.retry=6' --release
cp target/release/client-swarm /usr/local/bin
popd

rm -rf client-swarm
popd
