#!/usr/bin/env bash
set -e

cd /opt/iceberg-rest-catalog
ARCH=$(dpkg-architecture -q DEB_BUILD_ARCH)
chmod +x ./gradlew
JAVA_HOME="/usr/lib/jvm/java-17-openjdk-${ARCH}" ./gradlew --no-daemon --info shadowJar
