#!/usr/bin/env bash
set -e
apt update
apt install -y \
  build-essential \
  openjdk-17-jdk \
  openjdk-21-jdk \
  git \
  maven \
  cmake \
  curl

SCRIPTPATH="$(
  cd -- "$(dirname "$0")" >/dev/null 2>&1
  pwd -P
)"
$SCRIPTPATH/protobuf

update-java-alternatives -s java-1.17.0-openjdk-amd64
mkdir /opt/java

cat <<EOF >/opt/java/java-21
JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"
/usr/lib/jvm/java-21-openjdk-amd64/bin/java "\$@"
EOF
chmod +x /opt/java/java-21

cat <<EOF >/opt/java/java-17
JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
/usr/lib/jvm/java-17-openjdk-amd64/bin/java "\$@"
EOF
chmod +x /opt/java/java-17
