#!/usr/bin/env bash
set -e
apt update
apt install -y \
  build-essential \
  openjdk-17-jdk \
  git \
  maven \
  cmake \
  curl

SCRIPTPATH="$(
  cd -- "$(dirname "$0")" >/dev/null 2>&1
  pwd -P
)"
$SCRIPTPATH/protobuf
