#!/usr/bin/env bash
set -e

source "$(dirname "${BASH_SOURCE[0]}")/download-utils" # import download-utils

for ver in "2.3.1" "2.4.1" "2.5.0" "2.7.0" "3.0.0" "3.7.0" "3.8.0" "3.9.0" "4.0.0"; do
  odir=/opt/kafka-${ver}
  mkdir -p "$odir"
  chmod a+rw "$odir"
  if [ "$ver" = "4.0.0" ]; then
    archive_name="kafka_2.13-${ver}.tgz"
  else
    archive_name="kafka_2.12-${ver}.tgz"
  fi
  DL_STRIP=1 download_extract "https://vectorized-public.s3.us-west-2.amazonaws.com/dependencies/${archive_name}" "$odir"
done
ln -s /opt/kafka-4.0.0/ /opt/kafka-dev

set -e
git -C /opt clone --depth 1 --branch 0.14.0-example-producer-args https://github.com/redpanda-data/strimzi-kafka-oauth.git

cd /opt/strimzi-kafka-oauth
mvn -DskipTests=true clean package

cd /opt/strimzi-kafka-oauth/examples/producer
mvn -DskipTests=true clean package

cd /opt/strimzi-kafka-oauth
cp oauth-common/target/kafka-oauth-common-*.jar /opt/kafka-dev/libs
cp oauth-client/target/kafka-oauth-client-*.jar /opt/kafka-dev/libs
cp oauth-common/target/lib/nimbus-jose-jwt-*.jar /opt/kafka-dev/libs
