#!/usr/bin/env bash
set -e

OCSF_SCHEMA_VERSION=1.0.0
OCSF_SERVER_VERSION=d3b26de39df9eb33c6d63e34a126c77c0811c7a0

wget "https://github.com/redpanda-data/ocsf-schema/archive/refs/tags/v${OCSF_SCHEMA_VERSION}.tar.gz"
wget "https://github.com/redpanda-data/ocsf-server/archive/${OCSF_SERVER_VERSION}.tar.gz"

tar -xvzf v${OCSF_SCHEMA_VERSION}.tar.gz
rm v${OCSF_SCHEMA_VERSION}.tar.gz
mv ocsf-schema-${OCSF_SCHEMA_VERSION} /opt/ocsf-schema

tar -xvzf ${OCSF_SERVER_VERSION}.tar.gz
rm ${OCSF_SERVER_VERSION}.tar.gz
mv ocsf-server-${OCSF_SERVER_VERSION} /opt/ocsf-server

apt-get update
apt-get install -qq software-properties-common

add-apt-repository -y ppa:rabbitmq/rabbitmq-erlang
apt-get update
apt-get install -qq elixir erlang-dev erlang-xmerl

mix local.hex --force && mix local.rebar --force

pushd /opt/ocsf-server
./build_server.sh
openssl req -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout server.key -out server.crt -subj "/O=Redpanda" -batch
popd
