#!/usr/bin/env bash
set -e
git -C /opt clone https://github.com/redpanda-data/openmessaging-benchmark.git
cd /opt/openmessaging-benchmark
git reset --hard 9cff468d5124cc9eb6cfce90798c2c9a5c354f6c
mvn clean package -DskipTests
