#!/usr/bin/env bash
set -e
git -C /opt clone https://github.com/redpanda-data/openmessaging-benchmark.git
cd /opt/openmessaging-benchmark
git reset --hard 2674d62ca2b6fd7f22536e924c0df8a8fa21350d
mvn clean package -DskipTests
