#!/usr/bin/env bash
set -e
update-java-alternatives -s java-1.21.0-openjdk-amd64
git -C /opt clone https://github.com/apache/polaris.git
cd /opt/polaris
git reset --hard 1a6b3eb3963355f78c5ca916cc1d66ecd1493092
./gradlew --no-daemon --info shadowJar
update-java-alternatives -s java-1.17.0-openjdk-amd64
