#!/bin/sh
set -e
set -x

mkdir -p /opt/transforms/tinygo/

cd /transform-sdk/go/transform/internal/testdata

tinygo build -target wasi -opt=z \
  -panic print -scheduler none \
  -o "/opt/transforms/tinygo/identity.wasm" ./identity
