#!/usr/bin/env bash
set -e
mkdir -p /usr/local/tinygo/
if [ $(uname -m) = "aarch64" ]; then
  export ARCHID="arm64"
else
  export ARCHID="amd64"
fi
curl -sSLf --retry 5 --retry-all-errors --retry-delay 2 "https://github.com/redpanda-data/tinygo/releases/download/v0.31.0-rpk2/tinygo-linux-${ARCHID}.tar.gz" -o /tmp/tinygo-linux.tar.gz
cat /tmp/tinygo-linux.tar.gz | tar -xz -C /usr/local/tinygo/ --strip 1
rm /tmp/tinygo-linux.tar.gz
