#!/usr/bin/env bash
set -e
apt-get update
apt-get install -qq \
  bind9-utils \
  bind9-dnsutils \
  bsdmainutils \
  dmidecode \
  iproute2 \
  iptables \
  libatomic1 \
  libyajl-dev \
  libsasl2-dev \
  libsasl2-modules-gssapi-mit \
  libssl-dev \
  net-tools \
  lsof \
  pciutils \
  nodejs \
  npm \
  openssh-server \
  netcat-openbsd \
  sudo \
  llvm \
  python3-pip
