#!/usr/bin/env bash

# "tool packages" are generally those which are needed for running ducktape
# tests, but not for building the early layers of the image themselves. They
# are installed relatively late in the Dockerfile, after most of the heavy
# "non mainline" layers have forked off.
set -euo pipefail

apt-get update
apt-get install -qq \
  bind9-dnsutils \
  bind9-utils \
  bsdmainutils \
  dmidecode \
  faketime \
  file \
  gnuplot-nox \
  iproute2 \
  iptables \
  krb5-admin-server \
  krb5-kdc \
  krb5-user \
  libatomic1 \
  libyajl-dev \
  lsof \
  net-tools \
  netcat-openbsd \
  nodejs \
  npm \
  openssh-server \
  pciutils \
  software-properties-common \
  sudo

# install llvm-addr2line-$(version), which is not available in the default ubuntu/debian repos,
# but is needed to demangle seastar backtraces (much faster than binutils addr2line)

LLVM_VERSION=20

cd "$(mktemp -d)"
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
./llvm.sh $LLVM_VERSION
mkdir -p /opt/llvm
# make it available in a version-independent way
ln -s /usr/bin/llvm-addr2line-$LLVM_VERSION /opt/llvm/llvm-addr2line

# Install an llvm-symbolizer shim in the PATH, this allows ASAN, UBSAN, etc
# symbolization to work out of the box.
cat <<EOF >/usr/local/bin/llvm-symbolizer
#!/bin/bash

# This shim unsets LD_LIBRARY_PATH to avoid the issue that
# redpanda libraries are loaded into the symbolizer, causing
# it to crash.
echo "exec llvm-symbolizer shim, cmd: '\$*', ASAN_OPTIONS=\$ASAN_OPTIONS, UBSAN_OPTIONS=\$UBSAN_OPTIONS" >&2
unset LD_LIBRARY_PATH
exec /usr/bin/llvm-symbolizer-$LLVM_VERSION "\$@"
EOF
chmod +x /usr/local/bin/llvm-symbolizer

###########
# ripgrep #
###########

RG_VERSION=15.1.0
RG_BASE_URL="https://github.com/BurntSushi/ripgrep/releases/download"
if [ $(uname -m) = "aarch64" ]; then
  #           ripgrep-  15.1.0     -aarch64-unknown-linux-gnu.tar.gz
  RG_TARBALL="ripgrep-${RG_VERSION}-aarch64-unknown-linux-gnu.tar.gz"
else
  #           ripgrep-  15.1.0     -x86_64-unknown-linux-musl.tar.gz
  RG_TARBALL="ripgrep-${RG_VERSION}-x86_64-unknown-linux-musl.tar.gz"
fi
mkdir -p /opt/ripgrep
RG_URL="${RG_BASE_URL}/${RG_VERSION}/${RG_TARBALL}"
echo "Downloading ripgrep from ${RG_URL}"
curl -sSL "$RG_URL" | tar -xz -C /opt/ripgrep --strip-components=1
ln -sf /opt/ripgrep/rg /usr/local/bin/rg
