// Copyright (c) 2014 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found at https://github.com/google/leveldb/blob/main/LICENSE. See
// https://github.com/google/leveldb/blob/main/AUTHORS for names of
// contributors.
//
// Modifications copyright 2025 Redpanda Data, Inc.

#include "lsm/block/filter.h"

#include "base/units.h"
#include "base/vassert.h"
#include "hashing/xx.h"
#include "lsm/core/internal/keys.h"

#include <seastar/core/byteorder.hh>
#include <seastar/core/temporary_buffer.hh>

#include <algorithm>
#include <bit>
#include <utility>

namespace lsm::block {

namespace bloom_filter {
namespace {

constexpr static uint8_t min_probes = 1;
constexpr static uint8_t max_probes = 30;
constexpr double ln2 = 0.69; // 0.69 ~ ln(2)

constexpr static size_t max_allocation_size = 128_KiB;

void create(
  uint8_t bits_per_key,
  const chunked_vector<ss::sstring>& keys,
  iobuf* filter) {
    // We intentionally round down to reduce probing cost a little bit
    auto num_probes = static_cast<uint8_t>(bits_per_key * ln2);
    num_probes = std::clamp(num_probes, min_probes, max_probes);
    // Prevent a high false positive rate by enforcing a minimum filter size.
    constexpr size_t min_bits = 64;
    size_t bits = std::max(keys.size() * bits_per_key, min_bits);
    size_t bytes = (bits + CHAR_WIDTH - 1) / CHAR_WIDTH;
    bits = bytes * CHAR_WIDTH;

    std::vector<ss::temporary_buffer<uint8_t>> chunks;
    for (size_t size = 0; size < bytes; size += max_allocation_size) {
        size_t remaining = bytes - size;
        auto& buf = chunks.emplace_back(
          std::min(remaining, max_allocation_size));
        std::fill_n(buf.get_write(), buf.size(), 0);
    }
    for (const auto& key : keys) {
        uint32_t h = XXH3_64bits(key.data(), key.size());
        // NOLINTNEXTLINE(*magic-number*)
        uint32_t delta = (h >> 17u) | (h << 15u); // Rotate right 17 bits
        for (size_t j = 0; j < num_probes; ++j) {
            uint32_t bitpos = h % bits;
            uint8_t mask = 1u << (bitpos % CHAR_WIDTH);
            size_t bytepos = bitpos / CHAR_WIDTH;
            uint8_t* chunk = chunks[bytepos / max_allocation_size].get_write();
            // NOLINTNEXTLINE(*pointer-arithmetic*)
            chunk[bytepos % max_allocation_size] |= mask;
            h += delta;
        }
    }
    for (auto& chunk : chunks) {
        filter->append(chunk.get(), chunk.size());
    }
    filter->append(std::to_array({num_probes}));
}

bool key_may_match(
  std::string_view key, block::contents& contents, size_t offset, size_t len) {
    if (len < 2) {
        return false; // Empty filter
    }
    size_t bits = (len - 1) * CHAR_WIDTH;
    // Use the encoded num_probes so that we can read filters generated by bloom
    // filters created using different parameters.
    uint8_t n_probes = contents[offset + (len - 1)];
    if (n_probes > max_probes) {
        return true;
    }
    uint32_t h = XXH3_64bits(key.data(), key.size());
    // NOLINTNEXTLINE(*magic-number*)
    uint32_t delta = (h >> 17u) | (h << 15u); // Rotate right 17 bits
    for (size_t j = 0; j < n_probes; j++) {
        uint32_t bitpos = h % bits;
        uint8_t byte = contents[offset + (bitpos / CHAR_WIDTH)];
        uint8_t mask = 1u << (bitpos % CHAR_WIDTH);
        if (!(byte & mask)) {
            return false;
        }
        h += delta;
    }
    return true;
}

} // namespace
} // namespace bloom_filter

filter_builder::filter_builder(options o)
  : _bits_per_key(o.bits_per_key)
  , _filter_base_lg(static_cast<uint8_t>(std::bit_width(o.filter_period) - 1))
  , _filter_base(1u << _filter_base_lg) {
    dassert(
      _filter_base == o.filter_period,
      "sst_filter_period must be a power of two, got: {}",
      o.filter_period);
}

void filter_builder::start_block(size_t block_offset) {
    uint64_t filter_index = block_offset / _filter_base;
    while (filter_index > _filter_offsets.size()) {
        generate_filter();
    }
}

void filter_builder::add_key(internal::key_view key) {
    _keys.emplace_back(key.user_key());
}

iobuf filter_builder::finish() {
    if (!_keys.empty()) {
        generate_filter();
    }
    // Append array of per-filter offsets
    uint32_t offsets_start = _filter.size_bytes();
    for (const auto& offset : std::exchange(_filter_offsets, {})) {
        _filter.append(
          std::bit_cast<std::array<uint8_t, sizeof(offset)>>(
            ss::cpu_to_le(offset)));
    }
    _filter.append(
      std::bit_cast<std::array<uint8_t, sizeof(uint32_t)>>(offsets_start));
    // Save the encoding parameter for backwards compatibility
    _filter.append(
      std::bit_cast<std::array<uint8_t, sizeof(uint8_t)>>(_filter_base_lg));
    return std::exchange(_filter, {});
}

void filter_builder::generate_filter() {
    _filter_offsets.emplace_back(_filter.size_bytes());
    if (_keys.empty()) {
        return;
    }
    bloom_filter::create(_bits_per_key, _keys, &_filter);
    _keys.clear();
}

filter_reader::filter_reader(ss::lw_shared_ptr<block::contents> c)
  : _contents(std::move(c))
  , _offset(0)
  , _num(0)
  , _base_lg(0) {
    size_t n = _contents->size();
    constexpr static size_t min_footer_size = sizeof(uint8_t)
                                              + sizeof(uint32_t);
    if (n < min_footer_size) {
        return;
    }
    _base_lg = (*_contents)[n - 1];
    auto offsets_start = _contents->read_fixed32(n - min_footer_size);
    if (offsets_start > n - min_footer_size) {
        return;
    }
    _offset = offsets_start;
    _num = (n - min_footer_size - offsets_start) / 4;
}

bool filter_reader::key_may_match(
  uint64_t block_offset, internal::key_view key) {
    uint64_t index = block_offset >> _base_lg;
    if (index < _num) {
        // TODO(perf): This is very much on the hot path, and decoding int32
        // from segmented bytes is not going to be the cheapest operation in the
        // world, maybe it makes sense to be able to decode these at
        // construction time and free the memory in _contents, with some kind of
        // `trim` operation.
        uint32_t position = _offset + (index * sizeof(uint32_t));
        auto start = _contents->read_fixed32(position);
        auto limit = _contents->read_fixed32(position + sizeof(uint32_t));
        if (start <= limit && limit <= _offset) {
            return bloom_filter::key_may_match(
              key.user_key(), *_contents, start, limit - start);
        }
    }
    return true; // Unknown/error cases we don't know
}

} // namespace lsm::block
