// Copyright (c) 2014 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found at https://github.com/google/leveldb/blob/main/LICENSE. See
// https://github.com/google/leveldb/blob/main/AUTHORS for names of
// contributors.
//
// Modifications copyright 2025 Redpanda Data, Inc.

#include "lsm/block/filter.h"

#include "base/units.h"
#include "base/vassert.h"
#include "hashing/crc32c.h"
#include "hashing/xx.h"
#include "lsm/core/compression.h"
#include "lsm/core/exceptions.h"
#include "lsm/core/internal/keys.h"

#include <seastar/core/byteorder.hh>
#include <seastar/core/coroutine.hh>
#include <seastar/core/future.hh>
#include <seastar/core/temporary_buffer.hh>

#include <algorithm>
#include <bit>
#include <utility>

namespace lsm::block {

namespace bloom_filter {
namespace {

constexpr static uint8_t min_probes = 1;
constexpr static uint8_t max_probes = 30;
constexpr double ln2 = 0.69; // 0.69 ~ ln(2)

constexpr static size_t max_allocation_size = 128_KiB;

void create(
  uint8_t bits_per_key,
  const chunked_vector<ss::sstring>& keys,
  iobuf* filter) {
    // We intentionally round down to reduce probing cost a little bit
    auto num_probes = static_cast<uint8_t>(bits_per_key * ln2);
    num_probes = std::clamp(num_probes, min_probes, max_probes);
    // Prevent a high false positive rate by enforcing a minimum filter size.
    constexpr size_t min_bits = 64;
    size_t bits = std::max(keys.size() * bits_per_key, min_bits);
    size_t bytes = (bits + CHAR_WIDTH - 1) / CHAR_WIDTH;
    bits = bytes * CHAR_WIDTH;

    std::vector<ss::temporary_buffer<uint8_t>> chunks;
    for (size_t size = 0; size < bytes; size += max_allocation_size) {
        size_t remaining = bytes - size;
        auto& buf = chunks.emplace_back(
          std::min(remaining, max_allocation_size));
        std::fill_n(buf.get_write(), buf.size(), 0);
    }
    for (const auto& key : keys) {
        uint32_t h = XXH3_64bits(key.data(), key.size());
        // NOLINTNEXTLINE(*magic-number*)
        uint32_t delta = (h >> 17u) | (h << 15u); // Rotate right 17 bits
        for (size_t j = 0; j < num_probes; ++j) {
            uint32_t bitpos = h % bits;
            uint8_t mask = 1u << (bitpos % CHAR_WIDTH);
            size_t bytepos = bitpos / CHAR_WIDTH;
            uint8_t* chunk = chunks[bytepos / max_allocation_size].get_write();
            // NOLINTNEXTLINE(*pointer-arithmetic*)
            chunk[bytepos % max_allocation_size] |= mask;
            h += delta;
        }
    }
    for (auto& chunk : chunks) {
        filter->append(chunk.get(), chunk.size());
    }
    filter->append(std::to_array({num_probes}));
}

bool key_may_match(
  std::string_view key, block::contents& contents, size_t offset, size_t len) {
    if (len < 2) {
        return false; // Empty filter
    }
    size_t bits = (len - 1) * CHAR_WIDTH;
    // Use the encoded num_probes so that we can read filters generated by bloom
    // filters created using different parameters.
    uint8_t n_probes = contents[offset + (len - 1)];
    if (n_probes > max_probes) {
        return true;
    }
    uint32_t h = XXH3_64bits(key.data(), key.size());
    // NOLINTNEXTLINE(*magic-number*)
    uint32_t delta = (h >> 17u) | (h << 15u); // Rotate right 17 bits
    for (size_t j = 0; j < n_probes; j++) {
        uint32_t bitpos = h % bits;
        uint8_t byte = contents[offset + (bitpos / CHAR_WIDTH)];
        uint8_t mask = 1u << (bitpos % CHAR_WIDTH);
        if (!(byte & mask)) {
            return false;
        }
        h += delta;
    }
    return true;
}

} // namespace
} // namespace bloom_filter

filter_builder::filter_builder(options o)
  : _bits_per_key(o.bits_per_key)
  , _filter_base_lg(static_cast<uint8_t>(std::bit_width(o.filter_period) - 1))
  , _filter_base(1u << _filter_base_lg) {
    dassert(
      _filter_base == o.filter_period,
      "sst_filter_period must be a power of two, got: {}",
      o.filter_period);
}

void filter_builder::start_block(size_t block_offset) {
    uint64_t filter_index = block_offset / _filter_base;
    while (filter_index > _filter_offsets.size()) {
        generate_filter();
    }
}

void filter_builder::add_key(internal::key_view key) {
    _keys.emplace_back(key.user_key());
}

iobuf filter_builder::finish() {
    if (!_keys.empty()) {
        generate_filter();
    }
    // Append array of per-filter offsets
    uint32_t offsets_start = _filter.size_bytes();
    for (const auto& offset : std::exchange(_filter_offsets, {})) {
        _filter.append(
          std::bit_cast<std::array<uint8_t, sizeof(offset)>>(
            ss::cpu_to_le(offset)));
    }
    _filter.append(
      std::bit_cast<std::array<uint8_t, sizeof(uint32_t)>>(offsets_start));
    // Save the encoding parameter for backwards compatibility
    _filter.append(
      std::bit_cast<std::array<uint8_t, sizeof(uint8_t)>>(_filter_base_lg));
    return std::exchange(_filter, {});
}

void filter_builder::generate_filter() {
    _filter_offsets.emplace_back(_filter.size_bytes());
    if (_keys.empty()) {
        return;
    }
    bloom_filter::create(_bits_per_key, _keys, &_filter);
    _keys.clear();
}

filter_reader::filter_reader(
  io::random_access_file_reader* file,
  uint64_t content_offset,
  contents tail,
  uint32_t offsets_start,
  size_t num,
  uint8_t base_lg,
  chunked_vector<uint32_t> region_crcs)
  : _file(file)
  , _content_offset(content_offset)
  , _tail(std::move(tail))
  , _offsets_start(offsets_start)
  , _num(num)
  , _base_lg(base_lg)
  , _region_crcs(std::move(region_crcs)) {}

ss::future<filter_reader> filter_reader::open(
  io::random_access_file_reader* file,
  uint64_t content_offset,
  uint64_t content_size) {
    // The content ends with a (offsets_start: u32, base_lg: u8) trailer.
    constexpr size_t trailer_size = sizeof(uint32_t) + sizeof(uint8_t);
    if (content_size < trailer_size) {
        // Too small to be a valid filter; treat every key as "may match".
        co_return filter_reader(
          file, content_offset, contents(ioarray{}), 0, 0, 0, {});
    }
    auto trailer = co_await file->read(
      content_offset + content_size - trailer_size, trailer_size);
    uint32_t offsets_start = trailer.read_fixed32(0);
    auto base_lg = static_cast<uint8_t>(trailer[sizeof(uint32_t)]);
    if (offsets_start > content_size - trailer_size) {
        co_return filter_reader(
          file,
          content_offset,
          contents(ioarray{}),
          offsets_start,
          0,
          base_lg,
          {});
    }
    size_t num = (content_size - trailer_size - offsets_start)
                 / sizeof(uint32_t);
    // Retain only the tail: the offset array plus the trailer. The bulk of the
    // filter (the per-region bloom data) is left on disk and read on demand.
    auto tail_buf = co_await file->read(
      content_offset + offsets_start, content_size - offsets_start);
    block::contents tail(std::move(tail_buf));

    // The SST builder writes the filter as an uncompressed block, so a trailer
    // -- a compression-type byte followed by the whole-block CRC -- immediately
    // follows the content. Validate that CRC, and in the same pass compute a
    // CRC over each region so lazy region reads can be checked against it.
    constexpr size_t block_trailer_size = sizeof(uint8_t)
                                          + sizeof(crc::crc32c::value_type);
    auto block_trailer = co_await file->read(
      content_offset + content_size, block_trailer_size);
    if (
      compression_type_from_raw(static_cast<uint8_t>(block_trailer[0]))
      != compression_type::none) {
        co_await ss::coroutine::return_exception(corruption_exception(
          "filter block unexpectedly compressed in {}", *file));
    }
    uint32_t expected_crc = block_trailer.read_fixed32(sizeof(uint8_t));

    // Region ordinal i covers [offset[i], offset[i+1]); the last region ends at
    // offsets_start. Offsets are contiguous, so a single forward scan over the
    // region data assigns each byte to exactly one region.
    auto region_end = [&](size_t i) -> uint64_t {
        return (i + 1 < num) ? tail.read_fixed32((i + 1) * sizeof(uint32_t))
                             : offsets_start;
    };
    constexpr size_t crc_window = 128 * 1024;
    crc::crc32c whole;
    chunked_vector<uint32_t> region_crcs;
    region_crcs.reserve(num);
    size_t region_idx = 0;
    crc::crc32c region;
    for (uint64_t rel = 0; rel < offsets_start;) {
        uint64_t win_len = std::min<uint64_t>(crc_window, offsets_start - rel);
        auto buf = co_await file->read(content_offset + rel, win_len);
        block::contents window(std::move(buf));
        crc_extend_iobuf(whole, window.share(0, win_len));
        // Split this window at region boundaries, carrying a region's CRC
        // across windows when the region is larger than one.
        for (uint64_t cur = rel; cur < rel + win_len && region_idx < num;) {
            uint64_t end = std::min<uint64_t>(
              region_end(region_idx), rel + win_len);
            if (end > cur) {
                crc_extend_iobuf(region, window.share(cur - rel, end - cur));
                cur = end;
            }
            if (cur == region_end(region_idx)) {
                region_crcs.push_back(region.value());
                region = crc::crc32c{};
                ++region_idx;
            } else {
                break; // region continues into the next window
            }
        }
        rel += win_len;
    }
    // Finalize any trailing empty regions (offset[i] == offsets_start).
    while (region_idx < num) {
        region_crcs.push_back(region.value());
        region = crc::crc32c{};
        ++region_idx;
    }

    // Fold the retained tail and the compression byte into the whole-block CRC
    // (it covers the content plus that byte) and verify it.
    crc_extend_iobuf(whole, tail.share(0, content_size - offsets_start));
    char compression_byte = block_trailer[0];
    whole.extend(&compression_byte, 1);
    if (whole.value() != expected_crc) {
        co_await ss::coroutine::return_exception(corruption_exception(
          "unexpected filter crc, got: {}, want: {} in {}",
          whole.value(),
          expected_crc,
          *file));
    }

    co_return filter_reader(
      file,
      content_offset,
      std::move(tail),
      offsets_start,
      num,
      base_lg,
      std::move(region_crcs));
}

ss::future<bool>
filter_reader::key_may_match(uint64_t block_offset, internal::key_view key) {
    uint64_t index = block_offset >> _base_lg;
    if (index >= _num) {
        co_return true; // Unknown region: conservatively may match.
    }
    // The offset array lives at the start of the retained tail. Entry `index`
    // is region `index`'s start (a position within the filter content); the
    // next entry -- or the offsets_start trailer for the last region -- is its
    // end.
    uint32_t start = _tail.read_fixed32(index * sizeof(uint32_t));
    uint32_t limit = _tail.read_fixed32((index + 1) * sizeof(uint32_t));
    if (start > limit || limit > _offsets_start) {
        co_return true; // Malformed offsets: conservatively may match.
    }
    if (limit - start < 2) {
        co_return false; // Empty region: no keys hashed here.
    }
    auto region = co_await _file->read(_content_offset + start, limit - start);
    block::contents region_contents(std::move(region));
    // Verify the region against the CRC computed at open, so a post-open disk
    // bit-flip is caught here rather than silently becoming a false negative.
    crc::crc32c actual;
    crc_extend_iobuf(actual, region_contents.share(0, limit - start));
    if (actual.value() != _region_crcs[index]) {
        co_await ss::coroutine::return_exception(corruption_exception(
          "filter region {} failed crc check, got: {}, want: {} in {}",
          index,
          actual.value(),
          _region_crcs[index],
          *_file));
    }
    co_return bloom_filter::key_may_match(
      key.user_key(), region_contents, 0, limit - start);
}

} // namespace lsm::block
