/*
 * Copyright 2026 Redpanda Data, Inc.
 *
 * Use of this software is governed by the Business Source License
 * included in the file licenses/BSL.md
 *
 * As of the Change Date specified in that file, in accordance with
 * the Business Source License, use of this software will be governed
 * by the Apache License, Version 2.0
 */
#include "kafka/server/handlers/consumer_group_heartbeat.h"

#include "config/configuration.h"
#include "features/feature_table.h"
#include "kafka/protocol/consumer_group_heartbeat.h"
#include "kafka/protocol/errors.h"
#include "kafka/server/group_router.h"
#include "kafka/server/request_context.h"
#include "kafka/server/response.h"

#include <seastar/core/coroutine.hh>

namespace kafka {

template<>
ss::future<response_ptr> consumer_group_heartbeat_handler::handle(
  request_context ctx, [[maybe_unused]] ss::smp_service_group g) {
    consumer_group_heartbeat_request request;
    request.decode(ctx.reader(), ctx.header().version);
    log_request(ctx.header(), request);

    if (
      unlikely(
        !config::shard_local_cfg().group_consumer_protocol_enabled()
        || !ctx.feature_table().local().is_active(
          features::feature::topic_ids_api))) {
        co_return co_await ctx.respond(consumer_group_heartbeat_response(
          error_code::unsupported_version,
          "The next generation consumer group protocol is not enabled"));
    }

    if (unlikely(ctx.recovery_mode_enabled())) {
        co_return co_await ctx.respond(
          consumer_group_heartbeat_response(error_code::policy_violation));
    }

    ctx.connection()->attributes().last_group_id.update(request.data.group_id);
    ctx.connection()->attributes().last_group_member_id.update(
      request.data.member_id);

    auto authz = ctx.authorized(
      security::acl_operation::read, request.data.group_id);

    if (!ctx.audit()) {
        co_return co_await ctx.respond(consumer_group_heartbeat_response(
          error_code::broker_not_available,
          "Broker not available - audit system failure"));
    }

    if (!authz) {
        co_return co_await ctx.respond(consumer_group_heartbeat_response(
          error_code::group_authorization_failed));
    }

    // KIP-1082: since version 1 the member id is generated by the consumer
    // and must be provided on every heartbeat, including the initial join.
    if (
      ctx.header().version >= api_version(1)
      && request.data.member_id().empty()) {
        co_return co_await ctx.respond(consumer_group_heartbeat_response(
          error_code::invalid_request,
          "MemberId can't be empty for ConsumerGroupHeartbeat v1 and above"));
    }

    if (ctx.header().client_id) {
        request.client_id = kafka::client_id(
          ss::sstring(*ctx.header().client_id));
    }
    request.client_host = kafka::client_host(
      fmt::format("{}", ctx.connection()->client_host()));

    auto resp = co_await ctx.groups().consumer_group_heartbeat(
      std::move(request));
    co_return co_await ctx.respond(std::move(resp));
}

} // namespace kafka
