// @generated by protoc-gen-es v2.6.1 with parameter "target=js"
// @generated from file example.proto (package example, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file example.proto.
 */
export const file_example = /*@__PURE__*/
  fileDesc("Cg1leGFtcGxlLnByb3RvEgdleGFtcGxlItABCgRVc2VyEhIKCmZpcnN0X25hbWUYASABKAkSEQoJbGFzdF9uYW1lGAIgASgJEg4KBmFjdGl2ZRgDIAEoCBIeCgdtYW5hZ2VyGAQgASgLMg0uZXhhbXBsZS5Vc2VyEhEKCWxvY2F0aW9ucxgFIAMoCRItCghwcm9qZWN0cxgGIAMoCzIbLmV4YW1wbGUuVXNlci5Qcm9qZWN0c0VudHJ5Gi8KDVByb2plY3RzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AWIGcHJvdG8z");

/**
 * Describes the message example.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema = /*@__PURE__*/
  messageDesc(file_example, 0);

