apiVersion: redpanda.vectorized.io/v1alpha1
kind: Console
metadata:
  name: console
spec:
  server:
    listenPort: 8080
  schema:
    enabled: true
  clusterRef:
    name: cluster
    namespace: default
  deployment:
    image: vectorized/console:master-173596f
  connect:
    enabled: true
    clusters:
    - name: console-connector
      url:  http://localhost:8083
      tls:
        enabled: true
        secretKeyRef:
          name: connector-tls
          namespace: default
