CREATE TABLE IF NOT EXISTS environment (
  sent_at        timestamp not null,
  received_at    timestamp not null,
  organization   varchar not null,
  cluster_id     varchar not null,
  node_id        integer not null,
  node_uuid      varchar not null,
  cloud_vendor   varchar,
  os_info        varchar,
  vm_type        varchar,
  cpu_model      varchar,
  cpu_cores      varchar,
  rp_version     varchar,
  ip             varchar,
  hostname       varchar,
  country        varchar,
  region         varchar,
  city           varchar,
  payload        jsonb,
  config         jsonb
);
