def not_implemented_method(*args, **kwargs) -> None: ...

class PDict(dict):
    __setitem__ = not_implemented_method
    __delitem__ = not_implemented_method
    update = not_implemented_method
    clear = not_implemented_method
    pop = not_implemented_method
    popitem = not_implemented_method
    def copy(self): ...
    def without(self, *keys): ...
    def using(self, **kwargs): ...
    def __reduce__(self): ...

make_dict = PDict
