/*
 * Copyright 2025 Redpanda Data, Inc.
 *
 * Licensed as a Redpanda Enterprise file under the Redpanda Community
 * License (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * https://github.com/redpanda-data/redpanda/blob/master/licenses/rcl.md
 */

#pragma once

#include "base/format_to.h"
#include "cloud_topics/level_one/common/abstract_io.h"
#include "cloud_topics/level_one/common/object_id.h"
#include "cloud_topics/level_one/compaction/committing_policy.h"
#include "cloud_topics/level_one/compaction/meta.h"
#include "cloud_topics/level_one/metastore/metastore.h"
#include "container/chunked_circular_buffer.h"

class ReducerTestFixture;

namespace cloud_topics::l1 {

// Responsible for committing updates generated by L1 compaction to the
// metastore and uploading new data to cloud storage.
class compaction_committer {
public:
    compaction_committer(std::unique_ptr<committing_policy>, io*, metastore*);

    // Launches background committing loop.
    ss::future<> start();

    // Shuts down concurrency primitives, thereby stopping the backgrounded
    // committing loop.
    ss::future<> stop();

    // Pushes an update to the queue to be committed.
    void push_update(object_output_t);

    // The `compaction_committer` is a sharded object within the
    // `compaction_scheduler`, which means calling `stop()` on it destructs the
    // underlying instances. Because `compaction_worker`s depend on the
    // `committer`, the `committer` is the last object to be `stop()`'ed during
    // shutdown. When the inflight workers/compaction jobs are stopped, a number
    // of updates to the committer may be pushed at shutdown. `notify_stopped()`
    // provides a way to let the `committer` know that it should not attempt to
    // commit any more updates before `stop()` is called to avoid this stampede
    // of last minute updates.
    void notify_stopped() { _stopped = true; }

private:
    friend class ::ReducerTestFixture;
    using updates_t = chunked_circular_buffer<object_output_t>;

    struct built_update_context {
        std::unique_ptr<metastore::object_metadata_builder> metadata_builder;
        metastore::compaction_map_t compact_map;
    };

    struct inflight_update_context {
        model::topic_id_partition tidp;
        chunked_vector<staging_file_ref_and_md_info>
          staging_file_refs_and_md_infos;
        metastore::compaction_update compact_update;
    };

    struct error {
        enum class type : uint8_t { build_or_put_failure, commit_failure } t;
        ss::sstring msg;

        fmt::iterator format_to(fmt::iterator it) const {
            return fmt::format_to(
              it, "type:{}, msg:{}", static_cast<int>(t), msg);
        }
    };

private:
    // Starts the backgrounded committing loop.
    void start_committing_loop();

    // Returns `true` if the committer is currently active and a shutdown has
    // not been requested.
    bool is_active() const;

    // The main committing loop. Invoked in a background fiber until `_as` has
    // an abort requested or the `_gate` is closed.
    ss::future<> committing_loop();

    // Builds update context to be committed from the provided updates.
    ss::future<std::expected<built_update_context, error>>
      build_and_put_update(inflight_update_context);

    ss::future<std::expected<void, error>>
      try_build_and_commit_update(inflight_update_context);

    // Attempts to commit all updates in the provided container to the metastore
    // and cloud storage.
    ss::future<> commit_some(updates_t);

    // Removes all staging files in an compaction update.
    // Should be called after successfully or unsuccessfully uploading &
    // committing a compaction update, or during clean-up of uncommitted
    // compaction updates during shutdown.
    ss::future<> remove_staging_files(object_output_t);

private:
    // A queue of updates to be committed.
    updates_t _updates;

    // The committing policy. Controls pre-emption and scheduling of commits
    // made to the metastore and cloud storage.
    std::unique_ptr<committing_policy> _policy;

    ssx::semaphore _sem{0, "cloud_topics::compaction::committing_loop"};

    // Used as a flag to notify committer that a shutdown has been triggered,
    // and commits should no longer occur.
    bool _stopped{false};

    ss::abort_source _as;
    ss::gate _gate;

    // Newly compacted objects are uploaded using `io`.
    io* _io;

    // Commits of newly compacted objects go to the `metastore`.
    metastore* _metastore;
};

} // namespace cloud_topics::l1
