load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "connections",
    srcs = ["connections.go"],
    importpath = "github.com/redpanda-data/redpanda/tests/go/client-swarm/internal/connections",
    visibility = ["//tests/go/client-swarm:__subpackages__"],
)
