// Copyright 2025 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/redpanda/core/admin/internal/cloud_topics/v1/metastore.proto

package cloudtopicsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	cloudtopicsv1 "github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/debug/cloudtopics/metastore/internal/cloudtopicsv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MetastoreServiceName is the fully-qualified name of the MetastoreService service.
	MetastoreServiceName = "redpanda.core.admin.internal.cloud_topics.v1.MetastoreService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MetastoreServiceGetOffsetsProcedure is the fully-qualified name of the MetastoreService's
	// GetOffsets RPC.
	MetastoreServiceGetOffsetsProcedure = "/redpanda.core.admin.internal.cloud_topics.v1.MetastoreService/GetOffsets"
	// MetastoreServiceGetSizeProcedure is the fully-qualified name of the MetastoreService's GetSize
	// RPC.
	MetastoreServiceGetSizeProcedure = "/redpanda.core.admin.internal.cloud_topics.v1.MetastoreService/GetSize"
	// MetastoreServiceGetDatabaseStatsProcedure is the fully-qualified name of the MetastoreService's
	// GetDatabaseStats RPC.
	MetastoreServiceGetDatabaseStatsProcedure = "/redpanda.core.admin.internal.cloud_topics.v1.MetastoreService/GetDatabaseStats"
	// MetastoreServiceWriteRowsProcedure is the fully-qualified name of the MetastoreService's
	// WriteRows RPC.
	MetastoreServiceWriteRowsProcedure = "/redpanda.core.admin.internal.cloud_topics.v1.MetastoreService/WriteRows"
	// MetastoreServiceReadRowsProcedure is the fully-qualified name of the MetastoreService's ReadRows
	// RPC.
	MetastoreServiceReadRowsProcedure = "/redpanda.core.admin.internal.cloud_topics.v1.MetastoreService/ReadRows"
	// MetastoreServiceListCloudTopicsProcedure is the fully-qualified name of the MetastoreService's
	// ListCloudTopics RPC.
	MetastoreServiceListCloudTopicsProcedure = "/redpanda.core.admin.internal.cloud_topics.v1.MetastoreService/ListCloudTopics"
	// MetastoreServiceValidatePartitionProcedure is the fully-qualified name of the MetastoreService's
	// ValidatePartition RPC.
	MetastoreServiceValidatePartitionProcedure = "/redpanda.core.admin.internal.cloud_topics.v1.MetastoreService/ValidatePartition"
)

// MetastoreServiceClient is a client for the
// redpanda.core.admin.internal.cloud_topics.v1.MetastoreService service.
type MetastoreServiceClient interface {
	// Get the start and next offsets for a set of topic partitions in the Kafka
	// namespace. If the metastore contains no data for this NTP then a not
	// found error will be thrown.
	GetOffsets(context.Context, *connect.Request[cloudtopicsv1.GetOffsetsRequest]) (*connect.Response[cloudtopicsv1.GetOffsetsResponse], error)
	// Get the size in bytes of a topic partition in the Kafka namespace. If
	// the metastore contains no data for this NTP then a not found error will
	// be thrown.
	GetSize(context.Context, *connect.Request[cloudtopicsv1.GetSizeRequest]) (*connect.Response[cloudtopicsv1.GetSizeResponse], error)
	// Get database statistics for the metastore database.
	// Returns detailed size information about the LSM tree including
	// memtable sizes and per-level breakdowns.
	GetDatabaseStats(context.Context, *connect.Request[cloudtopicsv1.GetDatabaseStatsRequest]) (*connect.Response[cloudtopicsv1.GetDatabaseStatsResponse], error)
	// Write or delete arbitrary rows in the LSM metastore database.
	// Enables manual repair and debugging of metastore state.
	WriteRows(context.Context, *connect.Request[cloudtopicsv1.WriteRowsRequest]) (*connect.Response[cloudtopicsv1.WriteRowsResponse], error)
	// Read rows from the LSM metastore database, decoding raw key/value
	// pairs into typed protobuf messages. Supports pagination.
	ReadRows(context.Context, *connect.Request[cloudtopicsv1.ReadRowsRequest]) (*connect.Response[cloudtopicsv1.ReadRowsResponse], error)
	// List cloud topics from the topic table, returning their names, UUIDs,
	// and partition counts. Supports pagination by topic name.
	ListCloudTopics(context.Context, *connect.Request[cloudtopicsv1.ListCloudTopicsRequest]) (*connect.Response[cloudtopicsv1.ListCloudTopicsResponse], error)
	// Validate metastore state for a single partition. Checks invariants
	// such as extent contiguity, offset bounds, and term ordering.
	// Supports pagination via max_extents and resume_after_offset to
	// bound the work per call. Cross-page contiguity is enforced by
	// checking the boundary between consecutive pages.
	ValidatePartition(context.Context, *connect.Request[cloudtopicsv1.ValidatePartitionRequest]) (*connect.Response[cloudtopicsv1.ValidatePartitionResponse], error)
}

// NewMetastoreServiceClient constructs a client for the
// redpanda.core.admin.internal.cloud_topics.v1.MetastoreService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMetastoreServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MetastoreServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	metastoreServiceMethods := cloudtopicsv1.File_proto_redpanda_core_admin_internal_cloud_topics_v1_metastore_proto.Services().ByName("MetastoreService").Methods()
	return &metastoreServiceClient{
		getOffsets: connect.NewClient[cloudtopicsv1.GetOffsetsRequest, cloudtopicsv1.GetOffsetsResponse](
			httpClient,
			baseURL+MetastoreServiceGetOffsetsProcedure,
			connect.WithSchema(metastoreServiceMethods.ByName("GetOffsets")),
			connect.WithClientOptions(opts...),
		),
		getSize: connect.NewClient[cloudtopicsv1.GetSizeRequest, cloudtopicsv1.GetSizeResponse](
			httpClient,
			baseURL+MetastoreServiceGetSizeProcedure,
			connect.WithSchema(metastoreServiceMethods.ByName("GetSize")),
			connect.WithClientOptions(opts...),
		),
		getDatabaseStats: connect.NewClient[cloudtopicsv1.GetDatabaseStatsRequest, cloudtopicsv1.GetDatabaseStatsResponse](
			httpClient,
			baseURL+MetastoreServiceGetDatabaseStatsProcedure,
			connect.WithSchema(metastoreServiceMethods.ByName("GetDatabaseStats")),
			connect.WithClientOptions(opts...),
		),
		writeRows: connect.NewClient[cloudtopicsv1.WriteRowsRequest, cloudtopicsv1.WriteRowsResponse](
			httpClient,
			baseURL+MetastoreServiceWriteRowsProcedure,
			connect.WithSchema(metastoreServiceMethods.ByName("WriteRows")),
			connect.WithClientOptions(opts...),
		),
		readRows: connect.NewClient[cloudtopicsv1.ReadRowsRequest, cloudtopicsv1.ReadRowsResponse](
			httpClient,
			baseURL+MetastoreServiceReadRowsProcedure,
			connect.WithSchema(metastoreServiceMethods.ByName("ReadRows")),
			connect.WithClientOptions(opts...),
		),
		listCloudTopics: connect.NewClient[cloudtopicsv1.ListCloudTopicsRequest, cloudtopicsv1.ListCloudTopicsResponse](
			httpClient,
			baseURL+MetastoreServiceListCloudTopicsProcedure,
			connect.WithSchema(metastoreServiceMethods.ByName("ListCloudTopics")),
			connect.WithClientOptions(opts...),
		),
		validatePartition: connect.NewClient[cloudtopicsv1.ValidatePartitionRequest, cloudtopicsv1.ValidatePartitionResponse](
			httpClient,
			baseURL+MetastoreServiceValidatePartitionProcedure,
			connect.WithSchema(metastoreServiceMethods.ByName("ValidatePartition")),
			connect.WithClientOptions(opts...),
		),
	}
}

// metastoreServiceClient implements MetastoreServiceClient.
type metastoreServiceClient struct {
	getOffsets        *connect.Client[cloudtopicsv1.GetOffsetsRequest, cloudtopicsv1.GetOffsetsResponse]
	getSize           *connect.Client[cloudtopicsv1.GetSizeRequest, cloudtopicsv1.GetSizeResponse]
	getDatabaseStats  *connect.Client[cloudtopicsv1.GetDatabaseStatsRequest, cloudtopicsv1.GetDatabaseStatsResponse]
	writeRows         *connect.Client[cloudtopicsv1.WriteRowsRequest, cloudtopicsv1.WriteRowsResponse]
	readRows          *connect.Client[cloudtopicsv1.ReadRowsRequest, cloudtopicsv1.ReadRowsResponse]
	listCloudTopics   *connect.Client[cloudtopicsv1.ListCloudTopicsRequest, cloudtopicsv1.ListCloudTopicsResponse]
	validatePartition *connect.Client[cloudtopicsv1.ValidatePartitionRequest, cloudtopicsv1.ValidatePartitionResponse]
}

// GetOffsets calls redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.GetOffsets.
func (c *metastoreServiceClient) GetOffsets(ctx context.Context, req *connect.Request[cloudtopicsv1.GetOffsetsRequest]) (*connect.Response[cloudtopicsv1.GetOffsetsResponse], error) {
	return c.getOffsets.CallUnary(ctx, req)
}

// GetSize calls redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.GetSize.
func (c *metastoreServiceClient) GetSize(ctx context.Context, req *connect.Request[cloudtopicsv1.GetSizeRequest]) (*connect.Response[cloudtopicsv1.GetSizeResponse], error) {
	return c.getSize.CallUnary(ctx, req)
}

// GetDatabaseStats calls
// redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.GetDatabaseStats.
func (c *metastoreServiceClient) GetDatabaseStats(ctx context.Context, req *connect.Request[cloudtopicsv1.GetDatabaseStatsRequest]) (*connect.Response[cloudtopicsv1.GetDatabaseStatsResponse], error) {
	return c.getDatabaseStats.CallUnary(ctx, req)
}

// WriteRows calls redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.WriteRows.
func (c *metastoreServiceClient) WriteRows(ctx context.Context, req *connect.Request[cloudtopicsv1.WriteRowsRequest]) (*connect.Response[cloudtopicsv1.WriteRowsResponse], error) {
	return c.writeRows.CallUnary(ctx, req)
}

// ReadRows calls redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.ReadRows.
func (c *metastoreServiceClient) ReadRows(ctx context.Context, req *connect.Request[cloudtopicsv1.ReadRowsRequest]) (*connect.Response[cloudtopicsv1.ReadRowsResponse], error) {
	return c.readRows.CallUnary(ctx, req)
}

// ListCloudTopics calls
// redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.ListCloudTopics.
func (c *metastoreServiceClient) ListCloudTopics(ctx context.Context, req *connect.Request[cloudtopicsv1.ListCloudTopicsRequest]) (*connect.Response[cloudtopicsv1.ListCloudTopicsResponse], error) {
	return c.listCloudTopics.CallUnary(ctx, req)
}

// ValidatePartition calls
// redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.ValidatePartition.
func (c *metastoreServiceClient) ValidatePartition(ctx context.Context, req *connect.Request[cloudtopicsv1.ValidatePartitionRequest]) (*connect.Response[cloudtopicsv1.ValidatePartitionResponse], error) {
	return c.validatePartition.CallUnary(ctx, req)
}

// MetastoreServiceHandler is an implementation of the
// redpanda.core.admin.internal.cloud_topics.v1.MetastoreService service.
type MetastoreServiceHandler interface {
	// Get the start and next offsets for a set of topic partitions in the Kafka
	// namespace. If the metastore contains no data for this NTP then a not
	// found error will be thrown.
	GetOffsets(context.Context, *connect.Request[cloudtopicsv1.GetOffsetsRequest]) (*connect.Response[cloudtopicsv1.GetOffsetsResponse], error)
	// Get the size in bytes of a topic partition in the Kafka namespace. If
	// the metastore contains no data for this NTP then a not found error will
	// be thrown.
	GetSize(context.Context, *connect.Request[cloudtopicsv1.GetSizeRequest]) (*connect.Response[cloudtopicsv1.GetSizeResponse], error)
	// Get database statistics for the metastore database.
	// Returns detailed size information about the LSM tree including
	// memtable sizes and per-level breakdowns.
	GetDatabaseStats(context.Context, *connect.Request[cloudtopicsv1.GetDatabaseStatsRequest]) (*connect.Response[cloudtopicsv1.GetDatabaseStatsResponse], error)
	// Write or delete arbitrary rows in the LSM metastore database.
	// Enables manual repair and debugging of metastore state.
	WriteRows(context.Context, *connect.Request[cloudtopicsv1.WriteRowsRequest]) (*connect.Response[cloudtopicsv1.WriteRowsResponse], error)
	// Read rows from the LSM metastore database, decoding raw key/value
	// pairs into typed protobuf messages. Supports pagination.
	ReadRows(context.Context, *connect.Request[cloudtopicsv1.ReadRowsRequest]) (*connect.Response[cloudtopicsv1.ReadRowsResponse], error)
	// List cloud topics from the topic table, returning their names, UUIDs,
	// and partition counts. Supports pagination by topic name.
	ListCloudTopics(context.Context, *connect.Request[cloudtopicsv1.ListCloudTopicsRequest]) (*connect.Response[cloudtopicsv1.ListCloudTopicsResponse], error)
	// Validate metastore state for a single partition. Checks invariants
	// such as extent contiguity, offset bounds, and term ordering.
	// Supports pagination via max_extents and resume_after_offset to
	// bound the work per call. Cross-page contiguity is enforced by
	// checking the boundary between consecutive pages.
	ValidatePartition(context.Context, *connect.Request[cloudtopicsv1.ValidatePartitionRequest]) (*connect.Response[cloudtopicsv1.ValidatePartitionResponse], error)
}

// NewMetastoreServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMetastoreServiceHandler(svc MetastoreServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	metastoreServiceMethods := cloudtopicsv1.File_proto_redpanda_core_admin_internal_cloud_topics_v1_metastore_proto.Services().ByName("MetastoreService").Methods()
	metastoreServiceGetOffsetsHandler := connect.NewUnaryHandler(
		MetastoreServiceGetOffsetsProcedure,
		svc.GetOffsets,
		connect.WithSchema(metastoreServiceMethods.ByName("GetOffsets")),
		connect.WithHandlerOptions(opts...),
	)
	metastoreServiceGetSizeHandler := connect.NewUnaryHandler(
		MetastoreServiceGetSizeProcedure,
		svc.GetSize,
		connect.WithSchema(metastoreServiceMethods.ByName("GetSize")),
		connect.WithHandlerOptions(opts...),
	)
	metastoreServiceGetDatabaseStatsHandler := connect.NewUnaryHandler(
		MetastoreServiceGetDatabaseStatsProcedure,
		svc.GetDatabaseStats,
		connect.WithSchema(metastoreServiceMethods.ByName("GetDatabaseStats")),
		connect.WithHandlerOptions(opts...),
	)
	metastoreServiceWriteRowsHandler := connect.NewUnaryHandler(
		MetastoreServiceWriteRowsProcedure,
		svc.WriteRows,
		connect.WithSchema(metastoreServiceMethods.ByName("WriteRows")),
		connect.WithHandlerOptions(opts...),
	)
	metastoreServiceReadRowsHandler := connect.NewUnaryHandler(
		MetastoreServiceReadRowsProcedure,
		svc.ReadRows,
		connect.WithSchema(metastoreServiceMethods.ByName("ReadRows")),
		connect.WithHandlerOptions(opts...),
	)
	metastoreServiceListCloudTopicsHandler := connect.NewUnaryHandler(
		MetastoreServiceListCloudTopicsProcedure,
		svc.ListCloudTopics,
		connect.WithSchema(metastoreServiceMethods.ByName("ListCloudTopics")),
		connect.WithHandlerOptions(opts...),
	)
	metastoreServiceValidatePartitionHandler := connect.NewUnaryHandler(
		MetastoreServiceValidatePartitionProcedure,
		svc.ValidatePartition,
		connect.WithSchema(metastoreServiceMethods.ByName("ValidatePartition")),
		connect.WithHandlerOptions(opts...),
	)
	return "/redpanda.core.admin.internal.cloud_topics.v1.MetastoreService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MetastoreServiceGetOffsetsProcedure:
			metastoreServiceGetOffsetsHandler.ServeHTTP(w, r)
		case MetastoreServiceGetSizeProcedure:
			metastoreServiceGetSizeHandler.ServeHTTP(w, r)
		case MetastoreServiceGetDatabaseStatsProcedure:
			metastoreServiceGetDatabaseStatsHandler.ServeHTTP(w, r)
		case MetastoreServiceWriteRowsProcedure:
			metastoreServiceWriteRowsHandler.ServeHTTP(w, r)
		case MetastoreServiceReadRowsProcedure:
			metastoreServiceReadRowsHandler.ServeHTTP(w, r)
		case MetastoreServiceListCloudTopicsProcedure:
			metastoreServiceListCloudTopicsHandler.ServeHTTP(w, r)
		case MetastoreServiceValidatePartitionProcedure:
			metastoreServiceValidatePartitionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMetastoreServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMetastoreServiceHandler struct{}

func (UnimplementedMetastoreServiceHandler) GetOffsets(context.Context, *connect.Request[cloudtopicsv1.GetOffsetsRequest]) (*connect.Response[cloudtopicsv1.GetOffsetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.GetOffsets is not implemented"))
}

func (UnimplementedMetastoreServiceHandler) GetSize(context.Context, *connect.Request[cloudtopicsv1.GetSizeRequest]) (*connect.Response[cloudtopicsv1.GetSizeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.GetSize is not implemented"))
}

func (UnimplementedMetastoreServiceHandler) GetDatabaseStats(context.Context, *connect.Request[cloudtopicsv1.GetDatabaseStatsRequest]) (*connect.Response[cloudtopicsv1.GetDatabaseStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.GetDatabaseStats is not implemented"))
}

func (UnimplementedMetastoreServiceHandler) WriteRows(context.Context, *connect.Request[cloudtopicsv1.WriteRowsRequest]) (*connect.Response[cloudtopicsv1.WriteRowsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.WriteRows is not implemented"))
}

func (UnimplementedMetastoreServiceHandler) ReadRows(context.Context, *connect.Request[cloudtopicsv1.ReadRowsRequest]) (*connect.Response[cloudtopicsv1.ReadRowsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.ReadRows is not implemented"))
}

func (UnimplementedMetastoreServiceHandler) ListCloudTopics(context.Context, *connect.Request[cloudtopicsv1.ListCloudTopicsRequest]) (*connect.Response[cloudtopicsv1.ListCloudTopicsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.ListCloudTopics is not implemented"))
}

func (UnimplementedMetastoreServiceHandler) ValidatePartition(context.Context, *connect.Request[cloudtopicsv1.ValidatePartitionRequest]) (*connect.Response[cloudtopicsv1.ValidatePartitionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redpanda.core.admin.internal.cloud_topics.v1.MetastoreService.ValidatePartition is not implemented"))
}
