- hosts: all
  tasks:

  - assert:
      that:
      - "rp_pkg is defined"

  - name: install base deps redhat
    package:
      name:
        - iotop
        - xfsprogs
        - java-11-openjdk-devel.x86_64
      state: present
    when: ansible_os_family == 'RedHat'
  - name: install base deps - debian
    package:
      name:
        - iotop
        - xfsprogs
        - openjdk-11-jdk-headless
      state: present
    when: ansible_os_family == 'Debian'

  - name: create xfs filesystem
    filesystem:
      fstype: xfs
      dev: /dev/nvme0n1

  - name: mount nvme device
    mount:
      path: /mnt/vectorized
      src: /dev/nvme0n1
      fstype: xfs
      state: mounted
  - name: data path
    file:
      path: /mnt/vectorized/redpanda
      state: directory
      owner: root
      group: root
      mode: ugo=rwx

  - name: set premissions
    file:
      dest: /var/lib/redpanda
      src: /mnt/vectorized/redpanda
      state: link
      owner: root
      group: root
      mode: ugo=rwx


  - name: copy redpanda package
    copy:
      src: '{{ rp_pkg }}'
      dest: '/tmp/{{ rp_pkg | basename }}'
  - name: install package with rpm
    yum:
      name: '/tmp/{{ rp_pkg | basename }}'
      state: present
    when:
    - '".rpm" in rp_pkg'
  - name: install package with dpkg
    apt:
      deb: '/tmp/{{ rp_pkg | basename }}'
      state: present
    when:
    - '".deb" in rp_pkg'

  - name: install kafka binaries
    unarchive:
      src: 'https://s3-us-west-2.amazonaws.com/kafka-packages/kafka_2.12-2.4.0.tgz'
      dest: /opt/
      remote_src: yes
      creates: /opt/kafka_2.12-2.4.0
  - name: create kafka-dev symlink directory referenced in tests
    file:
      src: /opt/kafka_2.12-2.4.0
      dest: /opt/kafka-dev
      state: link
