# fedora:31
FROM fedora@sha256:8fa60b88e2a7eac8460b9c0104b877f1aa0cea7fbc03c701b7e545dacccfb433

ENV CI=1

RUN rm -f /etc/yum.repos.d/fedora-* && \
    dnf install -y python3-pip python3-psutil python3-devel gcc git unzip && \
    dnf clean all && \
    curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-19.03.11.tgz && \
    tar xzvf docker-19.03.11.tgz --strip 1 -C /usr/local/bin docker/docker && \
    rm docker-19.03.11.tgz
