ARG BASE_SHA=latest
FROM gcr.io/redpandaci/base:${BASE_SHA}

# go dependencies are built with gcc, and are not affected by build-type
COPY tools/ci/vtools-gcc-release.yml /v/.vtools.yml

COPY src/go/rpk/go.mod src/go/rpk/go.sum /v/src/go/rpk/
COPY src/go/metrics/go.mod src/go/metrics/go.sum /v/src/go/metrics/

COPY /tools/ /v/

RUN pip install /v && \
    vtools install go-compiler && \
    vtools install go-deps && \
    rm -r /v
