"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetBuildInfoRequest(google.protobuf.message.Message):
    """GetBuildInfoRequest is used to request the build information of the Redpanda
    cluster.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___GetBuildInfoRequest = GetBuildInfoRequest

@typing.final
class BuildInfo(google.protobuf.message.Message):
    """BuildInfo contains information about the Redpanda build."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VERSION_FIELD_NUMBER: builtins.int
    BUILD_SHA_FIELD_NUMBER: builtins.int
    version: builtins.str
    'A version string of Redpanda like "v25.2.1" '
    build_sha: builtins.str
    'The git commit SHA of the build.'

    def __init__(self, *, version: builtins.str=..., build_sha: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['build_sha', b'build_sha', 'version', b'version']) -> None:
        ...
global___BuildInfo = BuildInfo

@typing.final
class RPCRoute(google.protobuf.message.Message):
    """A route in the Admin API RPC server."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    HTTP_ROUTE_FIELD_NUMBER: builtins.int
    name: builtins.str
    'The name of the RPC method.\n\n    For example `redpanda.core.admin.AdminService.GetVersion`\n    '
    http_route: builtins.str
    'The HTTP route for this RPC method.\n\n    For example `/v2/redpanda.core.admin.AdminService/GetVersion`\n    '

    def __init__(self, *, name: builtins.str=..., http_route: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['http_route', b'http_route', 'name', b'name']) -> None:
        ...
global___RPCRoute = RPCRoute

@typing.final
class ListRPCRoutesRequest(google.protobuf.message.Message):
    """ListRPCRoutesRequest is used to request the list of available RPC routes in
    the Admin API.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___ListRPCRoutesRequest = ListRPCRoutesRequest

@typing.final
class ListRPCRoutesResponse(google.protobuf.message.Message):
    """ListRPCRoutesResponse contains the list of available RPC routes in the Admin
    API.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ROUTES_FIELD_NUMBER: builtins.int

    @property
    def routes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RPCRoute]:
        """All the routes available in the Admin API."""

    def __init__(self, *, routes: collections.abc.Iterable[global___RPCRoute] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['routes', b'routes']) -> None:
        ...
global___ListRPCRoutesResponse = ListRPCRoutesResponse