"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TranslationStatus:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TranslationStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TranslationStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TRANSLATION_STATUS_UNSPECIFIED: _TranslationStatus.ValueType
    TRANSLATION_STATUS_DISABLED: _TranslationStatus.ValueType
    TRANSLATION_STATUS_ENABLED: _TranslationStatus.ValueType

class TranslationStatus(_TranslationStatus, metaclass=_TranslationStatusEnumTypeWrapper):
    """Indicates whether translation is enabled for a topic."""
TRANSLATION_STATUS_UNSPECIFIED: TranslationStatus.ValueType
TRANSLATION_STATUS_DISABLED: TranslationStatus.ValueType
TRANSLATION_STATUS_ENABLED: TranslationStatus.ValueType
Global___TranslationStatus: typing_extensions.TypeAlias = TranslationStatus

@typing.final
class PartitionState(google.protobuf.message.Message):
    """State of a single partition's Iceberg translation."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LAST_CATALOG_COMMITTED_OFFSET_FIELD_NUMBER: builtins.int
    last_catalog_committed_offset: builtins.int
    'Last translated offset for the partition. If not set, no translation\n    has been done for the partition.\n    '

    def __init__(self, *, last_catalog_committed_offset: builtins.int | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_last_catalog_committed_offset', b'_last_catalog_committed_offset', 'last_catalog_committed_offset', b'last_catalog_committed_offset']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_last_catalog_committed_offset', b'_last_catalog_committed_offset', 'last_catalog_committed_offset', b'last_catalog_committed_offset']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_last_catalog_committed_offset', b'_last_catalog_committed_offset']) -> typing.Literal['last_catalog_committed_offset'] | None:
        ...
Global___PartitionState: typing_extensions.TypeAlias = PartitionState

@typing.final
class TopicState(google.protobuf.message.Message):
    """Iceberg translation state for a topic."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PartitionStatesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int

        @property
        def value(self) -> Global___PartitionState:
            ...

        def __init__(self, *, key: builtins.int=..., value: Global___PartitionState | None=...) -> None:
            ...

        def HasField(self, field_name: typing.Literal['value', b'value']) -> builtins.bool:
            ...

        def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
            ...
    PARTITION_STATES_FIELD_NUMBER: builtins.int
    TRANSLATION_STATUS_FIELD_NUMBER: builtins.int
    LAST_COMMITTED_SNAPSHOT_ID_FIELD_NUMBER: builtins.int
    NAMESPACE_NAME_FIELD_NUMBER: builtins.int
    TABLE_NAME_FIELD_NUMBER: builtins.int
    DLQ_TABLE_NAME_FIELD_NUMBER: builtins.int
    translation_status: Global___TranslationStatus.ValueType
    'Whether translation is enabled for this topic.'
    last_committed_snapshot_id: builtins.int
    'Last committed snapshot ID for the topic. If not set, no snapshot has\n    been committed for the topic.\n    '
    table_name: builtins.str
    'Iceberg table name'
    dlq_table_name: builtins.str
    'Iceberg DLQ (dead letter queue) table name'

    @property
    def partition_states(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, Global___PartitionState]:
        """Per-partition translation state, keyed by partition index."""

    @property
    def namespace_name(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Iceberg namespace name"""

    def __init__(self, *, partition_states: collections.abc.Mapping[builtins.int, Global___PartitionState] | None=..., translation_status: Global___TranslationStatus.ValueType=..., last_committed_snapshot_id: builtins.int | None=..., namespace_name: collections.abc.Iterable[builtins.str] | None=..., table_name: builtins.str=..., dlq_table_name: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_last_committed_snapshot_id', b'_last_committed_snapshot_id', 'last_committed_snapshot_id', b'last_committed_snapshot_id']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_last_committed_snapshot_id', b'_last_committed_snapshot_id', 'dlq_table_name', b'dlq_table_name', 'last_committed_snapshot_id', b'last_committed_snapshot_id', 'namespace_name', b'namespace_name', 'partition_states', b'partition_states', 'table_name', b'table_name', 'translation_status', b'translation_status']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['_last_committed_snapshot_id', b'_last_committed_snapshot_id']) -> typing.Literal['last_committed_snapshot_id'] | None:
        ...
Global___TopicState: typing_extensions.TypeAlias = TopicState

@typing.final
class GetTranslationStateRequest(google.protobuf.message.Message):
    """Returns the Iceberg translation state for one or more topics."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOPICS_FILTER_FIELD_NUMBER: builtins.int

    @property
    def topics_filter(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Names of topics whose state to return. Must be not empty."""

    def __init__(self, *, topics_filter: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['topics_filter', b'topics_filter']) -> None:
        ...
Global___GetTranslationStateRequest: typing_extensions.TypeAlias = GetTranslationStateRequest

@typing.final
class GetTranslationStateResponse(google.protobuf.message.Message):
    """Response containing per-topic Iceberg translation state."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TopicStatesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str

        @property
        def value(self) -> Global___TopicState:
            ...

        def __init__(self, *, key: builtins.str=..., value: Global___TopicState | None=...) -> None:
            ...

        def HasField(self, field_name: typing.Literal['value', b'value']) -> builtins.bool:
            ...

        def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
            ...
    TOPIC_STATES_FIELD_NUMBER: builtins.int

    @property
    def topic_states(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, Global___TopicState]:
        """Map of topic name to its translation state."""

    def __init__(self, *, topic_states: collections.abc.Mapping[builtins.str, Global___TopicState] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['topic_states', b'topic_states']) -> None:
        ...
Global___GetTranslationStateResponse: typing_extensions.TypeAlias = GetTranslationStateResponse