"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
from ........ import proto
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _State:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_State.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    L0_GC_STATE_STARTED: _State.ValueType
    L0_GC_STATE_PAUSED: _State.ValueType
    L0_GC_STATE_STOPPED: _State.ValueType

class State(_State, metaclass=_StateEnumTypeWrapper):
    ...
L0_GC_STATE_STARTED: State.ValueType
L0_GC_STATE_PAUSED: State.ValueType
L0_GC_STATE_STOPPED: State.ValueType
Global___State: typing_extensions.TypeAlias = State

class _Error:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Error.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    L0_GC_ERROR_SUCCESS: _Error.ValueType
    L0_GC_ERROR_FAILED: _Error.ValueType
    L0_GC_ERROR_TOPIC_NOT_FOUND: _Error.ValueType
    L0_GC_ERROR_INVALID_PARTITION: _Error.ValueType
    L0_GC_ERROR_NOT_CLOUD_TOPIC: _Error.ValueType

class Error(_Error, metaclass=_ErrorEnumTypeWrapper):
    """Error indicates success or failure for an attempt to advance the
    epoch of some partition.
    """
L0_GC_ERROR_SUCCESS: Error.ValueType
L0_GC_ERROR_FAILED: Error.ValueType
L0_GC_ERROR_TOPIC_NOT_FOUND: Error.ValueType
L0_GC_ERROR_INVALID_PARTITION: Error.ValueType
L0_GC_ERROR_NOT_CLOUD_TOPIC: Error.ValueType
Global___Error: typing_extensions.TypeAlias = Error

@typing.final
class StartRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___StartRequest: typing_extensions.TypeAlias = StartRequest

@typing.final
class StartResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATE_FIELD_NUMBER: builtins.int
    state: Global___State.ValueType

    def __init__(self, *, state: Global___State.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['state', b'state']) -> None:
        ...
Global___StartResponse: typing_extensions.TypeAlias = StartResponse

@typing.final
class PauseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___PauseRequest: typing_extensions.TypeAlias = PauseRequest

@typing.final
class PauseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATE_FIELD_NUMBER: builtins.int
    state: Global___State.ValueType

    def __init__(self, *, state: Global___State.ValueType=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['state', b'state']) -> None:
        ...
Global___PauseResponse: typing_extensions.TypeAlias = PauseResponse

@typing.final
class AdvanceEpochRequest(google.protobuf.message.Message):
    """AdvanceEpochRequest is the request for advancing the LO epoch for one or more
    partitions.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITIONS_FIELD_NUMBER: builtins.int

    @property
    def partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TopicPartitionEpoch]:
        """Topic partitions to advance the epoch for"""

    def __init__(self, *, partitions: collections.abc.Iterable[Global___TopicPartitionEpoch] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['partitions', b'partitions']) -> None:
        ...
Global___AdvanceEpochRequest: typing_extensions.TypeAlias = AdvanceEpochRequest

@typing.final
class AdvanceEpochResponse(google.protobuf.message.Message):
    """AdvanceEpochResponse is the result of trying to advance the L0 epoch for one
    or more partitions
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITIONS_FIELD_NUMBER: builtins.int

    @property
    def partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TopicPartitionAdvanceEpochResult]:
        """The per-partition results"""

    def __init__(self, *, partitions: collections.abc.Iterable[Global___TopicPartitionAdvanceEpochResult] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['partitions', b'partitions']) -> None:
        ...
Global___AdvanceEpochResponse: typing_extensions.TypeAlias = AdvanceEpochResponse

@typing.final
class TopicPartitionEpoch(google.protobuf.message.Message):
    """TopicPartitionEpoch is an aggregate of a single topic partition and the
    expected current epoch for that partition.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITION_FIELD_NUMBER: builtins.int
    EPOCH_FIELD_NUMBER: builtins.int
    epoch: builtins.int
    'The expected current epoch of partition'

    @property
    def partition(self) -> proto.redpanda.core.common.v1.ntp_pb2.TopicPartition:
        """The partition to advance"""

    def __init__(self, *, partition: proto.redpanda.core.common.v1.ntp_pb2.TopicPartition | None=..., epoch: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['partition', b'partition']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['epoch', b'epoch', 'partition', b'partition']) -> None:
        ...
Global___TopicPartitionEpoch: typing_extensions.TypeAlias = TopicPartitionEpoch

@typing.final
class TopicPartitionAdvanceEpochResult(google.protobuf.message.Message):
    """TopicPartitionAdvanceEpochResult is an aggregate of a single topic partition
    and the result (success or failure) of trying to advance its epoch.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITION_FIELD_NUMBER: builtins.int
    EPOCH_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    epoch: builtins.int
    error: Global___Error.ValueType

    @property
    def partition(self) -> proto.redpanda.core.common.v1.ntp_pb2.TopicPartition:
        """The partition we tried to advance"""

    def __init__(self, *, partition: proto.redpanda.core.common.v1.ntp_pb2.TopicPartition | None=..., epoch: builtins.int=..., error: Global___Error.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['epoch', b'epoch', 'error', b'error', 'partition', b'partition', 'result', b'result']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['epoch', b'epoch', 'error', b'error', 'partition', b'partition', 'result', b'result']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['result', b'result']) -> typing.Literal['epoch', 'error'] | None:
        ...
Global___TopicPartitionAdvanceEpochResult: typing_extensions.TypeAlias = TopicPartitionAdvanceEpochResult

@typing.final
class GetEpochRequest(google.protobuf.message.Message):
    """GetEpochRequest is the request for getting the L0 epoch for one or more
    partitions.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITIONS_FIELD_NUMBER: builtins.int

    @property
    def partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[proto.redpanda.core.common.v1.ntp_pb2.TopicPartition]:
        """Topic partitions to get the epoch for"""

    def __init__(self, *, partitions: collections.abc.Iterable[proto.redpanda.core.common.v1.ntp_pb2.TopicPartition] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['partitions', b'partitions']) -> None:
        ...
Global___GetEpochRequest: typing_extensions.TypeAlias = GetEpochRequest

@typing.final
class GetEpochResponse(google.protobuf.message.Message):
    """GetEpochResponse is the result of trying to get the L0 epoch for one
    or more partitions
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITIONS_FIELD_NUMBER: builtins.int

    @property
    def partitions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TopicPartitionGetEpochResult]:
        """The per-partition results"""

    def __init__(self, *, partitions: collections.abc.Iterable[Global___TopicPartitionGetEpochResult] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['partitions', b'partitions']) -> None:
        ...
Global___GetEpochResponse: typing_extensions.TypeAlias = GetEpochResponse

@typing.final
class TopicPartitionGetEpochResult(google.protobuf.message.Message):
    """TopicPartitionGetEpochResult is an aggregate of a single topic partition
    and the result (success or failure) of trying to get its epoch.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITION_FIELD_NUMBER: builtins.int
    EPOCH_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    epoch: builtins.int
    error: Global___Error.ValueType

    @property
    def partition(self) -> proto.redpanda.core.common.v1.ntp_pb2.TopicPartition:
        """The partition we tried to get the epoch for"""

    def __init__(self, *, partition: proto.redpanda.core.common.v1.ntp_pb2.TopicPartition | None=..., epoch: builtins.int=..., error: Global___Error.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['epoch', b'epoch', 'error', b'error', 'partition', b'partition', 'result', b'result']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['epoch', b'epoch', 'error', b'error', 'partition', b'partition', 'result', b'result']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['result', b'result']) -> typing.Literal['epoch', 'error'] | None:
        ...
Global___TopicPartitionGetEpochResult: typing_extensions.TypeAlias = TopicPartitionGetEpochResult