"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _KafkaConnectionState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _KafkaConnectionStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_KafkaConnectionState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    KAFKA_CONNECTION_STATE_UNSPECIFIED: _KafkaConnectionState.ValueType
    KAFKA_CONNECTION_STATE_OPEN: _KafkaConnectionState.ValueType
    'The connection is accepting requests.'
    KAFKA_CONNECTION_STATE_ABORTING: _KafkaConnectionState.ValueType
    'The connection is aborting ongoing requests and about to be closed.\n    This is a transient state between open and closed that should rarely be\n    observable under normal circumstances.\n    '
    KAFKA_CONNECTION_STATE_CLOSED: _KafkaConnectionState.ValueType
    'The connection has been closed.'

class KafkaConnectionState(_KafkaConnectionState, metaclass=_KafkaConnectionStateEnumTypeWrapper):
    """Enums"""
KAFKA_CONNECTION_STATE_UNSPECIFIED: KafkaConnectionState.ValueType
KAFKA_CONNECTION_STATE_OPEN: KafkaConnectionState.ValueType
'The connection is accepting requests.'
KAFKA_CONNECTION_STATE_ABORTING: KafkaConnectionState.ValueType
'The connection is aborting ongoing requests and about to be closed.\nThis is a transient state between open and closed that should rarely be\nobservable under normal circumstances.\n'
KAFKA_CONNECTION_STATE_CLOSED: KafkaConnectionState.ValueType
'The connection has been closed.'
Global___KafkaConnectionState: typing_extensions.TypeAlias = KafkaConnectionState

class _AuthenticationState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AuthenticationStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AuthenticationState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AUTHENTICATION_STATE_UNSPECIFIED: _AuthenticationState.ValueType
    AUTHENTICATION_STATE_UNAUTHENTICATED: _AuthenticationState.ValueType
    AUTHENTICATION_STATE_SUCCESS: _AuthenticationState.ValueType
    AUTHENTICATION_STATE_FAILURE: _AuthenticationState.ValueType

class AuthenticationState(_AuthenticationState, metaclass=_AuthenticationStateEnumTypeWrapper):
    ...
AUTHENTICATION_STATE_UNSPECIFIED: AuthenticationState.ValueType
AUTHENTICATION_STATE_UNAUTHENTICATED: AuthenticationState.ValueType
AUTHENTICATION_STATE_SUCCESS: AuthenticationState.ValueType
AUTHENTICATION_STATE_FAILURE: AuthenticationState.ValueType
Global___AuthenticationState: typing_extensions.TypeAlias = AuthenticationState

class _AuthenticationMechanism:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AuthenticationMechanismEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AuthenticationMechanism.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    AUTHENTICATION_MECHANISM_UNSPECIFIED: _AuthenticationMechanism.ValueType
    AUTHENTICATION_MECHANISM_MTLS: _AuthenticationMechanism.ValueType
    'Mutual TLS using client certificates'
    AUTHENTICATION_MECHANISM_SASL_SCRAM: _AuthenticationMechanism.ValueType
    'SASL SCRAM'
    AUTHENTICATION_MECHANISM_SASL_OAUTHBEARER: _AuthenticationMechanism.ValueType
    'SASL OAUTHBEARER (OAuth 2.0 / OpenID Connect)'
    AUTHENTICATION_MECHANISM_SASL_PLAIN: _AuthenticationMechanism.ValueType
    'SASL PLAIN (username/password in plaintext)'
    AUTHENTICATION_MECHANISM_SASL_GSSAPI: _AuthenticationMechanism.ValueType
    'SASL GSSAPI (Kerberos)'

class AuthenticationMechanism(_AuthenticationMechanism, metaclass=_AuthenticationMechanismEnumTypeWrapper):
    ...
AUTHENTICATION_MECHANISM_UNSPECIFIED: AuthenticationMechanism.ValueType
AUTHENTICATION_MECHANISM_MTLS: AuthenticationMechanism.ValueType
'Mutual TLS using client certificates'
AUTHENTICATION_MECHANISM_SASL_SCRAM: AuthenticationMechanism.ValueType
'SASL SCRAM'
AUTHENTICATION_MECHANISM_SASL_OAUTHBEARER: AuthenticationMechanism.ValueType
'SASL OAUTHBEARER (OAuth 2.0 / OpenID Connect)'
AUTHENTICATION_MECHANISM_SASL_PLAIN: AuthenticationMechanism.ValueType
'SASL PLAIN (username/password in plaintext)'
AUTHENTICATION_MECHANISM_SASL_GSSAPI: AuthenticationMechanism.ValueType
'SASL GSSAPI (Kerberos)'
Global___AuthenticationMechanism: typing_extensions.TypeAlias = AuthenticationMechanism

@typing.final
class KafkaConnection(google.protobuf.message.Message):
    """Resources

    Kafka connection details for a broker
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ApiVersionsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.int

        def __init__(self, *, key: builtins.int=..., value: builtins.int=...) -> None:
            ...

        def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
            ...
    NODE_ID_FIELD_NUMBER: builtins.int
    SHARD_ID_FIELD_NUMBER: builtins.int
    UID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    OPEN_TIME_FIELD_NUMBER: builtins.int
    CLOSE_TIME_FIELD_NUMBER: builtins.int
    AUTHENTICATION_INFO_FIELD_NUMBER: builtins.int
    LISTENER_NAME_FIELD_NUMBER: builtins.int
    TLS_INFO_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    CLIENT_SOFTWARE_NAME_FIELD_NUMBER: builtins.int
    CLIENT_SOFTWARE_VERSION_FIELD_NUMBER: builtins.int
    TRANSACTIONAL_ID_FIELD_NUMBER: builtins.int
    GROUP_ID_FIELD_NUMBER: builtins.int
    GROUP_INSTANCE_ID_FIELD_NUMBER: builtins.int
    GROUP_MEMBER_ID_FIELD_NUMBER: builtins.int
    API_VERSIONS_FIELD_NUMBER: builtins.int
    IDLE_DURATION_FIELD_NUMBER: builtins.int
    IN_FLIGHT_REQUESTS_FIELD_NUMBER: builtins.int
    TOTAL_REQUEST_STATISTICS_FIELD_NUMBER: builtins.int
    RECENT_REQUEST_STATISTICS_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    'Broker node ID'
    shard_id: builtins.int
    'Broker shard that handles the connection'
    uid: builtins.str
    'Kafka connection UUID'
    state: Global___KafkaConnectionState.ValueType
    'Lifecycle state of the connection (open/aborting/closed)'
    listener_name: builtins.str
    'Name of the Kafka listener that accepted this connection.\n    A listener is a named broker endpoint (for example, "internal",\n    "external", or "sasl_tls"). Each listener defines its network address and\n    enforces its protocol and authentication policy.\n    '
    client_id: builtins.str
    'Client identifier included in every request sent by the Kafka client.\n    This is typically a configurable property (client.id) set by the\n    application when creating a producer or consumer, and is often used for\n    metrics, quotas, and debugging.\n    '
    client_software_name: builtins.str
    'Name of the client library, reported automatically in ApiVersions v3+\n    requests. This is set by the client implementation and is not typically\n    configurable by applications.\n    '
    client_software_version: builtins.str
    'Version of the client library, reported automatically in ApiVersions v3+\n    requests. Like client_software_name, this is set by the\n    client and not usually configurable by applications.\n    '
    transactional_id: builtins.str
    'Most recent transactional ID seen in requests sent over this connection'
    group_id: builtins.str
    'Most recent group ID seen in requests sent over this connection. This\n    typically refers to a consumer group, but the Kafka group protocol is\n    more general and may also be used by other types of clients that\n    coordinate membership and assignments through the broker.\n    '
    group_instance_id: builtins.str
    'Most recent group instance ID seen in requests sent over this connection.\n    This is used when static membership is enabled, allowing a specific\n    client instance to retain its group membership across restarts.\n    '
    group_member_id: builtins.str
    'Most recent group member ID seen in requests sent over this connection.\n    This is the unique identifier assigned by the broker to a particular\n    member of the group.\n    '

    @property
    def open_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """When the broker accepted the connection"""

    @property
    def close_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """When the connection was closed. This field is set only when the
        connection state is "closed".
        """

    @property
    def authentication_info(self) -> Global___AuthenticationInfo:
        """Information about the authentication state of the connection"""

    @property
    def tls_info(self) -> Global___TLSInfo:
        """Information about the TLS state of the connection (e.g., whether TLS
        encryption is used for this connection)
        """

    @property
    def source(self) -> Global___Source:
        """Remote client address of the TCP connection"""

    @property
    def api_versions(self) -> google.protobuf.internal.containers.ScalarMap[builtins.int, builtins.int]:
        """This map records, for each Kafka API, the highest version number observed
        in requests on this connection. It can be useful for understanding which
        protocol versions a client supports or has negotiated with the broker.
        Only APIs that were actually used (i.e. at least one request was seen)
        are included.

        Example:
          { 0: 11, 1: 13 }
        means that for API key 0 (Produce), version 11 was the highest seen,
        and for API key 1 (Fetch), version 13 was the highest seen.

        Reference:
        - https://kafka.apache.org/0101/protocol.html#protocol_api_keys
        - https://kafka.apache.org/0101/protocol.html#protocol_compatibility
        """

    @property
    def idle_duration(self) -> google.protobuf.duration_pb2.Duration:
        """How long the connection has been idle (no in-flight requests)"""

    @property
    def in_flight_requests(self) -> Global___InFlightRequests:
        """Currently in-flight requests"""

    @property
    def total_request_statistics(self) -> Global___RequestStatistics:
        """Aggregated statistics for the entire connection's lifetime."""

    @property
    def recent_request_statistics(self) -> Global___RequestStatistics:
        """Statistics for previous last one minute window."""

    def __init__(self, *, node_id: builtins.int=..., shard_id: builtins.int=..., uid: builtins.str=..., state: Global___KafkaConnectionState.ValueType=..., open_time: google.protobuf.timestamp_pb2.Timestamp | None=..., close_time: google.protobuf.timestamp_pb2.Timestamp | None=..., authentication_info: Global___AuthenticationInfo | None=..., listener_name: builtins.str=..., tls_info: Global___TLSInfo | None=..., source: Global___Source | None=..., client_id: builtins.str=..., client_software_name: builtins.str=..., client_software_version: builtins.str=..., transactional_id: builtins.str=..., group_id: builtins.str=..., group_instance_id: builtins.str=..., group_member_id: builtins.str=..., api_versions: collections.abc.Mapping[builtins.int, builtins.int] | None=..., idle_duration: google.protobuf.duration_pb2.Duration | None=..., in_flight_requests: Global___InFlightRequests | None=..., total_request_statistics: Global___RequestStatistics | None=..., recent_request_statistics: Global___RequestStatistics | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['authentication_info', b'authentication_info', 'close_time', b'close_time', 'idle_duration', b'idle_duration', 'in_flight_requests', b'in_flight_requests', 'open_time', b'open_time', 'recent_request_statistics', b'recent_request_statistics', 'source', b'source', 'tls_info', b'tls_info', 'total_request_statistics', b'total_request_statistics']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['api_versions', b'api_versions', 'authentication_info', b'authentication_info', 'client_id', b'client_id', 'client_software_name', b'client_software_name', 'client_software_version', b'client_software_version', 'close_time', b'close_time', 'group_id', b'group_id', 'group_instance_id', b'group_instance_id', 'group_member_id', b'group_member_id', 'idle_duration', b'idle_duration', 'in_flight_requests', b'in_flight_requests', 'listener_name', b'listener_name', 'node_id', b'node_id', 'open_time', b'open_time', 'recent_request_statistics', b'recent_request_statistics', 'shard_id', b'shard_id', 'source', b'source', 'state', b'state', 'tls_info', b'tls_info', 'total_request_statistics', b'total_request_statistics', 'transactional_id', b'transactional_id', 'uid', b'uid']) -> None:
        ...
Global___KafkaConnection: typing_extensions.TypeAlias = KafkaConnection

@typing.final
class AuthenticationInfo(google.protobuf.message.Message):
    """Other Messages"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATE_FIELD_NUMBER: builtins.int
    MECHANISM_FIELD_NUMBER: builtins.int
    USER_PRINCIPAL_FIELD_NUMBER: builtins.int
    state: Global___AuthenticationState.ValueType
    'Authentication state'
    mechanism: Global___AuthenticationMechanism.ValueType
    'Authentication mechanism'
    user_principal: builtins.str
    'Authenticated user principal'

    def __init__(self, *, state: Global___AuthenticationState.ValueType=..., mechanism: Global___AuthenticationMechanism.ValueType=..., user_principal: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['mechanism', b'mechanism', 'state', b'state', 'user_principal', b'user_principal']) -> None:
        ...
Global___AuthenticationInfo: typing_extensions.TypeAlias = AuthenticationInfo

@typing.final
class TLSInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENABLED_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    'Whether TLS is in use'

    def __init__(self, *, enabled: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['enabled', b'enabled']) -> None:
        ...
Global___TLSInfo: typing_extensions.TypeAlias = TLSInfo

@typing.final
class Source(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IP_ADDRESS_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    ip_address: builtins.str
    port: builtins.int

    def __init__(self, *, ip_address: builtins.str=..., port: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['ip_address', b'ip_address', 'port', b'port']) -> None:
        ...
Global___Source: typing_extensions.TypeAlias = Source

@typing.final
class InFlightRequests(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Request(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        API_KEY_FIELD_NUMBER: builtins.int
        IN_FLIGHT_DURATION_FIELD_NUMBER: builtins.int
        api_key: builtins.int
        'API key for the request type (e.g., produce/fetch/metadata/etc)\n        https://kafka.apache.org/0101/protocol.html#protocol_api_keys\n        '

        @property
        def in_flight_duration(self) -> google.protobuf.duration_pb2.Duration:
            """How long the request has been in-flight since it was received"""

        def __init__(self, *, api_key: builtins.int=..., in_flight_duration: google.protobuf.duration_pb2.Duration | None=...) -> None:
            ...

        def HasField(self, field_name: typing.Literal['in_flight_duration', b'in_flight_duration']) -> builtins.bool:
            ...

        def ClearField(self, field_name: typing.Literal['api_key', b'api_key', 'in_flight_duration', b'in_flight_duration']) -> None:
            ...
    SAMPLED_IN_FLIGHT_REQUESTS_FIELD_NUMBER: builtins.int
    HAS_MORE_REQUESTS_FIELD_NUMBER: builtins.int
    has_more_requests: builtins.bool
    'Whether there are more in-flight requests than those in\n    `sampled_in_flight_requests`.\n    '

    @property
    def sampled_in_flight_requests(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___InFlightRequests.Request]:
        """A sample (e.g., the 5 latest) of the currently in-flight requests"""

    def __init__(self, *, sampled_in_flight_requests: collections.abc.Iterable[Global___InFlightRequests.Request] | None=..., has_more_requests: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['has_more_requests', b'has_more_requests', 'sampled_in_flight_requests', b'sampled_in_flight_requests']) -> None:
        ...
Global___InFlightRequests: typing_extensions.TypeAlias = InFlightRequests

@typing.final
class RequestStatistics(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRODUCE_BYTES_FIELD_NUMBER: builtins.int
    FETCH_BYTES_FIELD_NUMBER: builtins.int
    REQUEST_COUNT_FIELD_NUMBER: builtins.int
    PRODUCE_BATCH_COUNT_FIELD_NUMBER: builtins.int
    produce_bytes: builtins.int
    'Sum of bytes produced.'
    fetch_bytes: builtins.int
    'Sum of bytes fetched.'
    request_count: builtins.int
    'Number of requests the client has made.'
    produce_batch_count: builtins.int
    'Number of produced batches.\n    Average batch size = produce_bytes / produce_batch_count\n    '

    def __init__(self, *, produce_bytes: builtins.int=..., fetch_bytes: builtins.int=..., request_count: builtins.int=..., produce_batch_count: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['fetch_bytes', b'fetch_bytes', 'produce_batch_count', b'produce_batch_count', 'produce_bytes', b'produce_bytes', 'request_count', b'request_count']) -> None:
        ...
Global___RequestStatistics: typing_extensions.TypeAlias = RequestStatistics