"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
from ...... import proto
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _TransformPartitionState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TransformPartitionStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TransformPartitionState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TRANSFORM_PARTITION_STATE_UNSPECIFIED: _TransformPartitionState.ValueType
    TRANSFORM_PARTITION_STATE_RUNNING: _TransformPartitionState.ValueType
    TRANSFORM_PARTITION_STATE_INACTIVE: _TransformPartitionState.ValueType
    TRANSFORM_PARTITION_STATE_ERRORED: _TransformPartitionState.ValueType
    TRANSFORM_PARTITION_STATE_UNKNOWN: _TransformPartitionState.ValueType

class TransformPartitionState(_TransformPartitionState, metaclass=_TransformPartitionStateEnumTypeWrapper):
    """TransformPartitionState enumerates the possible execution states for a
    transform partition.
    """
TRANSFORM_PARTITION_STATE_UNSPECIFIED: TransformPartitionState.ValueType
TRANSFORM_PARTITION_STATE_RUNNING: TransformPartitionState.ValueType
TRANSFORM_PARTITION_STATE_INACTIVE: TransformPartitionState.ValueType
TRANSFORM_PARTITION_STATE_ERRORED: TransformPartitionState.ValueType
TRANSFORM_PARTITION_STATE_UNKNOWN: TransformPartitionState.ValueType
Global___TransformPartitionState: typing_extensions.TypeAlias = TransformPartitionState

@typing.final
class Transform(google.protobuf.message.Message):
    """---- transforms resource messages ----

    Transform represents a deployed transform and its runtime status.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    INPUT_TOPIC_FIELD_NUMBER: builtins.int
    OUTPUT_TOPICS_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    COMPRESSION_FIELD_NUMBER: builtins.int
    IS_PAUSED_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    name: builtins.str
    'Human-readable name that uniquely identifies the transform.'
    input_topic: builtins.str
    'The input topic the transform consumes from.'
    compression: proto.redpanda.core.common.v1.compression_pb2.CompressionMode.ValueType
    'Output batch compression applied by the transform.'
    is_paused: builtins.bool
    'Whether the transform is paused (stopped but not removed).'

    @property
    def output_topics(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The output topics the transform writes to, in order."""

    @property
    def environment(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TransformEnvironmentVariable]:
        """Environment variables passed to the transform at runtime."""

    @property
    def status(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TransformPartitionStatus]:
        """Per-partition execution status aggregated across the cluster."""

    def __init__(self, *, name: builtins.str=..., input_topic: builtins.str=..., output_topics: collections.abc.Iterable[builtins.str] | None=..., environment: collections.abc.Iterable[Global___TransformEnvironmentVariable] | None=..., compression: proto.redpanda.core.common.v1.compression_pb2.CompressionMode.ValueType=..., is_paused: builtins.bool=..., status: collections.abc.Iterable[Global___TransformPartitionStatus] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['compression', b'compression', 'environment', b'environment', 'input_topic', b'input_topic', 'is_paused', b'is_paused', 'name', b'name', 'output_topics', b'output_topics', 'status', b'status']) -> None:
        ...
Global___Transform: typing_extensions.TypeAlias = Transform

@typing.final
class TransformEnvironmentVariable(google.protobuf.message.Message):
    """TransformEnvironmentVariable is a single key/value environment entry."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    value: builtins.str

    def __init__(self, *, key: builtins.str=..., value: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['key', b'key', 'value', b'value']) -> None:
        ...
Global___TransformEnvironmentVariable: typing_extensions.TypeAlias = TransformEnvironmentVariable

@typing.final
class TransformPartitionStatus(google.protobuf.message.Message):
    """TransformPartitionStatus describes the execution state of a transform on one
    partition.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NODE_ID_FIELD_NUMBER: builtins.int
    PARTITION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    LAG_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    'The broker that owns this partition.'
    partition: builtins.int
    'The partition index in the input topic.'
    status: Global___TransformPartitionState.ValueType
    'The current execution state.'
    lag: builtins.int
    'Number of records yet to be processed on this partition.'

    def __init__(self, *, node_id: builtins.int=..., partition: builtins.int=..., status: Global___TransformPartitionState.ValueType=..., lag: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['lag', b'lag', 'node_id', b'node_id', 'partition', b'partition', 'status', b'status']) -> None:
        ...
Global___TransformPartitionStatus: typing_extensions.TypeAlias = TransformPartitionStatus

@typing.final
class TransformConsumeOffset(google.protobuf.message.Message):
    """TransformConsumeOffset specifies where a transform begins consuming its
    input topic. If absent, the transform starts at the time of the
    CreateTransform call.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FROM_START_FIELD_NUMBER: builtins.int
    FROM_END_FIELD_NUMBER: builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: builtins.int
    from_start: builtins.int
    'Start this many records from the beginning of each partition.'
    from_end: builtins.int
    'Start this many records before the end of each partition.'
    timestamp_ms: builtins.int
    'Start at the record at or after this Unix timestamp (milliseconds).'

    def __init__(self, *, from_start: builtins.int=..., from_end: builtins.int=..., timestamp_ms: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['from_end', b'from_end', 'from_start', b'from_start', 'position', b'position', 'timestamp_ms', b'timestamp_ms']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['from_end', b'from_end', 'from_start', b'from_start', 'position', b'position', 'timestamp_ms', b'timestamp_ms']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['position', b'position']) -> typing.Literal['from_start', 'from_end', 'timestamp_ms'] | None:
        ...
Global___TransformConsumeOffset: typing_extensions.TypeAlias = TransformConsumeOffset

@typing.final
class CreateTransformRequest(google.protobuf.message.Message):
    """CreateTransformRequest creates or replaces a transform. The binary referenced
    by binary_id must exist (stored via CreateBinary).
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    INPUT_TOPIC_FIELD_NUMBER: builtins.int
    OUTPUT_TOPICS_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    COMPRESSION_FIELD_NUMBER: builtins.int
    CONSUME_OFFSET_FIELD_NUMBER: builtins.int
    BINARY_ID_FIELD_NUMBER: builtins.int
    name: builtins.str
    'Unique name for the transform.'
    input_topic: builtins.str
    'Input topic the transform consumes.'
    compression: proto.redpanda.core.common.v1.compression_pb2.CompressionMode.ValueType
    'Output compression mode. Defaults to COMPRESSION_MODE_NONE.'
    binary_id: builtins.str
    'Opaque identifier for the transform binary, as returned by CreateBinary.'

    @property
    def output_topics(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Output topics the transform produces to, in order."""

    @property
    def environment(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TransformEnvironmentVariable]:
        """Environment variables to expose to the transform."""

    @property
    def consume_offset(self) -> Global___TransformConsumeOffset:
        """Where to begin consuming the input topic.
        If absent, defaults to the current time of the CreateTransform call.
        """

    def __init__(self, *, name: builtins.str=..., input_topic: builtins.str=..., output_topics: collections.abc.Iterable[builtins.str] | None=..., environment: collections.abc.Iterable[Global___TransformEnvironmentVariable] | None=..., compression: proto.redpanda.core.common.v1.compression_pb2.CompressionMode.ValueType=..., consume_offset: Global___TransformConsumeOffset | None=..., binary_id: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['consume_offset', b'consume_offset']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['binary_id', b'binary_id', 'compression', b'compression', 'consume_offset', b'consume_offset', 'environment', b'environment', 'input_topic', b'input_topic', 'name', b'name', 'output_topics', b'output_topics']) -> None:
        ...
Global___CreateTransformRequest: typing_extensions.TypeAlias = CreateTransformRequest

@typing.final
class CreateTransformResponse(google.protobuf.message.Message):
    """CreateTransformResponse is returned on a successful CreateTransform."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___CreateTransformResponse: typing_extensions.TypeAlias = CreateTransformResponse

@typing.final
class GetTransformRequest(google.protobuf.message.Message):
    """GetTransformRequest identifies a transform by name."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str

    def __init__(self, *, name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name']) -> None:
        ...
Global___GetTransformRequest: typing_extensions.TypeAlias = GetTransformRequest

@typing.final
class GetTransformResponse(google.protobuf.message.Message):
    """GetTransformResponse returns the current state of a transform."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRANSFORM_FIELD_NUMBER: builtins.int

    @property
    def transform(self) -> Global___Transform:
        ...

    def __init__(self, *, transform: Global___Transform | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['transform', b'transform']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['transform', b'transform']) -> None:
        ...
Global___GetTransformResponse: typing_extensions.TypeAlias = GetTransformResponse

@typing.final
class ListTransformsRequest(google.protobuf.message.Message):
    """ListTransformsRequest has no required fields."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___ListTransformsRequest: typing_extensions.TypeAlias = ListTransformsRequest

@typing.final
class ListTransformsResponse(google.protobuf.message.Message):
    """ListTransformsResponse contains all transforms with their current status."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRANSFORMS_FIELD_NUMBER: builtins.int

    @property
    def transforms(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Transform]:
        ...

    def __init__(self, *, transforms: collections.abc.Iterable[Global___Transform] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['transforms', b'transforms']) -> None:
        ...
Global___ListTransformsResponse: typing_extensions.TypeAlias = ListTransformsResponse

@typing.final
class UpdateTransformRequest(google.protobuf.message.Message):
    """UpdateTransformRequest carries a partial metadata update for a transform.
    Fields not explicitly marked as present are left unchanged. Use
    CreateTransform to change the binary.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    ENVIRONMENT_FIELD_NUMBER: builtins.int
    HAS_ENVIRONMENT_FIELD_NUMBER: builtins.int
    IS_PAUSED_FIELD_NUMBER: builtins.int
    HAS_IS_PAUSED_FIELD_NUMBER: builtins.int
    COMPRESSION_FIELD_NUMBER: builtins.int
    HAS_COMPRESSION_FIELD_NUMBER: builtins.int
    name: builtins.str
    'Name of the transform to update.'
    has_environment: builtins.bool
    is_paused: builtins.bool
    "If has_is_paused is true, sets the transform's paused state."
    has_is_paused: builtins.bool
    compression: proto.redpanda.core.common.v1.compression_pb2.CompressionMode.ValueType
    'If has_compression is true, sets the output compression mode.'
    has_compression: builtins.bool

    @property
    def environment(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TransformEnvironmentVariable]:
        """If has_environment is true, replaces the transform's environment map
        wholesale.
        """

    def __init__(self, *, name: builtins.str=..., environment: collections.abc.Iterable[Global___TransformEnvironmentVariable] | None=..., has_environment: builtins.bool=..., is_paused: builtins.bool=..., has_is_paused: builtins.bool=..., compression: proto.redpanda.core.common.v1.compression_pb2.CompressionMode.ValueType=..., has_compression: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['compression', b'compression', 'environment', b'environment', 'has_compression', b'has_compression', 'has_environment', b'has_environment', 'has_is_paused', b'has_is_paused', 'is_paused', b'is_paused', 'name', b'name']) -> None:
        ...
Global___UpdateTransformRequest: typing_extensions.TypeAlias = UpdateTransformRequest

@typing.final
class UpdateTransformResponse(google.protobuf.message.Message):
    """UpdateTransformResponse is returned on a successful UpdateTransform."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___UpdateTransformResponse: typing_extensions.TypeAlias = UpdateTransformResponse

@typing.final
class DeleteTransformRequest(google.protobuf.message.Message):
    """DeleteTransformRequest identifies a transform to remove."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str

    def __init__(self, *, name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name']) -> None:
        ...
Global___DeleteTransformRequest: typing_extensions.TypeAlias = DeleteTransformRequest

@typing.final
class DeleteTransformResponse(google.protobuf.message.Message):
    """DeleteTransformResponse is returned on a successful DeleteTransform."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___DeleteTransformResponse: typing_extensions.TypeAlias = DeleteTransformResponse

@typing.final
class TransformBinary(google.protobuf.message.Message):
    """---- binaries resource messages ----

    TransformBinary represents a stored plugin binary and the transforms that
    reference it.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARY_ID_FIELD_NUMBER: builtins.int
    REFERENCED_BY_FIELD_NUMBER: builtins.int
    binary_id: builtins.str
    'Opaque identifier for the stored binary.'

    @property
    def referenced_by(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Names of transforms that currently reference this binary."""

    def __init__(self, *, binary_id: builtins.str=..., referenced_by: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['binary_id', b'binary_id', 'referenced_by', b'referenced_by']) -> None:
        ...
Global___TransformBinary: typing_extensions.TypeAlias = TransformBinary

@typing.final
class CreateBinaryRequest(google.protobuf.message.Message):
    """CreateBinaryRequest carries the raw binary to store."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARY_FIELD_NUMBER: builtins.int
    binary: builtins.bytes
    'The raw plugin binary (e.g. a WebAssembly module).'

    def __init__(self, *, binary: builtins.bytes=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['binary', b'binary']) -> None:
        ...
Global___CreateBinaryRequest: typing_extensions.TypeAlias = CreateBinaryRequest

@typing.final
class CreateBinaryResponse(google.protobuf.message.Message):
    """CreateBinaryResponse is returned when the binary has been validated and
    stored successfully.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARY_ID_FIELD_NUMBER: builtins.int
    binary_id: builtins.str
    'Opaque identifier for the stored binary. Pass this value as the\n    binary_id field in CreateTransformRequest.\n    '

    def __init__(self, *, binary_id: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['binary_id', b'binary_id']) -> None:
        ...
Global___CreateBinaryResponse: typing_extensions.TypeAlias = CreateBinaryResponse

@typing.final
class ListBinariesRequest(google.protobuf.message.Message):
    """ListBinariesRequest has no required fields."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___ListBinariesRequest: typing_extensions.TypeAlias = ListBinariesRequest

@typing.final
class ListBinariesResponse(google.protobuf.message.Message):
    """ListBinariesResponse contains all binaries referenced by active transforms."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARIES_FIELD_NUMBER: builtins.int

    @property
    def binaries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TransformBinary]:
        ...

    def __init__(self, *, binaries: collections.abc.Iterable[Global___TransformBinary] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['binaries', b'binaries']) -> None:
        ...
Global___ListBinariesResponse: typing_extensions.TypeAlias = ListBinariesResponse

@typing.final
class DeleteBinaryRequest(google.protobuf.message.Message):
    """DeleteBinaryRequest identifies a binary to remove."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BINARY_ID_FIELD_NUMBER: builtins.int
    binary_id: builtins.str

    def __init__(self, *, binary_id: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['binary_id', b'binary_id']) -> None:
        ...
Global___DeleteBinaryRequest: typing_extensions.TypeAlias = DeleteBinaryRequest

@typing.final
class DeleteBinaryResponse(google.protobuf.message.Message):
    """DeleteBinaryResponse is returned on a successful DeleteBinary."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___DeleteBinaryResponse: typing_extensions.TypeAlias = DeleteBinaryResponse