"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommittedOffset(google.protobuf.message.Message):
    """CommittedOffset records the last committed input-topic offset for a
    specific transform/partition pair.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRANSFORM_NAME_FIELD_NUMBER: builtins.int
    PARTITION_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    transform_name: builtins.str
    'Name of the transform.'
    partition: builtins.int
    'The input-topic partition.'
    offset: builtins.int
    'The committed offset within that partition.'

    def __init__(self, *, transform_name: builtins.str=..., partition: builtins.int=..., offset: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['offset', b'offset', 'partition', b'partition', 'transform_name', b'transform_name']) -> None:
        ...
Global___CommittedOffset: typing_extensions.TypeAlias = CommittedOffset

@typing.final
class ListCommittedOffsetsRequest(google.protobuf.message.Message):
    """ListCommittedOffsetsRequest controls which committed offsets to return."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHOW_UNKNOWN_FIELD_NUMBER: builtins.int
    show_unknown: builtins.bool
    'When true, also return offsets for partitions whose transform no longer\n    exists (orphaned offsets).\n    '

    def __init__(self, *, show_unknown: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['show_unknown', b'show_unknown']) -> None:
        ...
Global___ListCommittedOffsetsRequest: typing_extensions.TypeAlias = ListCommittedOffsetsRequest

@typing.final
class ListCommittedOffsetsResponse(google.protobuf.message.Message):
    """ListCommittedOffsetsResponse returns all matching committed offsets."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OFFSETS_FIELD_NUMBER: builtins.int

    @property
    def offsets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___CommittedOffset]:
        ...

    def __init__(self, *, offsets: collections.abc.Iterable[Global___CommittedOffset] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['offsets', b'offsets']) -> None:
        ...
Global___ListCommittedOffsetsResponse: typing_extensions.TypeAlias = ListCommittedOffsetsResponse

@typing.final
class GarbageCollectOffsetsRequest(google.protobuf.message.Message):
    """GarbageCollectOffsetsRequest has no required fields."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___GarbageCollectOffsetsRequest: typing_extensions.TypeAlias = GarbageCollectOffsetsRequest

@typing.final
class GarbageCollectOffsetsResponse(google.protobuf.message.Message):
    """GarbageCollectOffsetsResponse is returned on success."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___GarbageCollectOffsetsResponse: typing_extensions.TypeAlias = GarbageCollectOffsetsResponse