"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
from ...... import proto
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ShadowLinkState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ShadowLinkStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ShadowLinkState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SHADOW_LINK_STATE_UNSPECIFIED: _ShadowLinkState.ValueType
    'Unspecified'
    SHADOW_LINK_STATE_ACTIVE: _ShadowLinkState.ValueType
    'Shadow link is active'
    SHADOW_LINK_STATE_PAUSED: _ShadowLinkState.ValueType
    'Shadow link was paused'

class ShadowLinkState(_ShadowLinkState, metaclass=_ShadowLinkStateEnumTypeWrapper):
    """Enums

    State of the shadow link
    """
SHADOW_LINK_STATE_UNSPECIFIED: ShadowLinkState.ValueType
'Unspecified'
SHADOW_LINK_STATE_ACTIVE: ShadowLinkState.ValueType
'Shadow link is active'
SHADOW_LINK_STATE_PAUSED: ShadowLinkState.ValueType
'Shadow link was paused'
Global___ShadowLinkState: typing_extensions.TypeAlias = ShadowLinkState

class _ScramMechanism:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ScramMechanismEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ScramMechanism.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SCRAM_MECHANISM_UNSPECIFIED: _ScramMechanism.ValueType
    SCRAM_MECHANISM_SCRAM_SHA_256: _ScramMechanism.ValueType
    'SCRAM-SHA-256'
    SCRAM_MECHANISM_SCRAM_SHA_512: _ScramMechanism.ValueType
    'SCRAM-SHA-512'

class ScramMechanism(_ScramMechanism, metaclass=_ScramMechanismEnumTypeWrapper):
    """Valid SCRAM mechanisms"""
SCRAM_MECHANISM_UNSPECIFIED: ScramMechanism.ValueType
SCRAM_MECHANISM_SCRAM_SHA_256: ScramMechanism.ValueType
'SCRAM-SHA-256'
SCRAM_MECHANISM_SCRAM_SHA_512: ScramMechanism.ValueType
'SCRAM-SHA-512'
Global___ScramMechanism: typing_extensions.TypeAlias = ScramMechanism

class _PatternType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PatternTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PatternType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PATTERN_TYPE_UNSPECIFIED: _PatternType.ValueType
    PATTERN_TYPE_LITERAL: _PatternType.ValueType
    'Must match the filter exactly'
    PATTERN_TYPE_PREFIX: _PatternType.ValueType
    'Will match anything that starts with filter'
    PATTERN_TYPE_PREFIXED: _PatternType.ValueType
    'Will match anything that starts with filter'

class PatternType(_PatternType, metaclass=_PatternTypeEnumTypeWrapper):
    """The matching pattern type"""
PATTERN_TYPE_UNSPECIFIED: PatternType.ValueType
PATTERN_TYPE_LITERAL: PatternType.ValueType
'Must match the filter exactly'
PATTERN_TYPE_PREFIX: PatternType.ValueType
'Will match anything that starts with filter'
PATTERN_TYPE_PREFIXED: PatternType.ValueType
'Will match anything that starts with filter'
Global___PatternType: typing_extensions.TypeAlias = PatternType

class _FilterType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FilterTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FilterType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FILTER_TYPE_UNSPECIFIED: _FilterType.ValueType
    FILTER_TYPE_INCLUDE: _FilterType.ValueType
    'Include the items that match the filter'
    FILTER_TYPE_EXCLUDE: _FilterType.ValueType
    'Exclude the items that match the filter'

class FilterType(_FilterType, metaclass=_FilterTypeEnumTypeWrapper):
    """What type of filter this is, include or exclude"""
FILTER_TYPE_UNSPECIFIED: FilterType.ValueType
FILTER_TYPE_INCLUDE: FilterType.ValueType
'Include the items that match the filter'
FILTER_TYPE_EXCLUDE: FilterType.ValueType
'Exclude the items that match the filter'
Global___FilterType: typing_extensions.TypeAlias = FilterType

class _TaskState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _TaskStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TASK_STATE_UNSPECIFIED: _TaskState.ValueType
    TASK_STATE_ACTIVE: _TaskState.ValueType
    'Task is active'
    TASK_STATE_PAUSED: _TaskState.ValueType
    'Task was paused'
    TASK_STATE_LINK_UNAVAILABLE: _TaskState.ValueType
    'Task is unable to communicate with source cluster'
    TASK_STATE_NOT_RUNNING: _TaskState.ValueType
    'Task is not running'
    TASK_STATE_FAULTED: _TaskState.ValueType
    'Task is faulted'

class TaskState(_TaskState, metaclass=_TaskStateEnumTypeWrapper):
    """Task states"""
TASK_STATE_UNSPECIFIED: TaskState.ValueType
TASK_STATE_ACTIVE: TaskState.ValueType
'Task is active'
TASK_STATE_PAUSED: TaskState.ValueType
'Task was paused'
TASK_STATE_LINK_UNAVAILABLE: TaskState.ValueType
'Task is unable to communicate with source cluster'
TASK_STATE_NOT_RUNNING: TaskState.ValueType
'Task is not running'
TASK_STATE_FAULTED: TaskState.ValueType
'Task is faulted'
Global___TaskState: typing_extensions.TypeAlias = TaskState

class _SchemaRegistrySyncType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchemaRegistrySyncTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchemaRegistrySyncType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SCHEMA_REGISTRY_SYNC_TYPE_UNSPECIFIED: _SchemaRegistrySyncType.ValueType
    'The Schema Registry sync type is not specified.'
    SCHEMA_REGISTRY_SYNC_TYPE_FULL: _SchemaRegistrySyncType.ValueType
    'A full source scan is running.'
    SCHEMA_REGISTRY_SYNC_TYPE_TAIL: _SchemaRegistrySyncType.ValueType
    'An incremental tail sync is running.'

class SchemaRegistrySyncType(_SchemaRegistrySyncType, metaclass=_SchemaRegistrySyncTypeEnumTypeWrapper):
    """Type of Schema Registry sync currently running."""
SCHEMA_REGISTRY_SYNC_TYPE_UNSPECIFIED: SchemaRegistrySyncType.ValueType
'The Schema Registry sync type is not specified.'
SCHEMA_REGISTRY_SYNC_TYPE_FULL: SchemaRegistrySyncType.ValueType
'A full source scan is running.'
SCHEMA_REGISTRY_SYNC_TYPE_TAIL: SchemaRegistrySyncType.ValueType
'An incremental tail sync is running.'
Global___SchemaRegistrySyncType: typing_extensions.TypeAlias = SchemaRegistrySyncType

class _UnsupportedSchemaFeaturePolicy:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _UnsupportedSchemaFeaturePolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UnsupportedSchemaFeaturePolicy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSUPPORTED_SCHEMA_FEATURE_POLICY_UNSPECIFIED: _UnsupportedSchemaFeaturePolicy.ValueType
    'Use the default unsupported schema feature handling behavior.'
    UNSUPPORTED_SCHEMA_FEATURE_POLICY_FAIL: _UnsupportedSchemaFeaturePolicy.ValueType
    'Fail the sync when an unsupported schema feature is encountered.'
    UNSUPPORTED_SCHEMA_FEATURE_POLICY_REMOVE: _UnsupportedSchemaFeaturePolicy.ValueType
    'Remove unsupported schema features before writing to the destination.'

class UnsupportedSchemaFeaturePolicy(_UnsupportedSchemaFeaturePolicy, metaclass=_UnsupportedSchemaFeaturePolicyEnumTypeWrapper):
    """Policy for handling source schema features unsupported by the destination."""
UNSUPPORTED_SCHEMA_FEATURE_POLICY_UNSPECIFIED: UnsupportedSchemaFeaturePolicy.ValueType
'Use the default unsupported schema feature handling behavior.'
UNSUPPORTED_SCHEMA_FEATURE_POLICY_FAIL: UnsupportedSchemaFeaturePolicy.ValueType
'Fail the sync when an unsupported schema feature is encountered.'
UNSUPPORTED_SCHEMA_FEATURE_POLICY_REMOVE: UnsupportedSchemaFeaturePolicy.ValueType
'Remove unsupported schema features before writing to the destination.'
Global___UnsupportedSchemaFeaturePolicy: typing_extensions.TypeAlias = UnsupportedSchemaFeaturePolicy

class _ShadowTopicState:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ShadowTopicStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ShadowTopicState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SHADOW_TOPIC_STATE_UNSPECIFIED: _ShadowTopicState.ValueType
    SHADOW_TOPIC_STATE_ACTIVE: _ShadowTopicState.ValueType
    'Shadow topic is active'
    SHADOW_TOPIC_STATE_FAULTED: _ShadowTopicState.ValueType
    'Shadow topic has faulted'
    SHADOW_TOPIC_STATE_PAUSED: _ShadowTopicState.ValueType
    'Shadow topic has been paused'
    SHADOW_TOPIC_STATE_FAILING_OVER: _ShadowTopicState.ValueType
    'Shadow topic is in the process of failing over'
    SHADOW_TOPIC_STATE_FAILED_OVER: _ShadowTopicState.ValueType
    'Shadow topic has failed over successfully'
    SHADOW_TOPIC_STATE_PROMOTING: _ShadowTopicState.ValueType
    'Shadow topic is in the process of being promoted'
    SHADOW_TOPIC_STATE_PROMOTED: _ShadowTopicState.ValueType
    'Shadow topic is promoted successfully'

class ShadowTopicState(_ShadowTopicState, metaclass=_ShadowTopicStateEnumTypeWrapper):
    """State of a shadow topic"""
SHADOW_TOPIC_STATE_UNSPECIFIED: ShadowTopicState.ValueType
SHADOW_TOPIC_STATE_ACTIVE: ShadowTopicState.ValueType
'Shadow topic is active'
SHADOW_TOPIC_STATE_FAULTED: ShadowTopicState.ValueType
'Shadow topic has faulted'
SHADOW_TOPIC_STATE_PAUSED: ShadowTopicState.ValueType
'Shadow topic has been paused'
SHADOW_TOPIC_STATE_FAILING_OVER: ShadowTopicState.ValueType
'Shadow topic is in the process of failing over'
SHADOW_TOPIC_STATE_FAILED_OVER: ShadowTopicState.ValueType
'Shadow topic has failed over successfully'
SHADOW_TOPIC_STATE_PROMOTING: ShadowTopicState.ValueType
'Shadow topic is in the process of being promoted'
SHADOW_TOPIC_STATE_PROMOTED: ShadowTopicState.ValueType
'Shadow topic is promoted successfully'
Global___ShadowTopicState: typing_extensions.TypeAlias = ShadowTopicState

@typing.final
class ShadowLink(google.protobuf.message.Message):
    """Resources

    A ShadowLink resource
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    UID_FIELD_NUMBER: builtins.int
    CONFIGURATIONS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    name: builtins.str
    'The name of the shadow link'
    uid: builtins.str
    'The UUID of the shadow link'

    @property
    def configurations(self) -> Global___ShadowLinkConfigurations:
        """Shadow link configuration"""

    @property
    def status(self) -> Global___ShadowLinkStatus:
        """Status of the shadow link"""

    def __init__(self, *, name: builtins.str=..., uid: builtins.str=..., configurations: Global___ShadowLinkConfigurations | None=..., status: Global___ShadowLinkStatus | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['configurations', b'configurations', 'status', b'status']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['configurations', b'configurations', 'name', b'name', 'status', b'status', 'uid', b'uid']) -> None:
        ...
Global___ShadowLink: typing_extensions.TypeAlias = ShadowLink

@typing.final
class ShadowTopic(google.protobuf.message.Message):
    """A ShadowTopic resource contained by the ShadowLink"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    TOPIC_ID_FIELD_NUMBER: builtins.int
    SOURCE_TOPIC_NAME_FIELD_NUMBER: builtins.int
    SOURCE_TOPIC_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    name: builtins.str
    'Name of the shadow topic'
    topic_id: builtins.str
    'The topic ID of the shadow topic'
    source_topic_name: builtins.str
    'The name of the source topic'
    source_topic_id: builtins.str
    'The topic ID of the source topic'

    @property
    def status(self) -> Global___ShadowTopicStatus:
        """The status of the shadow topic"""

    def __init__(self, *, name: builtins.str=..., topic_id: builtins.str=..., source_topic_name: builtins.str=..., source_topic_id: builtins.str=..., status: Global___ShadowTopicStatus | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['status', b'status']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name', 'source_topic_id', b'source_topic_id', 'source_topic_name', b'source_topic_name', 'status', b'status', 'topic_id', b'topic_id']) -> None:
        ...
Global___ShadowTopic: typing_extensions.TypeAlias = ShadowTopic

@typing.final
class CreateShadowLinkRequest(google.protobuf.message.Message):
    """RPC Requests and Responses

    Create a new shadow link
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINK_FIELD_NUMBER: builtins.int
    VALIDATE_ONLY_FIELD_NUMBER: builtins.int
    validate_only: builtins.bool
    'If true, validate connection parameters without creating the link.\n    Returns an empty response on success or an error if validation fails.\n    '

    @property
    def shadow_link(self) -> Global___ShadowLink:
        """The shadow link to create"""

    def __init__(self, *, shadow_link: Global___ShadowLink | None=..., validate_only: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_link', b'shadow_link', 'validate_only', b'validate_only']) -> None:
        ...
Global___CreateShadowLinkRequest: typing_extensions.TypeAlias = CreateShadowLinkRequest

@typing.final
class CreateShadowLinkResponse(google.protobuf.message.Message):
    """Response to creating a shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINK_FIELD_NUMBER: builtins.int

    @property
    def shadow_link(self) -> Global___ShadowLink:
        """The shadow link that was created"""

    def __init__(self, *, shadow_link: Global___ShadowLink | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> None:
        ...
Global___CreateShadowLinkResponse: typing_extensions.TypeAlias = CreateShadowLinkResponse

@typing.final
class DeleteShadowLinkRequest(google.protobuf.message.Message):
    """Request to delete a shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    FORCE_FIELD_NUMBER: builtins.int
    name: builtins.str
    'The name of the link to delete'
    force: builtins.bool
    "By default, DeleteShadowLink will fail if there are any active Shadow\n    Topics.  Set this flag to 'true' if you wish to delete the link while\n    there are active shadow topics.\n    "

    def __init__(self, *, name: builtins.str=..., force: builtins.bool=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['force', b'force', 'name', b'name']) -> None:
        ...
Global___DeleteShadowLinkRequest: typing_extensions.TypeAlias = DeleteShadowLinkRequest

@typing.final
class DeleteShadowLinkResponse(google.protobuf.message.Message):
    """Response to deleting a shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___DeleteShadowLinkResponse: typing_extensions.TypeAlias = DeleteShadowLinkResponse

@typing.final
class GetShadowLinkRequest(google.protobuf.message.Message):
    """Request to get the information about a shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    'The name of the shadow link to get'

    def __init__(self, *, name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name']) -> None:
        ...
Global___GetShadowLinkRequest: typing_extensions.TypeAlias = GetShadowLinkRequest

@typing.final
class GetShadowLinkResponse(google.protobuf.message.Message):
    """Response to getting a shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINK_FIELD_NUMBER: builtins.int

    @property
    def shadow_link(self) -> Global___ShadowLink:
        """The shadow link that was retrieved"""

    def __init__(self, *, shadow_link: Global___ShadowLink | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> None:
        ...
Global___GetShadowLinkResponse: typing_extensions.TypeAlias = GetShadowLinkResponse

@typing.final
class ListShadowLinksRequest(google.protobuf.message.Message):
    """Request to list all shadow links"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___ListShadowLinksRequest: typing_extensions.TypeAlias = ListShadowLinksRequest

@typing.final
class ListShadowLinksResponse(google.protobuf.message.Message):
    """All shadow links on the cluster"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINKS_FIELD_NUMBER: builtins.int

    @property
    def shadow_links(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ShadowLink]:
        """The shadow links"""

    def __init__(self, *, shadow_links: collections.abc.Iterable[Global___ShadowLink] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_links', b'shadow_links']) -> None:
        ...
Global___ListShadowLinksResponse: typing_extensions.TypeAlias = ListShadowLinksResponse

@typing.final
class UpdateShadowLinkRequest(google.protobuf.message.Message):
    """Updates a shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINK_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int

    @property
    def shadow_link(self) -> Global___ShadowLink:
        """The shadow link to update"""

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """The list of fields to update
        See [AIP-134](https://google.aip.dev/134) for how to use `field_mask`
        """

    def __init__(self, *, shadow_link: Global___ShadowLink | None=..., update_mask: google.protobuf.field_mask_pb2.FieldMask | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['shadow_link', b'shadow_link', 'update_mask', b'update_mask']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_link', b'shadow_link', 'update_mask', b'update_mask']) -> None:
        ...
Global___UpdateShadowLinkRequest: typing_extensions.TypeAlias = UpdateShadowLinkRequest

@typing.final
class UpdateShadowLinkResponse(google.protobuf.message.Message):
    """Response to the update shadow link request"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINK_FIELD_NUMBER: builtins.int

    @property
    def shadow_link(self) -> Global___ShadowLink:
        """The shadow link that was updated"""

    def __init__(self, *, shadow_link: Global___ShadowLink | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> None:
        ...
Global___UpdateShadowLinkResponse: typing_extensions.TypeAlias = UpdateShadowLinkResponse

@typing.final
class FailOverRequest(google.protobuf.message.Message):
    """Request to fail over a shadow link or a single shadow topic"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SHADOW_TOPIC_NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    'The name of the shadow link to fail over'
    shadow_topic_name: builtins.str
    'The name of the shadow topic to fail over, if not set will fail over\n    the entire shadow link\n    '

    def __init__(self, *, name: builtins.str=..., shadow_topic_name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name', 'shadow_topic_name', b'shadow_topic_name']) -> None:
        ...
Global___FailOverRequest: typing_extensions.TypeAlias = FailOverRequest

@typing.final
class FailOverResponse(google.protobuf.message.Message):
    """The response to the FailOverRequest"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINK_FIELD_NUMBER: builtins.int

    @property
    def shadow_link(self) -> Global___ShadowLink:
        """The shadow link that was failed over"""

    def __init__(self, *, shadow_link: Global___ShadowLink | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_link', b'shadow_link']) -> None:
        ...
Global___FailOverResponse: typing_extensions.TypeAlias = FailOverResponse

@typing.final
class GetShadowTopicRequest(google.protobuf.message.Message):
    """Request to get a shadow topic"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINK_NAME_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    shadow_link_name: builtins.str
    'The name of the shadow link the topic is contained in'
    name: builtins.str
    'The name of the shadow topic to get'

    def __init__(self, *, shadow_link_name: builtins.str=..., name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name', 'shadow_link_name', b'shadow_link_name']) -> None:
        ...
Global___GetShadowTopicRequest: typing_extensions.TypeAlias = GetShadowTopicRequest

@typing.final
class GetShadowTopicResponse(google.protobuf.message.Message):
    """Response of to getting a shadow topic"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_TOPIC_FIELD_NUMBER: builtins.int

    @property
    def shadow_topic(self) -> Global___ShadowTopic:
        ...

    def __init__(self, *, shadow_topic: Global___ShadowTopic | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['shadow_topic', b'shadow_topic']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_topic', b'shadow_topic']) -> None:
        ...
Global___GetShadowTopicResponse: typing_extensions.TypeAlias = GetShadowTopicResponse

@typing.final
class ListShadowTopicsRequest(google.protobuf.message.Message):
    """Request to list all shadow topics in a shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_LINK_NAME_FIELD_NUMBER: builtins.int
    shadow_link_name: builtins.str

    def __init__(self, *, shadow_link_name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_link_name', b'shadow_link_name']) -> None:
        ...
Global___ListShadowTopicsRequest: typing_extensions.TypeAlias = ListShadowTopicsRequest

@typing.final
class ListShadowTopicsResponse(google.protobuf.message.Message):
    """Response to listing all shadow topics in a shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SHADOW_TOPICS_FIELD_NUMBER: builtins.int

    @property
    def shadow_topics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ShadowTopic]:
        ...

    def __init__(self, *, shadow_topics: collections.abc.Iterable[Global___ShadowTopic] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['shadow_topics', b'shadow_topics']) -> None:
        ...
Global___ListShadowTopicsResponse: typing_extensions.TypeAlias = ListShadowTopicsResponse

@typing.final
class ShadowLinkConfigurations(google.protobuf.message.Message):
    """Other Messages

    ShadowLink options
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CLIENT_OPTIONS_FIELD_NUMBER: builtins.int
    TOPIC_METADATA_SYNC_OPTIONS_FIELD_NUMBER: builtins.int
    CONSUMER_OFFSET_SYNC_OPTIONS_FIELD_NUMBER: builtins.int
    SECURITY_SYNC_OPTIONS_FIELD_NUMBER: builtins.int
    SCHEMA_REGISTRY_SYNC_OPTIONS_FIELD_NUMBER: builtins.int
    ROLE_SYNC_OPTIONS_FIELD_NUMBER: builtins.int

    @property
    def client_options(self) -> Global___ShadowLinkClientOptions:
        """Configuration for the internal kafka client"""

    @property
    def topic_metadata_sync_options(self) -> Global___TopicMetadataSyncOptions:
        """Topic metadata sync options"""

    @property
    def consumer_offset_sync_options(self) -> Global___ConsumerOffsetSyncOptions:
        """Consumer offset sync options"""

    @property
    def security_sync_options(self) -> Global___SecuritySettingsSyncOptions:
        """Security settings sync options"""

    @property
    def schema_registry_sync_options(self) -> Global___SchemaRegistrySyncOptions:
        """Schema Registry sync options"""

    @property
    def role_sync_options(self) -> Global___RoleSyncOptions:
        """Role sync options"""

    def __init__(self, *, client_options: Global___ShadowLinkClientOptions | None=..., topic_metadata_sync_options: Global___TopicMetadataSyncOptions | None=..., consumer_offset_sync_options: Global___ConsumerOffsetSyncOptions | None=..., security_sync_options: Global___SecuritySettingsSyncOptions | None=..., schema_registry_sync_options: Global___SchemaRegistrySyncOptions | None=..., role_sync_options: Global___RoleSyncOptions | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['client_options', b'client_options', 'consumer_offset_sync_options', b'consumer_offset_sync_options', 'role_sync_options', b'role_sync_options', 'schema_registry_sync_options', b'schema_registry_sync_options', 'security_sync_options', b'security_sync_options', 'topic_metadata_sync_options', b'topic_metadata_sync_options']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['client_options', b'client_options', 'consumer_offset_sync_options', b'consumer_offset_sync_options', 'role_sync_options', b'role_sync_options', 'schema_registry_sync_options', b'schema_registry_sync_options', 'security_sync_options', b'security_sync_options', 'topic_metadata_sync_options', b'topic_metadata_sync_options']) -> None:
        ...
Global___ShadowLinkConfigurations: typing_extensions.TypeAlias = ShadowLinkConfigurations

@typing.final
class ShadowLinkClientOptions(google.protobuf.message.Message):
    """Options for the client link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BOOTSTRAP_SERVERS_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    SOURCE_CLUSTER_ID_FIELD_NUMBER: builtins.int
    TLS_SETTINGS_FIELD_NUMBER: builtins.int
    AUTHENTICATION_CONFIGURATION_FIELD_NUMBER: builtins.int
    METADATA_MAX_AGE_MS_FIELD_NUMBER: builtins.int
    EFFECTIVE_METADATA_MAX_AGE_MS_FIELD_NUMBER: builtins.int
    CONNECTION_TIMEOUT_MS_FIELD_NUMBER: builtins.int
    EFFECTIVE_CONNECTION_TIMEOUT_MS_FIELD_NUMBER: builtins.int
    RETRY_BACKOFF_MS_FIELD_NUMBER: builtins.int
    EFFECTIVE_RETRY_BACKOFF_MS_FIELD_NUMBER: builtins.int
    FETCH_WAIT_MAX_MS_FIELD_NUMBER: builtins.int
    EFFECTIVE_FETCH_WAIT_MAX_MS_FIELD_NUMBER: builtins.int
    FETCH_MIN_BYTES_FIELD_NUMBER: builtins.int
    EFFECTIVE_FETCH_MIN_BYTES_FIELD_NUMBER: builtins.int
    FETCH_MAX_BYTES_FIELD_NUMBER: builtins.int
    EFFECTIVE_FETCH_MAX_BYTES_FIELD_NUMBER: builtins.int
    FETCH_PARTITION_MAX_BYTES_FIELD_NUMBER: builtins.int
    EFFECTIVE_FETCH_PARTITION_MAX_BYTES_FIELD_NUMBER: builtins.int
    client_id: builtins.str
    'The Client ID for the Kafka RPC requests setn by this cluster to the\n    source cluster\n    '
    source_cluster_id: builtins.str
    'If provided, this is the expected ID of the source cluster.  If it does\n    not match then the connection will be rejected.  If provided, this value\n    must match the `ClusterId` field returned in the Kafka Metadata response\n    message\n    '
    metadata_max_age_ms: builtins.int
    'Max metadata age.\n    If 0 is provided, defaults to 10 seconds\n    '
    effective_metadata_max_age_ms: builtins.int
    'The effective metadata max age in milliseconds'
    connection_timeout_ms: builtins.int
    'Connection timeout.\n    If 0 is provided, defaults to 1 second\n    '
    effective_connection_timeout_ms: builtins.int
    'The effective connection timeout in milliseconds'
    retry_backoff_ms: builtins.int
    'Retry base backoff.\n    If 0 is provided, defaults to 100ms\n    '
    effective_retry_backoff_ms: builtins.int
    'The effective retry backoff in milliseconds'
    fetch_wait_max_ms: builtins.int
    'Fetch request timeout.\n    If 0 is provided, defaults to 500ms\n    '
    effective_fetch_wait_max_ms: builtins.int
    'The effective fetch wait max in milliseconds'
    fetch_min_bytes: builtins.int
    'Fetch min bytes.\n    If 0 is provided, defaults to 5 MiB\n    '
    effective_fetch_min_bytes: builtins.int
    'The effective fetch min bytes'
    fetch_max_bytes: builtins.int
    'Fetch max bytes.\n    If 0 is provided, defaults to 20 MiB\n    '
    effective_fetch_max_bytes: builtins.int
    'The effective fetch max bytes'
    fetch_partition_max_bytes: builtins.int
    'Fetch partition max bytes.\n    If 0 is provided, defaults to 5 MiB\n    '
    effective_fetch_partition_max_bytes: builtins.int
    'The effective fetch partition max bytes'

    @property
    def bootstrap_servers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The bootstrap servers to use"""

    @property
    def tls_settings(self) -> proto.redpanda.core.common.v1.tls_pb2.TLSSettings:
        """TLS settings"""

    @property
    def authentication_configuration(self) -> Global___AuthenticationConfiguration:
        """Authentication settings"""

    def __init__(self, *, bootstrap_servers: collections.abc.Iterable[builtins.str] | None=..., client_id: builtins.str=..., source_cluster_id: builtins.str=..., tls_settings: proto.redpanda.core.common.v1.tls_pb2.TLSSettings | None=..., authentication_configuration: Global___AuthenticationConfiguration | None=..., metadata_max_age_ms: builtins.int=..., effective_metadata_max_age_ms: builtins.int=..., connection_timeout_ms: builtins.int=..., effective_connection_timeout_ms: builtins.int=..., retry_backoff_ms: builtins.int=..., effective_retry_backoff_ms: builtins.int=..., fetch_wait_max_ms: builtins.int=..., effective_fetch_wait_max_ms: builtins.int=..., fetch_min_bytes: builtins.int=..., effective_fetch_min_bytes: builtins.int=..., fetch_max_bytes: builtins.int=..., effective_fetch_max_bytes: builtins.int=..., fetch_partition_max_bytes: builtins.int=..., effective_fetch_partition_max_bytes: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['_authentication_configuration', b'_authentication_configuration', '_tls_settings', b'_tls_settings', 'authentication_configuration', b'authentication_configuration', 'tls_settings', b'tls_settings']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['_authentication_configuration', b'_authentication_configuration', '_tls_settings', b'_tls_settings', 'authentication_configuration', b'authentication_configuration', 'bootstrap_servers', b'bootstrap_servers', 'client_id', b'client_id', 'connection_timeout_ms', b'connection_timeout_ms', 'effective_connection_timeout_ms', b'effective_connection_timeout_ms', 'effective_fetch_max_bytes', b'effective_fetch_max_bytes', 'effective_fetch_min_bytes', b'effective_fetch_min_bytes', 'effective_fetch_partition_max_bytes', b'effective_fetch_partition_max_bytes', 'effective_fetch_wait_max_ms', b'effective_fetch_wait_max_ms', 'effective_metadata_max_age_ms', b'effective_metadata_max_age_ms', 'effective_retry_backoff_ms', b'effective_retry_backoff_ms', 'fetch_max_bytes', b'fetch_max_bytes', 'fetch_min_bytes', b'fetch_min_bytes', 'fetch_partition_max_bytes', b'fetch_partition_max_bytes', 'fetch_wait_max_ms', b'fetch_wait_max_ms', 'metadata_max_age_ms', b'metadata_max_age_ms', 'retry_backoff_ms', b'retry_backoff_ms', 'source_cluster_id', b'source_cluster_id', 'tls_settings', b'tls_settings']) -> None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_authentication_configuration', b'_authentication_configuration']) -> typing.Literal['authentication_configuration'] | None:
        ...

    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal['_tls_settings', b'_tls_settings']) -> typing.Literal['tls_settings'] | None:
        ...
Global___ShadowLinkClientOptions: typing_extensions.TypeAlias = ShadowLinkClientOptions

@typing.final
class TopicMetadataSyncOptions(google.protobuf.message.Message):
    """Options for syncing topic metadata"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class EarliestOffset(google.protobuf.message.Message):
        """Start at the earliest offset in the partition."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(self) -> None:
            ...

    @typing.final
    class LatestOffset(google.protobuf.message.Message):
        """Start at the latest offset in the partition."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(self) -> None:
            ...
    INTERVAL_FIELD_NUMBER: builtins.int
    EFFECTIVE_INTERVAL_FIELD_NUMBER: builtins.int
    AUTO_CREATE_SHADOW_TOPIC_FILTERS_FIELD_NUMBER: builtins.int
    SYNCED_SHADOW_TOPIC_PROPERTIES_FIELD_NUMBER: builtins.int
    EXCLUDE_DEFAULT_FIELD_NUMBER: builtins.int
    START_AT_EARLIEST_FIELD_NUMBER: builtins.int
    START_AT_LATEST_FIELD_NUMBER: builtins.int
    START_AT_TIMESTAMP_FIELD_NUMBER: builtins.int
    PAUSED_FIELD_NUMBER: builtins.int
    exclude_default: builtins.bool
    'If false, then the following topic properties will be synced by default:\n    - `compression.type`\n    - `retention.bytes`\n    - `retention.ms`\n    - `delete.retention.ms`\n    - Replication Factor\n    - `min.compaction.lag.ms`\n    - `max.compaction.lag.ms`\n\n    If this is true, then only the properties listed in\n    `synced_shadow_topic_properties` will be synced.\n    '
    paused: builtins.bool
    "Allows user to pause the topic sync task.  If paused, then\n    the task will enter the 'paused' state and not sync topics or their\n    properties from the source cluster\n    "

    @property
    def interval(self) -> google.protobuf.duration_pb2.Duration:
        """How often to sync metadata
        If 0 provided, defaults to 30 seconds
        """

    @property
    def effective_interval(self) -> google.protobuf.duration_pb2.Duration:
        """The effective interval for the task"""

    @property
    def auto_create_shadow_topic_filters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NameFilter]:
        """List of filters that indicate which topics should be automatically
        created as shadow topics on the shadow cluster.  This only controls
        automatic creation of shadow topics and does not effect the state of the
        mirror topic once it is created.
        Literal filters for __consumer_offsets, _redpanda.audit_log and _schemas
        will be rejected as well as prefix filters to match topics prefixed with
        _redpanda or __redpanda.
        Wildcard `*` is permitted only for literal filters and will _not_ match
        any topics that start with _redpanda or __redpanda.  If users wish to
        shadow topics that start with _redpanda or __redpanda, they should
        provide a literal filter for those topics.
        """

    @property
    def synced_shadow_topic_properties(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of topic properties that should be synced from the source topic.
        The following properties will always be replicated
        - Partition count
        - `max.message.bytes`
        - `cleanup.policy`
        - `timestamp.type`

        The following properties are not allowed to be replicated and adding them
        to this list will result in an error:
        - `redpanda.remote.readreplica`
        - `redpanda.remote.recovery`
        - `redpanda.remote.allowgaps`
        - `redpanda.virtual.cluster.id`
        - `redpanda.leaders.preference`
        - `redpanda.storage.mode`

        This list is a list of properties in addition to the default properties
        that will be synced.  See `exclude_default`.
        """

    @property
    def start_at_earliest(self) -> Global___TopicMetadataSyncOptions.EarliestOffset:
        """Enables data replication from the earliest offset
        on the source topic/partition.
        """

    @property
    def start_at_latest(self) -> Global___TopicMetadataSyncOptions.LatestOffset:
        """Enables data replication from the latest offset
        on the source topic/partition.
        """

    @property
    def start_at_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Enables data replication from the first offset on the
        source topic/partition where the record's timestamp is
        at or after the specified timestamp.
        """

    def __init__(self, *, interval: google.protobuf.duration_pb2.Duration | None=..., effective_interval: google.protobuf.duration_pb2.Duration | None=..., auto_create_shadow_topic_filters: collections.abc.Iterable[Global___NameFilter] | None=..., synced_shadow_topic_properties: collections.abc.Iterable[builtins.str] | None=..., exclude_default: builtins.bool=..., start_at_earliest: Global___TopicMetadataSyncOptions.EarliestOffset | None=..., start_at_latest: Global___TopicMetadataSyncOptions.LatestOffset | None=..., start_at_timestamp: google.protobuf.timestamp_pb2.Timestamp | None=..., paused: builtins.bool=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['effective_interval', b'effective_interval', 'interval', b'interval', 'start_at_earliest', b'start_at_earliest', 'start_at_latest', b'start_at_latest', 'start_at_timestamp', b'start_at_timestamp', 'start_offset', b'start_offset']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['auto_create_shadow_topic_filters', b'auto_create_shadow_topic_filters', 'effective_interval', b'effective_interval', 'exclude_default', b'exclude_default', 'interval', b'interval', 'paused', b'paused', 'start_at_earliest', b'start_at_earliest', 'start_at_latest', b'start_at_latest', 'start_at_timestamp', b'start_at_timestamp', 'start_offset', b'start_offset', 'synced_shadow_topic_properties', b'synced_shadow_topic_properties']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['start_offset', b'start_offset']) -> typing.Literal['start_at_earliest', 'start_at_latest', 'start_at_timestamp'] | None:
        ...
Global___TopicMetadataSyncOptions: typing_extensions.TypeAlias = TopicMetadataSyncOptions

@typing.final
class SchemaRegistrySyncOptions(google.protobuf.message.Message):
    """Options for how the Schema Registry is synced."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ShadowSchemaRegistryTopic(google.protobuf.message.Message):
        """Shadow the entire source cluster's Schema Registry byte-for-byte.
        If set, the Shadow Link will attempt to add the `_schemas`
        topic to the list of Shadow Topics as long as:
        1. The `_schemas` topic exists on the source cluster
        2. The `_schemas` topic does not exist on the shadow cluster, or it is
        empty.
        If either of the above conditions are _not_ met, then the `_schemas`
        topic will _not_ be shadowed by this cluster. Unsetting this flag will
        _not_ remove the `_schemas` topic from shadowing if it has already been
        added.  Once made a shadow topic, the
        `_schemas` topic will be replicated byte-for-byte.  To stop shadowing the
        `_schemas` topic, unset this field, then either fail-over the topic or
        delete it.
        """
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(self) -> None:
            ...

    @typing.final
    class ShadowSchemaRegistryApi(google.protobuf.message.Message):
        """Replicates selected Schema Registry subjects, configs, modes, and schema
        IDs over the Schema Registry HTTP API.
        """
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SOURCE_URL_FIELD_NUMBER: builtins.int
        AUTH_OPTIONS_FIELD_NUMBER: builtins.int
        TLS_SETTINGS_FIELD_NUMBER: builtins.int
        TAIL_INTERVAL_FIELD_NUMBER: builtins.int
        EFFECTIVE_TAIL_INTERVAL_FIELD_NUMBER: builtins.int
        FULL_SYNC_INTERVAL_FIELD_NUMBER: builtins.int
        EFFECTIVE_FULL_SYNC_INTERVAL_FIELD_NUMBER: builtins.int
        MAX_SOURCE_REQUESTS_PER_SECOND_FIELD_NUMBER: builtins.int
        EFFECTIVE_MAX_SOURCE_REQUESTS_PER_SECOND_FIELD_NUMBER: builtins.int
        SOURCE_FILTER_FIELD_NUMBER: builtins.int
        DESTINATION_FIELD_NUMBER: builtins.int
        UNSUPPORTED_SCHEMA_FEATURE_POLICY_FIELD_NUMBER: builtins.int
        source_url: builtins.str
        'The source Schema Registry URL to use.'
        max_source_requests_per_second: builtins.int
        'Maximum request rate, in requests per second, for calls to the source\n        Schema Registry. If unset or zero, a default rate limit of 30\n        requests/s is used.\n        '
        effective_max_source_requests_per_second: builtins.int
        'The effective maximum request rate, in requests per second.'
        unsupported_schema_feature_policy: Global___UnsupportedSchemaFeaturePolicy.ValueType
        'Policy for handling source schema features unsupported by the\n        destination, such as rulesets or metadata tags. If unset, FAIL is\n        used.\n        '

        @property
        def auth_options(self) -> Global___SchemaRegistryAuthOptions:
            """Authentication settings for requests to the source Schema Registry.
            If unset, requests are sent without authentication.
            """

        @property
        def tls_settings(self) -> proto.redpanda.core.common.v1.tls_pb2.TLSSettings:
            """TLS settings for requests to the source Schema Registry."""

        @property
        def tail_interval(self) -> google.protobuf.duration_pb2.Duration:
            """Interval between incremental polls for new source subjects and
            subject versions. If unset or zero, the cluster default of 10s is
            used.
            """

        @property
        def effective_tail_interval(self) -> google.protobuf.duration_pb2.Duration:
            """The effective interval between incremental polls."""

        @property
        def full_sync_interval(self) -> google.protobuf.duration_pb2.Duration:
            """Interval between full scans of the selected source subjects. If unset
            or zero, the cluster default of 5m is used.
            """

        @property
        def effective_full_sync_interval(self) -> google.protobuf.duration_pb2.Duration:
            """The effective interval between full scans."""

        @property
        def source_filter(self) -> Global___SchemaRegistrySourceFilter:
            """Filter for specific Schema Registry contexts and subjects to select
            for replication. If unset or empty, the whole source Schema Registry
            is replicated.
            """

        @property
        def destination(self) -> Global___SchemaRegistryContextDestination:
            """Mapping from source contexts implied by `source_filter` to
            destination contexts. Each source context included in the replication
            must map to a distinct destination context to avoid
            collisions. If unset, source context names are preserved.
            """

        def __init__(self, *, source_url: builtins.str=..., auth_options: Global___SchemaRegistryAuthOptions | None=..., tls_settings: proto.redpanda.core.common.v1.tls_pb2.TLSSettings | None=..., tail_interval: google.protobuf.duration_pb2.Duration | None=..., effective_tail_interval: google.protobuf.duration_pb2.Duration | None=..., full_sync_interval: google.protobuf.duration_pb2.Duration | None=..., effective_full_sync_interval: google.protobuf.duration_pb2.Duration | None=..., max_source_requests_per_second: builtins.int=..., effective_max_source_requests_per_second: builtins.int=..., source_filter: Global___SchemaRegistrySourceFilter | None=..., destination: Global___SchemaRegistryContextDestination | None=..., unsupported_schema_feature_policy: Global___UnsupportedSchemaFeaturePolicy.ValueType=...) -> None:
            ...

        def HasField(self, field_name: typing.Literal['_tls_settings', b'_tls_settings', 'auth_options', b'auth_options', 'destination', b'destination', 'effective_full_sync_interval', b'effective_full_sync_interval', 'effective_tail_interval', b'effective_tail_interval', 'full_sync_interval', b'full_sync_interval', 'source_filter', b'source_filter', 'tail_interval', b'tail_interval', 'tls_settings', b'tls_settings']) -> builtins.bool:
            ...

        def ClearField(self, field_name: typing.Literal['_tls_settings', b'_tls_settings', 'auth_options', b'auth_options', 'destination', b'destination', 'effective_full_sync_interval', b'effective_full_sync_interval', 'effective_max_source_requests_per_second', b'effective_max_source_requests_per_second', 'effective_tail_interval', b'effective_tail_interval', 'full_sync_interval', b'full_sync_interval', 'max_source_requests_per_second', b'max_source_requests_per_second', 'source_filter', b'source_filter', 'source_url', b'source_url', 'tail_interval', b'tail_interval', 'tls_settings', b'tls_settings', 'unsupported_schema_feature_policy', b'unsupported_schema_feature_policy']) -> None:
            ...

        def WhichOneof(self, oneof_group: typing.Literal['_tls_settings', b'_tls_settings']) -> typing.Literal['tls_settings'] | None:
            ...
    SHADOW_SCHEMA_REGISTRY_TOPIC_FIELD_NUMBER: builtins.int
    SHADOW_SCHEMA_REGISTRY_API_FIELD_NUMBER: builtins.int

    @property
    def shadow_schema_registry_topic(self) -> Global___SchemaRegistrySyncOptions.ShadowSchemaRegistryTopic:
        ...

    @property
    def shadow_schema_registry_api(self) -> Global___SchemaRegistrySyncOptions.ShadowSchemaRegistryApi:
        ...

    def __init__(self, *, shadow_schema_registry_topic: Global___SchemaRegistrySyncOptions.ShadowSchemaRegistryTopic | None=..., shadow_schema_registry_api: Global___SchemaRegistrySyncOptions.ShadowSchemaRegistryApi | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['schema_registry_shadowing_mode', b'schema_registry_shadowing_mode', 'shadow_schema_registry_api', b'shadow_schema_registry_api', 'shadow_schema_registry_topic', b'shadow_schema_registry_topic']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['schema_registry_shadowing_mode', b'schema_registry_shadowing_mode', 'shadow_schema_registry_api', b'shadow_schema_registry_api', 'shadow_schema_registry_topic', b'shadow_schema_registry_topic']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['schema_registry_shadowing_mode', b'schema_registry_shadowing_mode']) -> typing.Literal['shadow_schema_registry_topic', 'shadow_schema_registry_api'] | None:
        ...
Global___SchemaRegistrySyncOptions: typing_extensions.TypeAlias = SchemaRegistrySyncOptions

@typing.final
class SchemaRegistryAuthOptions(google.protobuf.message.Message):
    """Authentication settings for source Schema Registry HTTP requests."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    BASIC_FIELD_NUMBER: builtins.int

    @property
    def basic(self) -> Global___HTTPBasicAuthOptions:
        """Authenticate source Schema Registry requests with HTTP Basic auth."""

    def __init__(self, *, basic: Global___HTTPBasicAuthOptions | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['auth_options', b'auth_options', 'basic', b'basic']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['auth_options', b'auth_options', 'basic', b'basic']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['auth_options', b'auth_options']) -> typing.Literal['basic'] | None:
        ...
Global___SchemaRegistryAuthOptions: typing_extensions.TypeAlias = SchemaRegistryAuthOptions

@typing.final
class HTTPBasicAuthOptions(google.protobuf.message.Message):
    """HTTP Basic auth credentials."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    PASSWORD_SET_FIELD_NUMBER: builtins.int
    PASSWORD_SET_AT_FIELD_NUMBER: builtins.int
    username: builtins.str
    'HTTP Basic auth username. For Confluent Cloud, this is the API key.'
    password: builtins.str
    'HTTP Basic auth password. For Confluent Cloud, this is the API secret.'
    password_set: builtins.bool
    'Indicates that the password has been set.'

    @property
    def password_set_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of when the password was last set - only valid if password_set
        is true.
        """

    def __init__(self, *, username: builtins.str=..., password: builtins.str=..., password_set: builtins.bool=..., password_set_at: google.protobuf.timestamp_pb2.Timestamp | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['password_set_at', b'password_set_at']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['password', b'password', 'password_set', b'password_set', 'password_set_at', b'password_set_at', 'username', b'username']) -> None:
        ...
Global___HTTPBasicAuthOptions: typing_extensions.TypeAlias = HTTPBasicAuthOptions

@typing.final
class SchemaRegistrySourceFilter(google.protobuf.message.Message):
    """Filter for specific Schema Registry contexts and subjects to select for
    replication. If unset or empty, the whole source Schema Registry is
    replicated.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CONTEXTS_FIELD_NUMBER: builtins.int
    SUBJECTS_FIELD_NUMBER: builtins.int

    @property
    def contexts(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Source contexts to replicate in full, for example ".", ".prod", or
        ".staging". If both `contexts` and `subjects` are set, the effective
        source scope is the union of both selections.
        """

    @property
    def subjects(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Exact source subjects to replicate, using Schema Registry qualified
        subject syntax. For example, "orders-value" selects the subject in the
        default context, and ":.prod:orders-value" selects the subject in context
        ".prod". If both `contexts` and `subjects` are set, the union of both
        selections is replicated. If a subject is also included by `contexts`, it
        is counted and replicated once.
        """

    def __init__(self, *, contexts: collections.abc.Iterable[builtins.str] | None=..., subjects: collections.abc.Iterable[builtins.str] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['contexts', b'contexts', 'subjects', b'subjects']) -> None:
        ...
Global___SchemaRegistrySourceFilter: typing_extensions.TypeAlias = SchemaRegistrySourceFilter

@typing.final
class SchemaRegistryContextDestination(google.protobuf.message.Message):
    """Destination context mapping for source Schema Registry data."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IDENTITY_FIELD_NUMBER: builtins.int
    EXACT_FIELD_NUMBER: builtins.int

    @property
    def identity(self) -> Global___SchemaRegistryIdentityContextMapping:
        """Preserve source context names in the destination Schema Registry."""

    @property
    def exact(self) -> Global___SchemaRegistryExactContextMappings:
        """Map selected source contexts to explicit destination contexts."""

    def __init__(self, *, identity: Global___SchemaRegistryIdentityContextMapping | None=..., exact: Global___SchemaRegistryExactContextMappings | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['exact', b'exact', 'identity', b'identity', 'mapping', b'mapping']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['exact', b'exact', 'identity', b'identity', 'mapping', b'mapping']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['mapping', b'mapping']) -> typing.Literal['identity', 'exact'] | None:
        ...
Global___SchemaRegistryContextDestination: typing_extensions.TypeAlias = SchemaRegistryContextDestination

@typing.final
class SchemaRegistryIdentityContextMapping(google.protobuf.message.Message):
    """Preserve source context names in the destination Schema Registry."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
Global___SchemaRegistryIdentityContextMapping: typing_extensions.TypeAlias = SchemaRegistryIdentityContextMapping

@typing.final
class SchemaRegistryExactContextMappings(google.protobuf.message.Message):
    """Explicit source-to-destination context mappings."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAPPINGS_FIELD_NUMBER: builtins.int

    @property
    def mappings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___SchemaRegistryContextMap]:
        """Explicit source-to-destination context mappings. Every source context in
        the effective source scope must have exactly one mapping.
        """

    def __init__(self, *, mappings: collections.abc.Iterable[Global___SchemaRegistryContextMap] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['mappings', b'mappings']) -> None:
        ...
Global___SchemaRegistryExactContextMappings: typing_extensions.TypeAlias = SchemaRegistryExactContextMappings

@typing.final
class SchemaRegistryContextMap(google.protobuf.message.Message):
    """One source-to-destination context mapping."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SOURCE_FIELD_NUMBER: builtins.int
    DESTINATION_FIELD_NUMBER: builtins.int
    source: builtins.str
    'Source context name.'
    destination: builtins.str
    'Destination context name.'

    def __init__(self, *, source: builtins.str=..., destination: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['destination', b'destination', 'source', b'source']) -> None:
        ...
Global___SchemaRegistryContextMap: typing_extensions.TypeAlias = SchemaRegistryContextMap

@typing.final
class ConsumerOffsetSyncOptions(google.protobuf.message.Message):
    """Options for syncing consumer offsets"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INTERVAL_FIELD_NUMBER: builtins.int
    EFFECTIVE_INTERVAL_FIELD_NUMBER: builtins.int
    PAUSED_FIELD_NUMBER: builtins.int
    GROUP_FILTERS_FIELD_NUMBER: builtins.int
    paused: builtins.bool
    "Allows user to pause the consumer offset sync task.  If paused, then\n    the task will enter the 'paused' state and not sync consumer offsets from\n    the source cluster\n    "

    @property
    def interval(self) -> google.protobuf.duration_pb2.Duration:
        """Sync interval
        If 0 provided, defaults to 30 seconds
        """

    @property
    def effective_interval(self) -> google.protobuf.duration_pb2.Duration:
        """The effective interval for the task"""

    @property
    def group_filters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NameFilter]:
        """The filters"""

    def __init__(self, *, interval: google.protobuf.duration_pb2.Duration | None=..., effective_interval: google.protobuf.duration_pb2.Duration | None=..., paused: builtins.bool=..., group_filters: collections.abc.Iterable[Global___NameFilter] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['effective_interval', b'effective_interval', 'interval', b'interval']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['effective_interval', b'effective_interval', 'group_filters', b'group_filters', 'interval', b'interval', 'paused', b'paused']) -> None:
        ...
Global___ConsumerOffsetSyncOptions: typing_extensions.TypeAlias = ConsumerOffsetSyncOptions

@typing.final
class SecuritySettingsSyncOptions(google.protobuf.message.Message):
    """Options for syncing security settings"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INTERVAL_FIELD_NUMBER: builtins.int
    EFFECTIVE_INTERVAL_FIELD_NUMBER: builtins.int
    PAUSED_FIELD_NUMBER: builtins.int
    ACL_FILTERS_FIELD_NUMBER: builtins.int
    paused: builtins.bool
    "Allows user to pause the security settings sync task.  If paused,\n    then the task will enter the 'paused' state and will not sync security\n    settings from the source cluster\n    "

    @property
    def interval(self) -> google.protobuf.duration_pb2.Duration:
        """Sync interval
        If 0 provided, defaults to 30 seconds
        """

    @property
    def effective_interval(self) -> google.protobuf.duration_pb2.Duration:
        """The effective interval for the task"""

    @property
    def acl_filters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ACLFilter]:
        """ACL filters"""

    def __init__(self, *, interval: google.protobuf.duration_pb2.Duration | None=..., effective_interval: google.protobuf.duration_pb2.Duration | None=..., paused: builtins.bool=..., acl_filters: collections.abc.Iterable[Global___ACLFilter] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['effective_interval', b'effective_interval', 'interval', b'interval']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['acl_filters', b'acl_filters', 'effective_interval', b'effective_interval', 'interval', b'interval', 'paused', b'paused']) -> None:
        ...
Global___SecuritySettingsSyncOptions: typing_extensions.TypeAlias = SecuritySettingsSyncOptions

@typing.final
class RoleSyncOptions(google.protobuf.message.Message):
    """Options for syncing RBAC roles"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INTERVAL_FIELD_NUMBER: builtins.int
    EFFECTIVE_INTERVAL_FIELD_NUMBER: builtins.int
    PAUSED_FIELD_NUMBER: builtins.int
    ROLE_NAME_FILTERS_FIELD_NUMBER: builtins.int
    paused: builtins.bool
    "Allows user to pause the role sync task.  If paused, then the task will\n    enter the 'paused' state and will not sync roles from the source cluster\n    "

    @property
    def interval(self) -> google.protobuf.duration_pb2.Duration:
        """Sync interval
        If 0 provided, defaults to 30 seconds
        """

    @property
    def effective_interval(self) -> google.protobuf.duration_pb2.Duration:
        """The effective interval for the task"""

    @property
    def role_name_filters(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NameFilter]:
        """Filters selecting which roles to shadow by name.  Defaults to empty: no
        roles are synced until at least one include filter is added
        """

    def __init__(self, *, interval: google.protobuf.duration_pb2.Duration | None=..., effective_interval: google.protobuf.duration_pb2.Duration | None=..., paused: builtins.bool=..., role_name_filters: collections.abc.Iterable[Global___NameFilter] | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['effective_interval', b'effective_interval', 'interval', b'interval']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['effective_interval', b'effective_interval', 'interval', b'interval', 'paused', b'paused', 'role_name_filters', b'role_name_filters']) -> None:
        ...
Global___RoleSyncOptions: typing_extensions.TypeAlias = RoleSyncOptions

@typing.final
class AuthenticationConfiguration(google.protobuf.message.Message):
    """Authentication config.  Supports:
    * SASL/SCRAM
    * SASL/PLAIN
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SCRAM_CONFIGURATION_FIELD_NUMBER: builtins.int
    PLAIN_CONFIGURATION_FIELD_NUMBER: builtins.int

    @property
    def scram_configuration(self) -> Global___ScramConfig:
        """SASL/SCRAM configuration"""

    @property
    def plain_configuration(self) -> Global___PlainConfig:
        """SASL/PLAIN configuration"""

    def __init__(self, *, scram_configuration: Global___ScramConfig | None=..., plain_configuration: Global___PlainConfig | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['authentication', b'authentication', 'plain_configuration', b'plain_configuration', 'scram_configuration', b'scram_configuration']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['authentication', b'authentication', 'plain_configuration', b'plain_configuration', 'scram_configuration', b'scram_configuration']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing.Literal['authentication', b'authentication']) -> typing.Literal['scram_configuration', 'plain_configuration'] | None:
        ...
Global___AuthenticationConfiguration: typing_extensions.TypeAlias = AuthenticationConfiguration

@typing.final
class PlainConfig(google.protobuf.message.Message):
    """PLAIN settings"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    PASSWORD_SET_FIELD_NUMBER: builtins.int
    PASSWORD_SET_AT_FIELD_NUMBER: builtins.int
    username: builtins.str
    'PLAIN username'
    password: builtins.str
    'Password'
    password_set: builtins.bool
    'Indicates that the password has been set'

    @property
    def password_set_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of when the password was last set - only valid if password_set
        is true
        """

    def __init__(self, *, username: builtins.str=..., password: builtins.str=..., password_set: builtins.bool=..., password_set_at: google.protobuf.timestamp_pb2.Timestamp | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['password_set_at', b'password_set_at']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['password', b'password', 'password_set', b'password_set', 'password_set_at', b'password_set_at', 'username', b'username']) -> None:
        ...
Global___PlainConfig: typing_extensions.TypeAlias = PlainConfig

@typing.final
class ScramConfig(google.protobuf.message.Message):
    """SCRAM settings"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    PASSWORD_SET_FIELD_NUMBER: builtins.int
    PASSWORD_SET_AT_FIELD_NUMBER: builtins.int
    SCRAM_MECHANISM_FIELD_NUMBER: builtins.int
    username: builtins.str
    'SCRAM username'
    password: builtins.str
    'Password'
    password_set: builtins.bool
    'Indicates that the password has been set'
    scram_mechanism: Global___ScramMechanism.ValueType
    'The SCRAM mechanism to use'

    @property
    def password_set_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of when the password was last set - only valid if password_set
        is true
        """

    def __init__(self, *, username: builtins.str=..., password: builtins.str=..., password_set: builtins.bool=..., password_set_at: google.protobuf.timestamp_pb2.Timestamp | None=..., scram_mechanism: Global___ScramMechanism.ValueType=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['password_set_at', b'password_set_at']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['password', b'password', 'password_set', b'password_set', 'password_set_at', b'password_set_at', 'scram_mechanism', b'scram_mechanism', 'username', b'username']) -> None:
        ...
Global___ScramConfig: typing_extensions.TypeAlias = ScramConfig

@typing.final
class NameFilter(google.protobuf.message.Message):
    """A filter based on the name of a resource"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATTERN_TYPE_FIELD_NUMBER: builtins.int
    FILTER_TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    pattern_type: Global___PatternType.ValueType
    'Literal or prefix'
    filter_type: Global___FilterType.ValueType
    'Include or exclude'
    name: builtins.str
    'The resource name, or "*"\n    Note if "*", must be the _only_ character\n    and `pattern_type` must be `PATTERN_TYPE_LITERAL`\n    '

    def __init__(self, *, pattern_type: Global___PatternType.ValueType=..., filter_type: Global___FilterType.ValueType=..., name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['filter_type', b'filter_type', 'name', b'name', 'pattern_type', b'pattern_type']) -> None:
        ...
Global___NameFilter: typing_extensions.TypeAlias = NameFilter

@typing.final
class ACLFilter(google.protobuf.message.Message):
    """A filter for ACLs"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESOURCE_FILTER_FIELD_NUMBER: builtins.int
    ACCESS_FILTER_FIELD_NUMBER: builtins.int

    @property
    def resource_filter(self) -> Global___ACLResourceFilter:
        """The resource filter"""

    @property
    def access_filter(self) -> Global___ACLAccessFilter:
        """The access filter"""

    def __init__(self, *, resource_filter: Global___ACLResourceFilter | None=..., access_filter: Global___ACLAccessFilter | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['access_filter', b'access_filter', 'resource_filter', b'resource_filter']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['access_filter', b'access_filter', 'resource_filter', b'resource_filter']) -> None:
        ...
Global___ACLFilter: typing_extensions.TypeAlias = ACLFilter

@typing.final
class ACLResourceFilter(google.protobuf.message.Message):
    """A filter to match ACLs for resources"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESOURCE_TYPE_FIELD_NUMBER: builtins.int
    PATTERN_TYPE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    resource_type: proto.redpanda.core.common.v1.acl_pb2.ACLResource.ValueType
    'The ACL resource type to match'
    pattern_type: proto.redpanda.core.common.v1.acl_pb2.ACLPattern.ValueType
    'The pattern to apply to name'
    name: builtins.str
    'Name, if not given will default to match all items in `resource_type`.\n    Note that asterisk `*` is literal and matches resource ACLs\n    that are named `*`\n    '

    def __init__(self, *, resource_type: proto.redpanda.core.common.v1.acl_pb2.ACLResource.ValueType=..., pattern_type: proto.redpanda.core.common.v1.acl_pb2.ACLPattern.ValueType=..., name: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name', 'pattern_type', b'pattern_type', 'resource_type', b'resource_type']) -> None:
        ...
Global___ACLResourceFilter: typing_extensions.TypeAlias = ACLResourceFilter

@typing.final
class ACLAccessFilter(google.protobuf.message.Message):
    """Filter an ACL based on its access"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PRINCIPAL_FIELD_NUMBER: builtins.int
    OPERATION_FIELD_NUMBER: builtins.int
    PERMISSION_TYPE_FIELD_NUMBER: builtins.int
    HOST_FIELD_NUMBER: builtins.int
    principal: builtins.str
    'The name of the principal, if not set will default to match\n    all principals with the specified `operation` and `permission_type`\n    '
    operation: proto.redpanda.core.common.v1.acl_pb2.ACLOperation.ValueType
    'The ACL operation to match'
    permission_type: proto.redpanda.core.common.v1.acl_pb2.ACLPermissionType.ValueType
    'The permission type'
    host: builtins.str
    'The host to match.  If not set, will default to match all hosts\n    with the specified `operation` and `permission_type`. Note that\n    the asterisk `*` is literal and matches hosts that are set to `*`\n    '

    def __init__(self, *, principal: builtins.str=..., operation: proto.redpanda.core.common.v1.acl_pb2.ACLOperation.ValueType=..., permission_type: proto.redpanda.core.common.v1.acl_pb2.ACLPermissionType.ValueType=..., host: builtins.str=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['host', b'host', 'operation', b'operation', 'permission_type', b'permission_type', 'principal', b'principal']) -> None:
        ...
Global___ACLAccessFilter: typing_extensions.TypeAlias = ACLAccessFilter

@typing.final
class ShadowLinkStatus(google.protobuf.message.Message):
    """Status of the shadow link"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATE_FIELD_NUMBER: builtins.int
    TASK_STATUSES_FIELD_NUMBER: builtins.int
    SHADOW_TOPICS_FIELD_NUMBER: builtins.int
    SYNCED_SHADOW_TOPIC_PROPERTIES_FIELD_NUMBER: builtins.int
    SCHEMA_REGISTRY_SYNC_STATUS_FIELD_NUMBER: builtins.int
    state: Global___ShadowLinkState.ValueType

    @property
    def task_statuses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ShadowLinkTaskStatus]:
        """Statuses of the running tasks"""

    @property
    def shadow_topics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ShadowTopic]:
        """Status of shadow topics"""

    @property
    def synced_shadow_topic_properties(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of topic properties that are being synced"""

    @property
    def schema_registry_sync_status(self) -> Global___SchemaRegistrySyncStatus:
        """Status of Schema Registry syncing."""

    def __init__(self, *, state: Global___ShadowLinkState.ValueType=..., task_statuses: collections.abc.Iterable[Global___ShadowLinkTaskStatus] | None=..., shadow_topics: collections.abc.Iterable[Global___ShadowTopic] | None=..., synced_shadow_topic_properties: collections.abc.Iterable[builtins.str] | None=..., schema_registry_sync_status: Global___SchemaRegistrySyncStatus | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['schema_registry_sync_status', b'schema_registry_sync_status']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['schema_registry_sync_status', b'schema_registry_sync_status', 'shadow_topics', b'shadow_topics', 'state', b'state', 'synced_shadow_topic_properties', b'synced_shadow_topic_properties', 'task_statuses', b'task_statuses']) -> None:
        ...
Global___ShadowLinkStatus: typing_extensions.TypeAlias = ShadowLinkStatus

@typing.final
class ShadowLinkTaskStatus(google.protobuf.message.Message):
    """Status of a task"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    BROKER_ID_FIELD_NUMBER: builtins.int
    SHARD_FIELD_NUMBER: builtins.int
    name: builtins.str
    'Name of the task'
    state: Global___TaskState.ValueType
    'State of the task'
    reason: builtins.str
    'Reason for task being in state'
    broker_id: builtins.int
    'The broker the task is running on'
    shard: builtins.int
    'The shard the task is running on'

    def __init__(self, *, name: builtins.str=..., state: Global___TaskState.ValueType=..., reason: builtins.str=..., broker_id: builtins.int=..., shard: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['broker_id', b'broker_id', 'name', b'name', 'reason', b'reason', 'shard', b'shard', 'state', b'state']) -> None:
        ...
Global___ShadowLinkTaskStatus: typing_extensions.TypeAlias = ShadowLinkTaskStatus

@typing.final
class ShadowTopicStatus(google.protobuf.message.Message):
    """Status of a ShadowTopic"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STATE_FIELD_NUMBER: builtins.int
    PARTITION_INFORMATION_FIELD_NUMBER: builtins.int
    state: Global___ShadowTopicState.ValueType
    'State of the shadow topic'

    @property
    def partition_information(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___TopicPartitionInformation]:
        """List of partition information for the shadow topic"""

    def __init__(self, *, state: Global___ShadowTopicState.ValueType=..., partition_information: collections.abc.Iterable[Global___TopicPartitionInformation] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['partition_information', b'partition_information', 'state', b'state']) -> None:
        ...
Global___ShadowTopicStatus: typing_extensions.TypeAlias = ShadowTopicStatus

@typing.final
class TopicPartitionInformation(google.protobuf.message.Message):
    """Topic partition information"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARTITION_ID_FIELD_NUMBER: builtins.int
    SOURCE_LAST_STABLE_OFFSET_FIELD_NUMBER: builtins.int
    SOURCE_HIGH_WATERMARK_FIELD_NUMBER: builtins.int
    HIGH_WATERMARK_FIELD_NUMBER: builtins.int
    SOURCE_LAST_UPDATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    partition_id: builtins.int
    'Partition ID'
    source_last_stable_offset: builtins.int
    "Source partition's LSO"
    source_high_watermark: builtins.int
    "Source partition's HWM"
    high_watermark: builtins.int
    "Shadowed partition's HWM"

    @property
    def source_last_updated_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of the last time the source partition information was updated"""

    def __init__(self, *, partition_id: builtins.int=..., source_last_stable_offset: builtins.int=..., source_high_watermark: builtins.int=..., high_watermark: builtins.int=..., source_last_updated_timestamp: google.protobuf.timestamp_pb2.Timestamp | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['source_last_updated_timestamp', b'source_last_updated_timestamp']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['high_watermark', b'high_watermark', 'partition_id', b'partition_id', 'source_high_watermark', b'source_high_watermark', 'source_last_stable_offset', b'source_last_stable_offset', 'source_last_updated_timestamp', b'source_last_updated_timestamp']) -> None:
        ...
Global___TopicPartitionInformation: typing_extensions.TypeAlias = TopicPartitionInformation

@typing.final
class SchemaRegistrySyncStatus(google.protobuf.message.Message):
    """Status of Schema Registry syncing."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INVENTORY_FIELD_NUMBER: builtins.int
    CURRENT_SYNC_FIELD_NUMBER: builtins.int
    LAST_FULL_SYNC_FIELD_NUMBER: builtins.int
    TOTALS_SINCE_TASK_START_FIELD_NUMBER: builtins.int
    LAST_ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    last_error_message: builtins.str
    'Short sanitized summary of the most recent Schema Registry sync\n    error. Detailed errors are written to broker logs.\n    '

    @property
    def inventory(self) -> Global___SchemaRegistryInventory:
        """Last observed source and destination Schema Registry inventory. These
        counts are updated as sync work observes source and destination state.
        """

    @property
    def current_sync(self) -> Global___SchemaRegistryCurrentSync:
        """Sync currently running. This is unset when no Schema Registry sync is
        running.
        """

    @property
    def last_full_sync(self) -> Global___SchemaRegistrySyncSummary:
        """Counters from the most recently completed full sync. This is unset until
        a full sync completes on the current task instance.
        """

    @property
    def totals_since_task_start(self) -> Global___SchemaRegistrySyncSummary:
        """Cumulative counters since the Schema Registry task started. These
        counters reset after task restart or leadership transfer.
        """

    def __init__(self, *, inventory: Global___SchemaRegistryInventory | None=..., current_sync: Global___SchemaRegistryCurrentSync | None=..., last_full_sync: Global___SchemaRegistrySyncSummary | None=..., totals_since_task_start: Global___SchemaRegistrySyncSummary | None=..., last_error_message: builtins.str=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['current_sync', b'current_sync', 'inventory', b'inventory', 'last_full_sync', b'last_full_sync', 'totals_since_task_start', b'totals_since_task_start']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['current_sync', b'current_sync', 'inventory', b'inventory', 'last_error_message', b'last_error_message', 'last_full_sync', b'last_full_sync', 'totals_since_task_start', b'totals_since_task_start']) -> None:
        ...
Global___SchemaRegistrySyncStatus: typing_extensions.TypeAlias = SchemaRegistrySyncStatus

@typing.final
class SchemaRegistryCurrentSync(google.protobuf.message.Message):
    """A Schema Registry sync that is currently running."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SYNC_TYPE_FIELD_NUMBER: builtins.int
    SUMMARY_FIELD_NUMBER: builtins.int
    sync_type: Global___SchemaRegistrySyncType.ValueType
    'Type of Schema Registry sync currently running.'

    @property
    def summary(self) -> Global___SchemaRegistrySyncSummary:
        """Counters for the sync currently running."""

    def __init__(self, *, sync_type: Global___SchemaRegistrySyncType.ValueType=..., summary: Global___SchemaRegistrySyncSummary | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['summary', b'summary']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['summary', b'summary', 'sync_type', b'sync_type']) -> None:
        ...
Global___SchemaRegistryCurrentSync: typing_extensions.TypeAlias = SchemaRegistryCurrentSync

@typing.final
class SchemaRegistryInventory(google.protobuf.message.Message):
    """Last observed Schema Registry inventory."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SELECTED_SOURCE_SUBJECTS_FIELD_NUMBER: builtins.int
    SELECTED_SOURCE_SUBJECT_VERSIONS_FIELD_NUMBER: builtins.int
    DESTINATION_SUBJECTS_FIELD_NUMBER: builtins.int
    DESTINATION_SUBJECT_VERSIONS_FIELD_NUMBER: builtins.int
    selected_source_subjects: builtins.int
    'Number of source subjects selected for replication after applying source\n    scope context and subject filters.\n    '
    selected_source_subject_versions: builtins.int
    'Number of source subject versions selected for replication after\n    applying source scope context and subject filters.\n    '
    destination_subjects: builtins.int
    'Number of destination subjects corresponding to the selected source\n    subjects after applying destination context mapping.\n    '
    destination_subject_versions: builtins.int
    'Number of destination subject versions corresponding to the selected\n    source subjects after applying destination context mapping.\n    '

    def __init__(self, *, selected_source_subjects: builtins.int=..., selected_source_subject_versions: builtins.int=..., destination_subjects: builtins.int=..., destination_subject_versions: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['destination_subject_versions', b'destination_subject_versions', 'destination_subjects', b'destination_subjects', 'selected_source_subject_versions', b'selected_source_subject_versions', 'selected_source_subjects', b'selected_source_subjects']) -> None:
        ...
Global___SchemaRegistryInventory: typing_extensions.TypeAlias = SchemaRegistryInventory

@typing.final
class SchemaRegistrySyncSummary(google.protobuf.message.Message):
    """Summary counters for one Schema Registry sync or for a cumulative interval."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_TIME_FIELD_NUMBER: builtins.int
    FINISH_TIME_FIELD_NUMBER: builtins.int
    SUBJECT_VERSIONS_CHANGED_FIELD_NUMBER: builtins.int
    COMPATIBILITY_CONFIGS_CHANGED_FIELD_NUMBER: builtins.int
    MODES_CHANGED_FIELD_NUMBER: builtins.int
    UNSUPPORTED_FEATURES_REMOVED_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    subject_versions_changed: builtins.int
    'Number of selected subject versions created, updated, or deleted on the\n    destination.\n    '
    compatibility_configs_changed: builtins.int
    'Number of selected compatibility configuration changes applied to the\n    destination.\n    '
    modes_changed: builtins.int
    'Number of selected mode changes applied to the destination.'
    unsupported_features_removed: builtins.int
    'Number of unsupported fields removed from schemas or schema configs when\n    UNSUPPORTED_SCHEMA_FEATURE_POLICY_REMOVE is used.\n    '
    errors: builtins.int
    'Number of errors observed during the sync or cumulative interval.'

    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Time when the sync started. For cumulative counters, this is the time
        when the Schema Registry task started.
        """

    @property
    def finish_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Time when the sync finished. This is unset for a sync that is still
        running and for cumulative counters.
        """

    def __init__(self, *, start_time: google.protobuf.timestamp_pb2.Timestamp | None=..., finish_time: google.protobuf.timestamp_pb2.Timestamp | None=..., subject_versions_changed: builtins.int=..., compatibility_configs_changed: builtins.int=..., modes_changed: builtins.int=..., unsupported_features_removed: builtins.int=..., errors: builtins.int=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['finish_time', b'finish_time', 'start_time', b'start_time']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['compatibility_configs_changed', b'compatibility_configs_changed', 'errors', b'errors', 'finish_time', b'finish_time', 'modes_changed', b'modes_changed', 'start_time', b'start_time', 'subject_versions_changed', b'subject_versions_changed', 'unsupported_features_removed', b'unsupported_features_removed']) -> None:
        ...
Global___SchemaRegistrySyncSummary: typing_extensions.TypeAlias = SchemaRegistrySyncSummary