"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StartStressFiberRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MIN_SPINS_PER_SCHEDULING_POINT_FIELD_NUMBER: builtins.int
    MAX_SPINS_PER_SCHEDULING_POINT_FIELD_NUMBER: builtins.int
    STACK_DEPTH_FIELD_NUMBER: builtins.int
    MIN_MS_PER_SCHEDULING_POINT_FIELD_NUMBER: builtins.int
    MAX_MS_PER_SCHEDULING_POINT_FIELD_NUMBER: builtins.int
    FIBER_COUNT_FIELD_NUMBER: builtins.int
    min_spins_per_scheduling_point: builtins.int
    max_spins_per_scheduling_point: builtins.int
    stack_depth: builtins.int
    min_ms_per_scheduling_point: builtins.int
    max_ms_per_scheduling_point: builtins.int
    fiber_count: builtins.int

    def __init__(self, *, min_spins_per_scheduling_point: builtins.int=..., max_spins_per_scheduling_point: builtins.int=..., stack_depth: builtins.int=..., min_ms_per_scheduling_point: builtins.int=..., max_ms_per_scheduling_point: builtins.int=..., fiber_count: builtins.int=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['fiber_count', b'fiber_count', 'max_ms_per_scheduling_point', b'max_ms_per_scheduling_point', 'max_spins_per_scheduling_point', b'max_spins_per_scheduling_point', 'min_ms_per_scheduling_point', b'min_ms_per_scheduling_point', 'min_spins_per_scheduling_point', b'min_spins_per_scheduling_point', 'stack_depth', b'stack_depth']) -> None:
        ...
global___StartStressFiberRequest = StartStressFiberRequest

@typing.final
class StartStressFiberResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___StartStressFiberResponse = StartStressFiberResponse

@typing.final
class StopStressFiberRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___StopStressFiberRequest = StopStressFiberRequest

@typing.final
class StopStressFiberResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___StopStressFiberResponse = StopStressFiberResponse