load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "date_proto",
    srcs = ["date.proto"],
    import_prefix = "redpanda/datalake",
    strip_import_prefix = "",
    visibility = ["//visibility:public"],
)
