{{/*
Copyright 2020 Redpanda Data, Inc.

Use of this software is governed by the Business Source License
included in the file licenses/BSL.md

As of the Change Date specified in that file, in accordance with
the Business Source License, use of this software will be governed
by the Apache License, Version 2.0
*/}}

{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redpanda-operator.name" . }}-webhook-service
  labels:
{{ include "redpanda-operator.labels" . | indent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: {{ include "redpanda-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
