{
 "title": "Vectorized",
 "panels": [
  {
   "title": "net_conntrack_dialer_conn_attempted_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_attempted_total{job=\"node\"}"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_closed_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_closed_total{job=\"node\"}"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_established_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_established_total{job=\"node\"}"
    }
   ]
  },
  {
   "title": "net_conntrack_dialer_conn_failed_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_conntrack_dialer_conn_failed_total{job=\"node\"}"
    }
   ]
  },
  {
   "title": "net_conntrack_listener_conn_accepted_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_conntrack_listener_conn_accepted_total{job=\"node\"}"
    }
   ]
  },
  {
   "title": "net_conntrack_listener_conn_closed_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "net_conntrack_listener_conn_closed_total{job=\"node\"}"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"node\"}"
    }
   ]
  },
  {
   "title": "process_max_fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{job=\"node\"}"
    }
   ]
  },
  {
   "title": "process_open_fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"node\"}"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "process_start_time_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"node\"}"
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "process_virtual_memory_max_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_alien_receive_batch_queue_length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_alien_receive_batch_queue_length{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_alien_total_received_messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_alien_total_received_messages{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_alien_total_sent_messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_alien_total_sent_messages{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_httpd_connections_current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_httpd_connections_current{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_httpd_connections_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_httpd_connections_total{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_httpd_read_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_httpd_read_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_httpd_reply_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_httpd_reply_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_httpd_requests_served",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_httpd_requests_served{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_io_queue_delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_io_queue_delay{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_io_queue_queue_length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_io_queue_queue_length{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_io_queue_shares",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_io_queue_shares{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_io_queue_total_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_io_queue_total_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_io_queue_total_operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_io_queue_total_operations{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_active_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_active_connections{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_bad_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_bad_requests{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_connection_close_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_connection_close_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_connects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_connects{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_consumed_mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_consumed_mem{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_corrupted_headers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_corrupted_headers{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_dispatch_handler_latency_bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_dispatch_handler_latency_bucket{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_dispatch_handler_latency_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_dispatch_handler_latency_count{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_dispatch_handler_latency_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_dispatch_handler_latency_sum{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_max_service_mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_max_service_mem{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_method_not_found_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_method_not_found_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_received_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_received_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_requests_blocked_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_requests_blocked_memory{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_requests_completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_requests_completed{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_requests_pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_requests_pending{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_kafka_rpc_protocol_sent_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_kafka_rpc_protocol_sent_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_memory_allocated_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_memory_allocated_memory{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_memory_cross_cpu_free_operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_memory_cross_cpu_free_operations{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_memory_free_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_memory_free_memory{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_memory_free_operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_memory_free_operations{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_memory_malloc_live_objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_memory_malloc_live_objects{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_memory_malloc_operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_memory_malloc_operations{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_memory_reclaims_operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_memory_reclaims_operations{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_memory_total_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_memory_total_memory{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_abandoned_failed_futures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_abandoned_failed_futures{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_aio_bytes_read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_aio_bytes_read{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_aio_bytes_write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_aio_bytes_write{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_aio_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_aio_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_aio_reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_aio_reads{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_aio_writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_aio_writes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_cpp_exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_cpp_exceptions{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_cpu_busy_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_cpu_busy_ms{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_cpu_steal_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_cpu_steal_time_ms{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_fstream_read_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_fstream_read_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_fstream_read_bytes_blocked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_fstream_read_bytes_blocked{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_fstream_reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_fstream_reads{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_fstream_reads_ahead_bytes_discarded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_fstream_reads_ahead_bytes_discarded{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_fstream_reads_aheads_discarded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_fstream_reads_aheads_discarded{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_fstream_reads_blocked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_fstream_reads_blocked{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_fsyncs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_fsyncs{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_io_queue_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_io_queue_requests{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_io_threaded_fallbacks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_io_threaded_fallbacks{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_logging_failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_logging_failures{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_polls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_polls{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_tasks_pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_tasks_pending{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_tasks_processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_tasks_processed{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_timers_pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_timers_pending{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_reactor_utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_reactor_utilization{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_active_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_active_connections{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_client_correlation_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_client_correlation_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_connection_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_connection_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_connects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_connects{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_corrupted_headers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_corrupted_headers{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_in_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_in_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_out_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_out_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_read_dispatch_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_read_dispatch_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_request_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_request_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_request_timeouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_request_timeouts{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_requests{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_requests_blocked_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_requests_blocked_memory{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_requests_pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_requests_pending{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_rpc_client_server_correlation_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_rpc_client_server_correlation_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_scheduler_queue_length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_scheduler_queue_length{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_scheduler_runtime_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_scheduler_runtime_ms{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_scheduler_shares",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_scheduler_shares{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_scheduler_tasks_processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_scheduler_tasks_processed{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_scheduler_time_spent_on_task_quota_violations_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_scheduler_time_spent_on_task_quota_violations_ms{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_stall_detector_reported",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_stall_detector_reported{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_storage_log_batch_parse_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_storage_log_batch_parse_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_storage_log_batch_write_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_storage_log_batch_write_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_storage_log_batches_read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_storage_log_batches_read{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_storage_log_batches_written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_storage_log_batches_written{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_storage_log_bytes_read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_storage_log_bytes_read{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_storage_log_bytes_written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_storage_log_bytes_written{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_storage_log_log_segments_created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_storage_log_log_segments_created{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_active_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_active_connections{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_bad_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_bad_requests{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_connection_close_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_connection_close_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_connects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_connects{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_consumed_mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_consumed_mem{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_corrupted_headers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_corrupted_headers{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_dispatch_handler_latency_bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_dispatch_handler_latency_bucket{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_dispatch_handler_latency_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_dispatch_handler_latency_count{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_dispatch_handler_latency_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_dispatch_handler_latency_sum{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_max_service_mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_max_service_mem{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_method_not_found_errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_method_not_found_errors{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_received_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_received_bytes{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_requests_blocked_memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_requests_blocked_memory{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_requests_completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_requests_completed{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_requests_pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_requests_pending{job=\"node\"}"
    }
   ]
  },
  {
   "title": "vectorized_vectorized_internal_rpc_protocol_sent_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vectorized_vectorized_internal_rpc_protocol_sent_bytes{job=\"node\"}"
    }
   ]
  }
 ]
}