load("//bazel:build.bzl", "redpanda_cc_library")

redpanda_cc_library(
    name = "common_constants",
    hdrs = ["common.h"],
    visibility = ["//visibility:public"],
)

redpanda_cc_library(
    name = "balancer_constants",
    hdrs = ["balancer_constants.h"],
    visibility = ["//visibility:public"],
)
