# permissions for end users to view redpanda.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redpanda-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redpanda-operator
    app.kubernetes.io/part-of: redpanda-operator
    app.kubernetes.io/managed-by: kustomize
  name: redpanda-viewer-role
rules:
- apiGroups:
  - redpanda.vectorized.io
  resources:
  - redpanda
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redpanda.vectorized.io
  resources:
  - redpanda/status
  verbs:
  - get
