# permissions for end users to edit topics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: topic-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redpanda-operator
    app.kubernetes.io/part-of: redpanda-operator
    app.kubernetes.io/managed-by: kustomize
  name: topic-editor-role
rules:
- apiGroups:
  - redpanda.com
  resources:
  - topics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redpanda.com
  resources:
  - topics/status
  verbs:
  - get
