steps:
- id: 'build builder image'
  name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--dockerfile=tools/ci/Dockerfile.base',
         '--destination=gcr.io/$PROJECT_ID/builder:$SHORT_SHA',
         '--cache=true']

- id: 'configure'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  args: ['cmake', '-GNinja', '-B./build', '-DCMAKE_BUILD_TYPE=${_BUILD_TYPE}',
         '-DRP_ENABLE_GOLD_LINKER=OFF', '-DV_MANAGE_DEPS=OFF', '.']
  env:
  - 'CC=clang'
  - 'CXX=clang++'

- id: 'build'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  dir: 'build/'
  args: ['ninja', '-C', '/workspace/build/']

- id: 'test'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  dir: 'build/'
  args: ['ctest', '-V']

timeout: 3600s

substitutions:
  _BUILD_TYPE: Release

options:
  machineType: 'N1_HIGHCPU_32'
