steps:
- id: 'build builder image'
  name: 'gcr.io/kaniko-project/executor:debug-v0.13.0'
  entrypoint: '/busybox/sh'
  args: ['tools/ci/scripts/build-builder.sh']
  env:
  - 'BUILD_TYPE=$_BUILD_TYPE'
  - 'COMPILER=$_COMPILER'
  - 'SHORT_SHA=$SHORT_SHA'
  - 'PROJECT_ID=$PROJECT_ID'

- id: 'build and test cpp'
  name: 'gcr.io/$PROJECT_ID/builder-$_COMPILER-$_BUILD_TYPE:$SHORT_SHA'
  args: ['tools/ci/scripts/build-and-test-cpp.sh']
  env:
  - 'BUILD_TYPE=$_BUILD_TYPE'
  - 'COMPILER=$_COMPILER'
  - 'CI=1'

- id: 'test and build go'
  name: 'gcr.io/$PROJECT_ID/builder-$_COMPILER-$_BUILD_TYPE:$SHORT_SHA'
  args: ['tools/ci/scripts/test-and-build-go.sh']
  env:
  - 'GOBIN=/workspace/build/go/bin'
  - 'CI=1'

- id: 'package'
  name: 'gcr.io/$PROJECT_ID/builder-$_COMPILER-$_BUILD_TYPE:$SHORT_SHA'
  args: ['tools/packaging.py',
         '--build-dir', '/workspace/build/',
         '--build-type', '$_BUILD_TYPE',
         '--formats', 'rpm', 'deb', 'tar',
         '--external', '/usr/local/bin/iotune', '/usr/local/bin/hwloc-calc', '/usr/local/bin/hwloc-distrib']

- id: 'publish package'
  name: 'gcr.io/$PROJECT_ID/packagecloud'
  entrypoint: '/bin/bash'
  args: ['tools/ci/scripts/packagecloud-push.sh']
  env:
  - 'COMPILER=$_COMPILER'
  - 'BUILD_TYPE=$_BUILD_TYPE'
  - 'TAG_NAME=$TAG_NAME'
  - 'PACKAGECLOUD_TOKEN=$_PACKAGECLOUD_TOKEN'

timeout: 3600s

substitutions:
  _BUILD_TYPE: release
  _COMPILER: gcc
  _PACKAGECLOUD_TOKEN: "na"

options:
  machineType: 'N1_HIGHCPU_32'

artifacts:
  objects:
    location: 'gs://vectorizedio/rp/$_BUILD_TYPE/$SHORT_SHA/'
    paths:
    - 'build/$_BUILD_TYPE/dist/tar/*.tar.gz'
    - 'build/$_BUILD_TYPE/dist/debian/*.deb'
    - 'build/$_BUILD_TYPE/dist/rpm/RPMS/x86_64/*.rpm'
