steps:
- id: 'build builder image'
  name: 'gcr.io/kaniko-project/executor:latest'
  args: ['--dockerfile=tools/ci/Dockerfile',
         '--destination=gcr.io/$PROJECT_ID/builder:$SHORT_SHA',
         '--cache=true']

- id: 'configure'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  args: ['cmake', '-GNinja', '-B./build', '-DCMAKE_BUILD_TYPE=${_BUILD_TYPE}',
         '-DRP_ENABLE_GOLD_LINKER=OFF', '-DV_MANAGE_DEPS=OFF', '.']
  env:
  - 'CC=clang'
  - 'CXX=clang++'
  - 'BOOST_TEST_LOG_LEVEL=test_suite'
  - 'BOOST_TEST_COLOR_OUTPUT=0'

- id: 'build cpp'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  dir: 'build/'
  args: ['ninja', '-C', '/workspace/build/']

- id: 'test cpp'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  dir: 'build/'
  args: ['ctest', '-VV']

- id: 'test go'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  dir: 'src/go/pkg'
  args: ['go', 'test', './...']

- id: 'build go exe'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  dir: 'src/go/pkg'
  args: ['go', 'install', './...']
  env:
  - 'GOBIN=/workspace/build/go/bin'

- id: 'package'
  name: 'gcr.io/$PROJECT_ID/builder:$SHORT_SHA'
  args: ['tools/packaging.py',
         '--formats', 'rpm', 'deb', 'tar',
         '--external', '/usr/local/bin/iotune', '/usr/local/bin/hwloc-calc',
         '/usr/local/bin/hwloc-distrib']

timeout: 3600s

substitutions:
  _BUILD_TYPE: Release

options:
  machineType: 'N1_HIGHCPU_32'

artifacts:
  objects:
    location: 'gs://vectorizedio/rp/${_BUILD_TYPE}/${SHORT_SHA}/'
    paths:
    - 'build/dist/tar/*.tar.gz'
    - 'build/dist/debian/*.deb'
    - 'build/dist/rpm/RPMS/x86_64/*.rpm'
