#!/usr/bin/env bash

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
root_dir=$(git -C ${script_dir} rev-parse --show-toplevel)

pushd ${root_dir}
git ls-files --full-name "*.cc" "*.java" "*.h" "*.proto" | xargs -n1 clang-format -i -style=file -fallback-style=none
popd
