#!/usr/bin/env bash

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
root_dir=$(git -C ${script_dir} rev-parse --show-toplevel)

pushd ${root_dir}
git ls-files "*.py" | xargs -P 8 -n 8 yapf -i
popd
