#!/usr/bin/env bash
#
# go install github.com/bazelbuild/buildtools/buildifier@latest
#
# TODO
#  - could arrange for `bazel run //:buildifier` to work

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
root_dir=$(git -C ${script_dir} rev-parse --show-toplevel)

pushd ${root_dir}
# list *.BUILD explicitly it doesn't seem to get picked up automatically
buildifier -r -lint=fix -mode=fix -type=auto . bazel/thirdparty/*.BUILD
popd
