#!/usr/bin/env bash

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
root_dir=$(git -C ${script_dir} rev-parse --show-toplevel)

gcovr --gcov-executable "llvm-cov gcov" --root ${root_dir} \
  --exclude "_deps/" --html-details \
  --html-self-contained -o coverage.html \
  --txt - $@
