#!/usr/bin/python3
#
# ==================================================================
# Copyright 2026 Redpanda Data, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0
# ==================================================================
#
# Package a Bazel-built C++ binary into an Antithesis-compatible Docker
# image using the antithesis_test_image() Bazel macro.
#
# Usage:
#   ./tools/antithesis/single_binary_test_package.py //src/v/lsm/db/tests:memtable_test
#   ./tools/antithesis/single_binary_test_package.py //src/v/lsm/db/tests:db_bench --binary-args='--duration 60'
#   ./tools/antithesis/single_binary_test_package.py //src/v/lsm/db/tests:db_bench --tag myregistry/db_bench:v1
#

import argparse
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

_BASE_SEASTAR_ARGS = [
    "--blocked-reactor-notify-ms 2000000",
    "--abort-on-seastar-bad-alloc",
    "--overprovisioned",
]

_GEN_DIR = ".antithesis"


def _config_tag(image_tag: str) -> str:
    """Derive the config image tag by inserting '-config' before the :tag suffix."""
    if ":" in image_tag:
        repo, tag = image_tag.rsplit(":", 1)
        return f"{repo}-config:{tag}"
    return f"{image_tag}-config"


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent.parent


def parse_bazel_target(target: str) -> tuple[str, str]:
    """//src/v/lsm/db/tests:db_bench -> ("src/v/lsm/db/tests", "db_bench")"""
    if ":" in target:
        pkg, name = target.split(":", 1)
    else:
        pkg = target
        name = target.rsplit("/", 1)[-1]
    return pkg.lstrip("/"), name


def query_target_info(target: str) -> tuple[str, list[str], dict[str, str]]:
    """Query Bazel for rule kind, args, and env via XML output."""
    result = subprocess.run(
        ["bazel", "query", "--output=xml", target],
        capture_output=True,
        text=True,
        cwd=repo_root(),
    )
    if result.returncode != 0:
        print(f"Warning: bazel query failed for {target}", file=sys.stderr)
        return ("cc_binary", [], {})

    root = ET.fromstring(result.stdout)
    rule = root.find(".//rule")
    if rule is None:
        return ("cc_binary", [], {})

    rule_kind = rule.get("class", "cc_binary")

    args_elem = rule.find("list[@name='args']")
    args = [
        s.get("value", "")
        for s in (args_elem if args_elem is not None else [])
        if s.get("value")
    ]

    env: dict[str, str] = {}
    env_elem = rule.find("dict[@name='env']")
    for pair in env_elem if env_elem is not None else []:
        strings = pair.findall("string")
        if len(strings) == 2 and strings[0].get("value"):
            env[strings[0].get("value", "")] = strings[1].get("value", "")

    return rule_kind, args, env


_EXCLUDED_ENV = {
    # Antithesis needs random seeds to explore different execution paths.
    "REDPANDA_RNG_SEEDING_MODE_DEFAULT",
    "REDPANDA_RNG_SEEDING_MODE",
}


def filter_env(env: dict[str, str]) -> dict[str, str]:
    """Remove env vars that are inappropriate for Antithesis testing."""
    return {k: v for k, v in env.items() if k not in _EXCLUDED_ENV}


def build_runtime_args(
    rule_kind: str, bazel_args: list[str], binary_args: str
) -> list[str]:
    """For cc_test: use Bazel args. For cc_binary: no resource constraints.
    Always include base Seastar flags."""
    args = list(bazel_args) if rule_kind == "cc_test" else []

    for flag in _BASE_SEASTAR_ARGS:
        prefix = flag.split()[0] if " " in flag else flag.split("=")[0]
        if not any(a.startswith(prefix) for a in args):
            args.append(flag)

    if binary_args:
        args.extend(binary_args.split())
    return args


def starlark_str_list(items: list[str]) -> str:
    inner = ", ".join(f'"{item}"' for item in items)
    return f"[{inner}]"


def starlark_str_dict(d: dict[str, str]) -> str:
    if not d:
        return "{}"
    pairs = ", ".join(
        f'"{k}": "{v}"'
        for k, v in d.items()
        if "$(rootpath" not in v and "$(location" not in v
    )
    return "{" + pairs + "}"


def build_pkg(target_name: str) -> str:
    return f"{_GEN_DIR}/{target_name}"


def generate_build_file(
    target: str,
    target_name: str,
    runtime_args: list[str],
    env: dict[str, str],
    image_tag: str,
) -> Path:
    """Write a BUILD.bazel that uses antithesis_test_image()."""
    pkg = build_pkg(target_name)
    build_dir = repo_root() / pkg
    build_dir.mkdir(parents=True, exist_ok=True)

    build_file = build_dir / "BUILD.bazel"
    build_file.write_text(f"""\
# AUTO-GENERATED by tools/antithesis/single_binary_test_package.py — do not edit.
load("//bazel/antithesis:antithesis.bzl", "antithesis_test_image")

antithesis_test_image(
    name = "image",
    binary = "{target}",
    args = {starlark_str_list(runtime_args)},
    env = {starlark_str_dict(env)},
    image_tag = "{image_tag}",
)
""")
    return build_file


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Package a Bazel C++ binary for Antithesis testing."
    )
    parser.add_argument(
        "target", help="Bazel label (e.g. //src/v/lsm/db/tests:db_bench)"
    )
    parser.add_argument(
        "--binary-args",
        default="",
        help="Extra arguments passed to the binary at runtime",
    )
    parser.add_argument(
        "--name",
        default="",
        help="Custom target name for the image and generated "
        "artifacts (default: derived from Bazel label)",
    )
    parser.add_argument(
        "--tag", default="", help="Docker image tag (default: antithesis/<name>:latest)"
    )
    parser.add_argument(
        "--bazel-args", default="", help="Extra arguments passed to bazel build"
    )
    parser.add_argument(
        "--instrumented",
        action="store_true",
        help="Build with --config=antithesis for coverage "
        "instrumentation (trace-pc-guard)",
    )
    args = parser.parse_args()

    _, default_name = parse_bazel_target(args.target)
    target_name = args.name or default_name
    image_tag = args.tag or f"{target_name}:latest"
    extra_bazel_args = args.bazel_args.split() if args.bazel_args else []
    if args.instrumented:
        extra_bazel_args.append("--config=antithesis")

    # Query Bazel for the target's rule kind, args, and env.
    print(f"==> Querying target info for {args.target}")
    rule_kind, bazel_args, bazel_env = query_target_info(args.target)
    print(f"    Rule kind: {rule_kind}")

    runtime_args = build_runtime_args(rule_kind, bazel_args, args.binary_args)
    bazel_env = filter_env(bazel_env)

    pkg = build_pkg(target_name)

    # Generate the BUILD file that invokes the macro.
    print(f"==> Generating {pkg}/BUILD.bazel")
    generate_build_file(args.target, target_name, runtime_args, bazel_env, image_tag)

    # Build the image and load it into Docker.
    # --check_visibility=false is needed because test targets are typically
    # package-private, and we're referencing them from a generated package.
    bazel_flags = ["--check_visibility=false"] + extra_bazel_args

    label = f"//{pkg}:image_load"
    print(f"==> Running {label}")
    subprocess.check_call(
        ["bazel", "run"] + bazel_flags + [label],
        cwd=repo_root(),
    )

    # Build and load the config image (docker-compose.yml for Antithesis).
    config_label = f"//{pkg}:image_config_load"
    print(f"==> Running {config_label}")
    subprocess.check_call(
        ["bazel", "run"] + bazel_flags + [config_label],
        cwd=repo_root(),
    )

    # The compose file is a separate output for local use.
    compose_label = f"//{pkg}:image_compose"
    print(f"==> Building {compose_label}")
    subprocess.check_call(
        ["bazel", "build"] + bazel_flags + [compose_label],
        cwd=repo_root(),
    )

    compose_path = repo_root() / "bazel-bin" / pkg / "docker-compose.yaml"
    config_tag = _config_tag(image_tag)

    print(f"""
Images loaded:
  workload: {image_tag}
  config:   {config_tag}

Run locally:
  docker compose -f {compose_path} up
  # Then in another terminal:
  docker compose -f {compose_path} exec workload \\
      /opt/antithesis/test/v1/quickstart/singleton_driver_{default_name}.sh

Push to Antithesis registry:
  TENANT=<your-tenant-name>
  REGISTRY=us-central1-docker.pkg.dev/molten-verve-216720/$TENANT-repository
  docker tag {image_tag} $REGISTRY/{target_name}:latest
  docker push $REGISTRY/{target_name}:latest
  docker tag {config_tag} $REGISTRY/{target_name}-config:latest
  docker push $REGISTRY/{target_name}-config:latest
""")


if __name__ == "__main__":
    main()
