# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/redpanda-data/pre-commit-vectorizedio.git
    rev: 91f6656b0fd532cdf325536a1daf8f28a8fa670c
    hooks:
      - id: golangci-lint
        args:
          - src/go/k8s
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks
      - id: detect-private-key
  - repo: https://github.com/dnephin/pre-commit-golang.git
    rev: master
    hooks:
      - id: go-mod-tidy
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.5.0
    hooks:
      - id: helm-docs
