apiVersion: v1
kind: Namespace
metadata:
  name: redpanda
---
apiVersion: redpanda.vectorized.io/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef:
    chartVersion: "2.13.2"
  clusterSpec:
    statefulset:
      replicas: 1
