/*
 * Copyright 2025 Redpanda Data, Inc.
 *
 * Licensed as a Redpanda Enterprise file under the Redpanda Community
 * License (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * https://github.com/redpanda-data/redpanda/blob/master/licenses/rcl.md
 */

#pragma once

#include "cloud_topics/level_one/common/file_io.h"
#include "cloud_topics/level_one/frontend_reader/level_one_reader_probe.h"
#include "cloud_topics/level_one/maintenance/log_collector.h"
#include "cloud_topics/level_one/maintenance/log_info_collector.h"
#include "cloud_topics/level_one/maintenance/meta.h"
#include "cloud_topics/level_one/maintenance/scheduler_probe.h"
#include "cloud_topics/level_one/maintenance/scheduling_policies.h"
#include "cloud_topics/level_one/maintenance/worker_manager.h"
#include "cloud_topics/level_one/metastore/replicated_metastore.h"
#include "config/property.h"
#include "model/fundamental.h"
#include "ssx/semaphore.h"

class SchedulerTestFixture;

namespace cloud_topics::l1 {

/*
 * The `maintenance_scheduler` contains all of the relevant objects required for
 * cloud topics maintenance (compaction and leveling). It exists on shard0 and
 * manages:
 *  - A `log_collector`, which pushes logs this broker is responsible for
 * maintaining to both a set and intrusive list of logs.
 * - A `log_info_collector` which fetches metadata for managed logs from the
 * metastore on a sampling interval. Compaction and leveling each have their
 * own scheduling loop with independent intervals.
 * - Separate `log_compaction_queue` and `log_leveling_queue` priority queues,
 * populated with shared pointers to managed logs that require maintenance,
 * sorted by a heuristic provided by the `scheduling_policy`.
 * - A `worker_manager` which manages a `maintenance_worker` on each shard,
 * which individually pull work from the queues on shard0. Updates generated by
 * workers are pushed to the `metastore` and cloud storage via multipart
 * uploads. Workers are alerted of new work on each scheduling loop iteration.
 */
class maintenance_scheduler {
public:
    maintenance_scheduler(
      maintenance_cluster_state,
      ss::sharded<file_io>*,
      ss::sharded<l1::replicated_metastore>*,
      ss::sharded<level_one_reader_probe>*);

    // Starts the contained `_log_collector`, `_worker_manager`, and the
    // backgrounded scheduling loop.
    ss::future<> start();

    // Shuts down concurrency primitives, thereby stopping the backgrounded
    // scheduling loops, stops the `_log_collector`, requests inflight
    // maintenance jobs in the `_worker_manager` be stopped, drains the managed
    // partition log list, and finally shuts down the `_worker_manager` once it
    // is safe to do so.
    ss::future<> stop();

    // Returns `true` iff the provided `tidp` is managed by this scheduler.
    bool is_managed(const model::ntp&) const noexcept;

    // Pushes a new `tidp` to be managed by this scheduler to the list of
    // `tidp`s. It is the caller's responsibility to ensure the partition is
    // not already managed by this scheduler.
    void manage_partition(
      const model::ntp&, const model::topic_id_partition&, std::string_view);

    // Removes the `tidp` from the list of managed partitions. No-ops if the
    // provided `tidp` is not managed by this scheduler. Because the `tidp`
    // may be undergoing inflight maintenance, an early stop is requested by
    // the `_worker_manager`.
    void unmanage_partition(const model::ntp&, std::string_view);

private:
    // Starts the backgrounded scheduling loops.
    void start_bg_loop();

    // The compaction scheduling loop. Invoked in a background fiber until
    // `_as` has an abort requested or the `_gate` is closed.
    ss::future<> compaction_scheduling_loop();

    // The leveling scheduling loop. Invoked in a background fiber until
    // `_as` has an abort requested or the `_gate` is closed.
    ss::future<> leveling_scheduling_loop();

private:
    // Pointer to sharded `file_io` held by `app`. Used by the `worker_manager`
    // for reading L1 objects and writing compacted objects to cloud storage.
    ss::sharded<file_io>* _io;

    // Pointer to metastore.
    ss::sharded<replicated_metastore>* _metastore;

private:
    // Responsible for pushing logs to manage/unmanage to this scheduler.
    std::unique_ptr<log_collector> _log_collector;

    // Responsible for collecting maintenance metadata (compaction and leveling
    // info) for managed logs during their respective scheduling loops.
    log_info_collector _log_info_collector;

    // Responsible for sorting logs collected by the info collector for
    // compaction and leveling.
    std::unique_ptr<scheduling_policy> _scheduling_policy;

    // Responsible for dispatching maintenance jobs to per-shard workers.
    worker_manager _worker_manager;

    // The interval on which compaction loop is executed.
    config::binding<std::chrono::milliseconds> _compaction_interval;

    // The interval on which leveling loop is executed.
    config::binding<std::chrono::milliseconds> _leveling_interval;

    // Semaphores used to signal config changes during the `wait()` operation
    // in each scheduling loop.
    ssx::semaphore _compaction_sem{
      0, "cloud_topics::maintenance::compaction_scheduling_loop"};
    ssx::semaphore _leveling_sem{
      0, "cloud_topics::maintenance::leveling_scheduling_loop"};

    ss::abort_source _as;
    ss::gate _gate;

    // Set of logs this scheduler is responsible for issuing maintenance jobs
    // for.
    log_set_t _logs;

    // Intrusive list of logs this scheduler is responsible for issuing
    // maintenance jobs for.
    log_list_t _logs_list;

    // Container of pointers to logs in `_logs/_logs_list` which have sampled
    // compaction metadata available and are available for compaction.
    log_compaction_queue _compaction_queue;

    // Container of pointers to logs in `_logs/_logs_list` which have sampled
    // leveling metadata available and are available for leveling.
    log_leveling_queue _leveling_queue;

    // TODO: remove this once more cluster objects speak `topic_id_partition`.
    chunked_hash_map<model::ntp, model::topic_id_partition> _ntp_to_tidp;

private:
    maintenance_scheduler_probe _probe;

    friend class ::SchedulerTestFixture;

    // Testing c-tor
    maintenance_scheduler(log_info_collector);
};

} // namespace cloud_topics::l1
