from _typeshed import Incomplete
from collections.abc import Generator
from typing import Any
from ducktape.cluster.cluster_spec import ClusterSpec as ClusterSpec
from ducktape.cluster.cluster import Cluster
from ducktape.command_line.defaults import ConsoleDefaults as ConsoleDefaults
from ducktape.mark.resource import (
    CLUSTER_SIZE_KEYWORD as CLUSTER_SIZE_KEYWORD,
    CLUSTER_SPEC_KEYWORD as CLUSTER_SPEC_KEYWORD,
)
from ducktape.services.service_registry import ServiceRegistry as ServiceRegistry
from ducktape.template import TemplateRenderer as TemplateRenderer
from ducktape.tests.loggermaker import (
    LoggerMaker as LoggerMaker,
    close_logger as close_logger,
)
from ducktape.tests.status import FAIL as FAIL, OFAIL as OFAIL
from ducktape.utils.local_filesystem_utils import mkdir_p as mkdir_p
from logging import Logger

class Test(TemplateRenderer):
    test_context: TestContext

    def __init__(
        self, test_context: TestContext, *args: list[Any], **kwargs: dict[str, Any]
    ) -> None: ...
    @property
    def cluster(self) -> Cluster: ...
    @property
    def logger(self) -> Logger: ...
    def min_cluster_spec(self): ...
    def min_cluster_size(self) -> None: ...
    def setup(self) -> None: ...
    def teardown(self) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def free_nodes(self) -> None: ...
    def compress_service_logs(self, node, service, node_logs): ...
    def copy_service_logs(self, test_status) -> None: ...
    def mark_for_collect(self, service, log_name: Incomplete | None = ...) -> None: ...
    def mark_no_collect(self, service, log_name: Incomplete | None = ...) -> None: ...
    def should_collect_log(self, log_name, service): ...

def test_logger(logger_name, log_dir, debug): ...

class TestLoggerMaker(LoggerMaker):
    log_dir: Incomplete
    debug: Incomplete

    def __init__(self, logger_name, log_dir, debug) -> None: ...
    def configure_logger(self) -> None: ...

class TestContext:
    session_context: Incomplete
    cluster: Cluster
    module: Incomplete
    test_suite_name: str
    file: str | None
    cls: Incomplete
    function: Incomplete
    injected_args: Incomplete
    ignore: bool
    ok_to_fail: bool
    cluster_use_metadata: Incomplete
    services: ServiceRegistry
    test_index: Incomplete
    log_collect: Incomplete

    def __init__(self, **kwargs) -> None: ...
    def copy(self, **kwargs): ...
    @property
    def local_scratch_dir(self): ...
    @property
    def test_metadata(self): ...
    @staticmethod
    def logger_name(test_context, test_index): ...
    @staticmethod
    def results_dir(test_context, test_index): ...
    @property
    def expected_num_nodes(self): ...
    @property
    def expected_cluster_spec(self): ...
    @property
    def globals(self) -> dict[str, Any]: ...
    @property
    def module_name(self): ...
    @property
    def cls_name(self): ...
    @property
    def function_name(self): ...
    @property
    def description(self): ...
    @property
    def injected_args_name(self): ...
    @property
    def test_id(self): ...
    @property
    def test_name(self): ...
    @property
    def logger(self) -> Logger: ...
    def close(self) -> None: ...

def in_dir(path) -> Generator[None, None, None]: ...
def in_temp_dir() -> Generator[Incomplete, None, None]: ...
