from ducktape.cluster.cluster_spec import ClusterSpec as ClusterSpec
from ducktape.cluster.node_container import NodeContainer as NodeContainer

from .cluster import Cluster as Cluster
from .cluster import ClusterNode as ClusterNode
from .linux_remoteaccount import LinuxRemoteAccount as LinuxRemoteAccount
from .remoteaccount import RemoteAccountSSHConfig as RemoteAccountSSHConfig

class LocalhostCluster(Cluster):
    def __init__(self, *args, **kwargs) -> None: ...
    def do_alloc(self, cluster_spec): ...
    def free_single(self, node) -> None: ...
    def available(self): ...
    def used(self): ...
