- hosts: redpanda
  roles:
  - cloudalchemy.node-exporter
  
  tasks:

  - name: amazon setup
    when: ansible_distribution == 'Amazon'
    block:
      - name: install java
        shell: "amazon-linux-extras enable java-openjdk11"
        become: yes

  - name: fedora setup
    when: ansible_os_family == 'RedHat'
    block:
    - name: delete unused repos
      file:
        name: "{{item}}"
        state: absent
      with_items:
        - /etc/yum.repos.d/fedora-updates-modular.repo
        - /etc/yum.repos.d/fedora-cisco-openh264.repo
    - name: install base deps
      package:
        name:
          - iotop
          - java-11-openjdk-devel.x86_64
          - mdadm
          - xfsprogs
        state: present

  - name: add additional debian repos
    when: ansible_distribution == 'Debian'
    apt_repository:
      repo: deb http://deb.debian.org/debian stretch-backports main
      state: present

  - name: update packages - debian
    apt:
      update_cache: yes
      force_apt_get: yes
    when: ansible_os_family == 'Debian'

  - name: install base deps - debian
    apt:
      name:
        - iotop
        - mdadm
        - openjdk-11-jdk-headless
        - xfsprogs
      state: present
      update_cache: yes
    when: ansible_os_family == 'Debian'

  - name: install kafka binaries
    unarchive:
      src: 'https://s3-us-west-2.amazonaws.com/kafka-packages/kafka_2.12-2.4.0.tgz'
      dest: /opt/
      remote_src: yes
      creates: /opt/kafka_2.12-2.4.0
  - name: create kafka-dev symlink directory referenced in tests
    file:
      src: /opt/kafka_2.12-2.4.0
      dest: /opt/kafka-dev
      state: link
