- include: install-test-node-deps.yml

- include: prepare-data-dir-raid.yml
  when: with_raid | default(False)

- include: prepare-data-dir.yml
  when: not (with_raid | default(False))

- include: install-redpanda.yml
