cc_library(
    name = "transform-sdk",
    srcs = ["src/transform_sdk.cc"],
    hdrs = ["include/redpanda/transform_sdk.h"],
    copts = [
        "-std=c++23",
        "-fno-exceptions",
    ],
    includes = ["include"],
)
