project_name: rpk
builds:
  - id: windows-and-linux
    main: ./cmd/rpk
    binary: rpk
    ldflags:
      - -X github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/cmd/version.version={{.Tag}}
      - -X github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/cmd/version.rev={{.ShortCommit}}
      - -X github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/cmd/container/common.tag={{.Tag}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
  # we need separate build for darwin to sign/notarize using quill
  - id: darwin
    main: ./cmd/rpk
    binary: rpk
    ldflags:
      - -X github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/cmd/version.version={{.Tag}}
      - -X github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/cmd/version.rev={{.ShortCommit}}
      - -X github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/cmd/container/common.tag={{.Tag}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        # The binary is signed and notarized when running a production release, but for snapshot builds notarization is
        # skipped and only ad-hoc signing is performed (not cryptographic material is needed).
        #
        # note: environment variables required for signing and notarization (set in CI) but are not needed for snapshot builds
        #    QUILL_SIGN_P12, QUILL_SIGN_PASSWORD, QUILL_NOTARY_KEY, QUILL_NOTARY_KEY_ID, QUILL_NOTARY_ISSUER
        - cmd: quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
          env:
            - QUILL_LOG_FILE=dist/quill-{{ .Target }}.log
archives:
  - id: rpk
    builds:
      - windows-and-linux
      - darwin
    format: zip
    name_template: "rpk-{{ .Os }}-{{ .Arch }}"
release:
  github:
    owner: redpanda-data
    name: redpanda
  draft: true
  discussion_category_name: Releases
brews:
  - name: redpanda
    homepage: "https://redpanda.com"
    description: "Redpanda CLI & toolbox"
    tap:
      owner: redpanda-data
      name: homebrew-tap
    folder: Formula
    skip_upload: auto
    caveats: |
        Redpanda Keeper (rpk) is Redpanda's command line interface (CLI)
        utility. The rpk commands let you configure, manage, and tune
        Redpanda clusters. They also let you manage topics, groups,
        and access control lists (ACLs).
        Start a three-node docker cluster locally:

            rpk container start -n 3

        Interact with the cluster using commands like:

            rpk topic list

        When done, stop and delete the docker cluster:

            rpk container purge

        For more examples and guides, visit: https://docs.redpanda.com
    commit_author:
      name: vbotbuildovich
      email: vbot@redpanda.com
announce:
  skip: "true"
