---
name: Trigger redpanda install-pack bump
on:
  release:
    types: [published]
permissions:
  id-token: write
  contents: read
jobs:
  check-version:
    outputs:
      is_supported: ${{ steps.check_version.outputs.is_supported }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout redpanda dev
        uses: actions/checkout@v5
        with:
          ref: 'dev'
      - name: Check if version is supported in cloud
        id: check_version
        run: |
          set -eo pipefail
          supported_ga=$(git tag --list | grep '^v.*' | grep -v '\-dev' | grep -v '\-rc' | awk -F. '{print $1 "." $2}' | sort | uniq | tail -2)
          if grep "$supported" <<< "${{ github.ref_name }}" ; then
            echo "is_supported=true" >>$GITHUB_OUTPUT
          else
            echo "is_supported=false" >>$GITHUB_OUTPUT
          fi
  trigger-bump:
    needs: check-version
    runs-on: ubuntu-latest
    if: needs.check-version.outputs.is_supported == 'true'
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.RP_AWS_CRED_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.RP_AWS_CRED_ACCOUNT_ID }}:role/${{ vars.RP_AWS_CRED_BASE_ROLE_NAME }}${{ github.event.repository.name }}
      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
            ,sdlc/prod/github/buildkite_token
          parse-json-secrets: true
      - uses: actions/checkout@v4
        with:
          repository: redpanda-data/sparse-checkout
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          path: sparse-checkout
      - uses: ./sparse-checkout
        with:
          repository: redpanda-data/vtools
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          patterns: actions
          path: ghca
      - name: Trigger Versions Bump Buildkite Job
        uses: ./ghca/actions/buildkite-pipeline-trigger
        with:
          buildkite_token: ${{ env.BUILDKITE_TOKEN }}
          buildkite_org: redpanda
          buildkite_pipeline: ${{ vars.CLOUD_PIPELINE }}
          commit: HEAD
          branch: ${{ vars.CLOUD_DEFAULT_BRANCH }}
          message: Install Pack version bump trigger
          env: '{"INSTALLPACK_BUMP": "1", "RELEASE_VERSION": "${{ github.ref_name }}"}'
