name: Manage JIRA Issue
on:
  issues:
    types:
      - opened
      - reopened
      - edited
      - closed
      - deleted
      - labeled
      - unlabeled


jobs:
  manage_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: install dependencies
        env:
          SCRIPT_DIR: ${{ github.workspace }}/.github/workflows/scripts
        run: pip install -r ${SCRIPT_DIR}/requirements.txt
      - name: Manage JIRA Issue
        env:
          SCRIPT_DIR: ${{ github.workspace }}/.github/workflows/scripts
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN  }}
          JIRA_USER: ${{ secrets.JIRA_USER  }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name) }}
          ISSUE_STATE: ${{ github.event.issue.state }}
          EVENT_NAME: ${{ github.event.action }}
        run: python ${SCRIPT_DIR}/jira_helper.py ISSUE --verbose
