---
name: Lint sh
on:
  push:
    branches: [dev]
    paths:
      - '**.bash'
      - '**.sh'
      - '.github/workflows/lint-sh.yml'
      - '.buildkite/hooks/*'
      - 'tests/docker/ducktape-deps/*'
      - 'tools/*'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - '**.bash'
      - '**.sh'
      - '.github/workflows/lint-sh.yml'
      - '.buildkite/hooks/*'
      - 'tests/docker/ducktape-deps/*'
      - 'tools/*'
  merge_group:
    types: [checks_requested]
jobs:
  sh:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install shfmt
        env:
          SHFMT_VER: 3.12.0
        run: |
          mkdir -v -p "$HOME/.local/bin"
          wget -O "$HOME/.local/bin/shfmt" "https://github.com/mvdan/sh/releases/download/v${SHFMT_VER}/shfmt_v${SHFMT_VER}_linux_amd64"
          chmod 0700 "$HOME/.local/bin/shfmt"
      - name: Run shfmt
        run: |
          shfmt=(shfmt -i 2 -ci -s)
          if ! "${shfmt[@]}" -d .; then
            echo -e "============\nshfmt lint failed, run this locally to fix (from redpanda root):"
            echo -e "${shfmt[@]} -w .\n============"
            exit 1
          fi
