---
name: Lint cpp
on:
  push:
    branches: [dev]
    paths:
      - '**.h'
      - '**.cc'
      - '**.cpp'
      - '**.proto'
      - '**.java'
      - '.github/workflows/lint-cpp.yml'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - '**.h'
      - '**.cc'
      - '**.cpp'
      - '**.proto'
      - '**.java'
      - '.github/workflows/lint-cpp.yml'
  merge_group:
    types: [checks_requested]
jobs:
  cpp:
    name: Lint files with clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Share repository cache between workflows.
          repository-cache: true
      - name: Run clang-format
        env:
          # Bazel uses this to enforce strict sandboxing - we can't do it in Github Actions,
          # so set CI=false to disable the check we do in `//tools:bazel`
          CI: false
        # Don't update the lockfile for this
        run: |
          bazel run --lockfile_mode=off //tools:clang_format
          git diff --exit-code
