---
name: lint-yaml
on:
  push:
    branches: [dev]
    paths:
      - '.yamllint'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '.yamllint'
      - '.github/workflows/*.yml'
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yamllint -f github .yamllint .github/workflows/*.yml
