name: Lint python

on:
  push:
    branches:
      - 'dev'
    paths:
      - '**.py'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - '**.py'

jobs:
  py:
    name: Lint python files
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install yapf
      run: |
        python3 -mvenv /tmp/venv/yapf
        source /tmp/venv/yapf/bin/activate
        pip install yapf==0.40.1

    - name: Run yapf
      run: find . -type f -name '*.py' | xargs -n8 /tmp/venv/yapf/bin/yapf -d
